MASTER_BALL   EQU $01
ULTRA_BALL    EQU $02
GREAT_BALL    EQU $03
POKE_BALL     EQU $04
TOWN_MAP      EQU $05
BICYCLE       EQU $06
SURFBOARD     EQU $07 ; buggy?
SAFARI_BALL   EQU $08
POKEDEX       EQU $09
MOON_STONE    EQU $0A
ANTIDOTE      EQU $0B
BURN_HEAL     EQU $0C
ICE_HEAL      EQU $0D
AWAKENING     EQU $0E
PARLYZ_HEAL   EQU $0F
FULL_RESTORE  EQU $10
MAX_POTION    EQU $11
HYPER_POTION  EQU $12
SUPER_POTION  EQU $13
POTION        EQU $14
BAIT_ITEM     EQU $15
ROCK_ITEM     EQU $16
; XXX ????? EQU $17
; XXX ????? EQU $18
; XXX ????? EQU $19
; XXX ????? EQU $1A
; XXX ????? EQU $1B
; XXX ????? EQU $1C
ESCAPE_ROPE   EQU $1D
REPEL         EQU $1E
OLD_AMBER     EQU $1F
FIRE_STONE    EQU $20
THUNDER_STONE EQU $21
WATER_STONE   EQU $22
HP_UP         EQU $23
PROTEIN       EQU $24
IRON          EQU $25
CARBOS        EQU $26
CALCIUM       EQU $27
RARE_CANDY    EQU $28
DOME_FOSSIL   EQU $29
HELIX_FOSSIL  EQU $2A
SECRET_KEY    EQU $2B
TRADE_STONE   EQU $2C
BIKE_VOUCHER  EQU $2D
X_ACCURACY    EQU $2E
LEAF_STONE    EQU $2F
CARD_KEY      EQU $30
NUGGET        EQU $31
TECH_MACHINE  EQU $32
POKE_DOLL     EQU $33
FULL_HEAL     EQU $34
REVIVE        EQU $35
MAX_REVIVE    EQU $36
GUARD_SPEC_   EQU $37
SUPER_REPEL   EQU $38
MAX_REPEL     EQU $39
DIRE_HIT      EQU $3A
COIN          EQU $3B
FRESH_WATER   EQU $3C
SODA_POP      EQU $3D
LEMONADE      EQU $3E
S_S__TICKET   EQU $3F
GOLD_TEETH    EQU $40
X_ATTACK      EQU $41
X_DEFEND      EQU $42
X_SPEED       EQU $43
X_SPECIAL     EQU $44
COIN_CASE     EQU $45
OAKS_PARCEL   EQU $46
ITEMFINDER    EQU $47
SILPH_SCOPE   EQU $48
POKE_FLUTE    EQU $49
LIFT_KEY      EQU $4A
FOCUS         EQU $4B
OLD_ROD       EQU $4C
GOOD_ROD      EQU $4D
SUPER_ROD     EQU $4E
; XXX todo: compare this to $32
PP_UP         EQU $4F
ETHER         EQU $50
MAX_ETHER     EQU $51
ELIXER        EQU $52
MAX_ELIXER    EQU $53

HM_01         EQU $54 ; NATURE POWER
HM_02         EQU $55 ; AIR POWER
HM_03         EQU $56 ; WATER POWER
HM_04         EQU $57 ; EARTH POWER
HM_05         EQU $58 ; FIRE POWER

TM_01         EQU $C4
TM_02         EQU $C5
TM_03         EQU $C6
TM_04         EQU $C7
TM_05         EQU $C8
TM_06         EQU $C9
TM_07         EQU $CA
TM_08         EQU $CB
TM_09         EQU $CC
TM_10         EQU $CD
TM_11         EQU $CE
TM_12         EQU $CF
TM_13         EQU $D0
TM_14         EQU $D1
TM_15         EQU $D2
TM_16         EQU $D3
TM_17         EQU $D4
TM_18         EQU $D5
TM_19         EQU $D6
TM_20         EQU $D7
TM_21         EQU $D8
TM_22         EQU $D9
TM_23         EQU $DA
TM_24         EQU $DB
TM_25         EQU $DC
TM_26         EQU $DD
TM_27         EQU $DE
TM_28         EQU $DF
TM_29         EQU $E0
TM_30         EQU $E1
TM_31         EQU $E2
TM_32         EQU $E3
TM_33         EQU $E4
TM_34         EQU $E5
TM_35         EQU $E6
TM_36         EQU $E7
TM_37         EQU $E8
TM_38         EQU $E9
TM_39         EQU $EA
TM_40         EQU $EB
TM_41         EQU $EC
TM_42         EQU $ED
TM_43         EQU $EE
TM_44         EQU $EF
TM_45         EQU $F0
TM_46         EQU $F1
TM_47         EQU $F2
TM_48         EQU $F3
TM_49         EQU $F4
TM_50         EQU $F5
TM_51         EQU $F6
TM_52         EQU $F7
TM_53         EQU $F8
TM_54         EQU $F9
TM_55         EQU $FA
TM_56         EQU $FB