; characteristics of each move
; animation,effect,power,type,accuracy,PP

    db POUND        , NO_ADDITIONAL_EFFECT       ,  40 , NORMAL   , 255 , 35
    db KARATE_CHOP  , NO_ADDITIONAL_EFFECT       ,  50 , NORMAL   , 255 , 25
    db DOUBLESLAP   , TWO_TO_FIVE_ATTACKS_EFFECT ,  15 , NORMAL   , 216 , 10
    db COMET_PUNCH  , TWO_TO_FIVE_ATTACKS_EFFECT ,  18 , NORMAL   , 216 , 15
    db MEGA_PUNCH   , NO_ADDITIONAL_EFFECT       ,  80 , NORMAL   , 216 , 20
    db PAY_DAY      , PAY_DAY_EFFECT             ,  40 , NORMAL   , 255 , 20
    db FIRE_PUNCH   , BURN_SIDE_EFFECT1          ,  75 , FIRE     , 255 , 15
    db ICE_PUNCH    , FREEZE_SIDE_EFFECT         ,  75 , ICE      , 255 , 15
    db THUNDERPUNCH , PARALYZE_SIDE_EFFECT1      ,  75 , ELECTRIC , 255 , 15
    db SCRATCH      , NO_ADDITIONAL_EFFECT       ,  40 , NORMAL   , 255 , 35
    db VICEGRIP     , NO_ADDITIONAL_EFFECT       ,  55 , NORMAL   , 255 , 30
    db GUILLOTINE   , OHKO_EFFECT                ,   1 , NORMAL   ,  76 ,  5
    db RAZOR_WIND   , CHARGE_EFFECT              ,  80 , NORMAL   , 191 , 10
    db SWORDS_DANCE , ATTACK_UP2_EFFECT          ,   0 , NORMAL   , 255 , 30
    db BLADE        , NO_ADDITIONAL_EFFECT       ,  50 , NORMAL   , 242 , 30
    db GUST         , NO_ADDITIONAL_EFFECT       ,  40 , NORMAL   , 255 , 35
    db WING_ATTACK  , NO_ADDITIONAL_EFFECT       ,  35 , FLYING   , 255 , 35
    db WHIRLWIND    , SWITCH_AND_TELEPORT_EFFECT ,   0 , NORMAL   , 216 , 20
    db SWOOP        , FLY_EFFECT                 ,  70 , FLYING   , 242 , 15
    db BIND         , TRAPPING_EFFECT            ,  15 , NORMAL   , 191 , 20
    db SLAM         , NO_ADDITIONAL_EFFECT       ,  80 , NORMAL   , 191 , 20
    db VINE_WHIP    , NO_ADDITIONAL_EFFECT       ,  35 , GRASS    , 255 , 10
    db STOMP        , FLINCH_SIDE_EFFECT2        ,  65 , NORMAL   , 255 , 20
    db DOUBLE_KICK  , ATTACK_TWICE_EFFECT        ,  30 , FIGHTING , 255 , 30
    db MEGA_KICK    , NO_ADDITIONAL_EFFECT       , 120 , NORMAL   , 191 ,  5
    db JUMP_KICK    , JUMP_KICK_EFFECT           ,  70 , FIGHTING , 242 , 25
    db ROLLING_KICK , FLINCH_SIDE_EFFECT2        ,  60 , FIGHTING , 216 , 15
    db SAND_ATTACK  , ACCURACY_DOWN1_EFFECT      ,   0 , NORMAL   , 255 , 15
    db HEADBUTT     , FLINCH_SIDE_EFFECT2        ,  70 , NORMAL   , 255 , 15
    db HORN_ATTACK  , NO_ADDITIONAL_EFFECT       ,  65 , NORMAL   , 255 , 25
    db FURY_ATTACK  , TWO_TO_FIVE_ATTACKS_EFFECT ,  15 , NORMAL   , 216 , 20
    db HORN_DRILL   , OHKO_EFFECT                ,   1 , NORMAL   ,  76 ,  5
    db TACKLE       , NO_ADDITIONAL_EFFECT       ,  35 , NORMAL   , 242 , 35
    db BODY_SLAM    , PARALYZE_SIDE_EFFECT2      ,  85 , NORMAL   , 255 , 15
    db WRAP         , TRAPPING_EFFECT            ,  15 , NORMAL   , 216 , 20
    db TAKE_DOWN    , RECOIL_EFFECT              ,  90 , NORMAL   , 216 , 20
    db THRASH       , THRASH_PETAL_DANCE_EFFECT  ,  90 , NORMAL   , 255 , 20
    db DOUBLE_EDGE  , RECOIL_EFFECT              , 100 , NORMAL   , 255 , 15
    db TAIL_WHIP    , DEFENSE_DOWN1_EFFECT       ,   0 , NORMAL   , 255 , 30
    db POISON_STING , POISON_SIDE_EFFECT1        ,  15 , POISON   , 255 , 35
    db TWINEEDLE    , TWINEEDLE_EFFECT           ,  25 , BUG      , 255 , 20
    db PIN_MISSILE  , TWO_TO_FIVE_ATTACKS_EFFECT ,  14 , BUG      , 216 , 20
    db LEER         , DEFENSE_DOWN1_EFFECT       ,   0 , NORMAL   , 255 , 30
    db BITE         , FLINCH_SIDE_EFFECT1        ,  60 , NORMAL   , 255 , 25
    db GROWL        , ATTACK_DOWN1_EFFECT        ,   0 , NORMAL   , 255 , 40
    db ROAR         , SWITCH_AND_TELEPORT_EFFECT ,   0 , NORMAL   , 255 , 20
    db SING         , SLEEP_EFFECT               ,   0 , NORMAL   , 140 , 15
    db SUPERSONIC   , CONFUSION_EFFECT           ,   0 , NORMAL   , 140 , 20
    db SONICBOOM    , SPECIAL_DAMAGE_EFFECT      ,   1 , NORMAL   , 229 , 20
    db DISABLE      , DISABLE_EFFECT             ,   0 , NORMAL   , 140 , 20
    db ACID         , DEFENSE_DOWN_SIDE_EFFECT   ,  40 , POISON   , 255 , 30
    db EMBER        , BURN_SIDE_EFFECT1          ,  40 , FIRE     , 255 , 25
    db FLAMETHROWER , BURN_SIDE_EFFECT1          ,  95 , FIRE     , 255 , 15
    db MIST         , MIST_EFFECT                ,   0 , ICE      , 255 , 30
    db WATER_GUN    , NO_ADDITIONAL_EFFECT       ,  40 , WATER    , 255 , 25
    db HYDRO_PUMP   , NO_ADDITIONAL_EFFECT       , 120 , WATER    , 204 ,  5
    db TSUNAMI      , NO_ADDITIONAL_EFFECT       ,  95 , WATER    , 255 , 15
    db ICE_BEAM     , FREEZE_SIDE_EFFECT         ,  95 , ICE      , 255 , 10
    db BLIZZARD     , FREEZE_SIDE_EFFECT         , 120 , ICE      , 229 ,  5
    db PSYBEAM      , CONFUSION_SIDE_EFFECT      ,  65 , PSYCHIC  , 255 , 20
    db BUBBLEBEAM   , SPEED_DOWN_SIDE_EFFECT     ,  65 , WATER    , 255 , 20
    db AURORA_BEAM  , ATTACK_DOWN_SIDE_EFFECT    ,  65 , ICE      , 255 , 20
    db HYPER_BEAM   , HYPER_BEAM_EFFECT          , 150 , NORMAL   , 229 ,  5
    db PECK         , NO_ADDITIONAL_EFFECT       ,  35 , FLYING   , 255 , 35
    db DRILL_PECK   , NO_ADDITIONAL_EFFECT       ,  80 , FLYING   , 255 , 20
    db SUBMISSION   , RECOIL_EFFECT              ,  80 , FIGHTING , 204 , 25
    db LOW_KICK     , FLINCH_SIDE_EFFECT2        ,  50 , FIGHTING , 229 , 20
    db COUNTER      , NO_ADDITIONAL_EFFECT       ,   1 , FIGHTING , 255 , 20
    db SEISMIC_TOSS , SPECIAL_DAMAGE_EFFECT      ,   1 , FIGHTING , 255 , 20
    db STRIKE       , NO_ADDITIONAL_EFFECT       ,  80 , NORMAL   , 255 , 15
    db ABSORB       , DRAIN_HP_EFFECT            ,  20 , GRASS    , 255 , 20
    db MEGA_DRAIN   , DRAIN_HP_EFFECT            ,  40 , GRASS    , 255 , 10
    db LEECH_SEED   , LEECH_SEED_EFFECT          ,   0 , GRASS    , 229 , 10
    db GROWTH       , SPECIAL_UP1_EFFECT         ,   0 , NORMAL   , 255 , 40
    db RAZOR_LEAF   , NO_ADDITIONAL_EFFECT       ,  55 , GRASS    , 242 , 25
    db SOLARBEAM    , CHARGE_EFFECT              , 120 , GRASS    , 255 , 10
    db POISONPOWDER , POISON_EFFECT              ,   0 , POISON   , 191 , 35
    db STUN_SPORE   , PARALYZE_EFFECT            ,   0 , GRASS    , 191 , 30
    db SLEEP_POWDER , SLEEP_EFFECT               ,   0 , GRASS    , 191 , 15
    db PETAL_DANCE  , THRASH_PETAL_DANCE_EFFECT  ,  70 , GRASS    , 255 , 20
    db STRING_SHOT  , SPEED_DOWN1_EFFECT         ,   0 , BUG      , 242 , 40
    db DRAGON_RAGE  , SPECIAL_DAMAGE_EFFECT      ,   1 , DRAGON   , 255 , 10
    db FIRE_SPIN    , TRAPPING_EFFECT            ,  15 , FIRE     , 178 , 15
    db THUNDERSHOCK , PARALYZE_SIDE_EFFECT1      ,  40 , ELECTRIC , 255 , 30
    db THUNDERBOLT  , PARALYZE_SIDE_EFFECT1      ,  95 , ELECTRIC , 255 , 15
    db THUNDER_WAVE , PARALYZE_EFFECT            ,   0 , ELECTRIC , 255 , 20
    db THUNDER      , PARALYZE_SIDE_EFFECT1      , 120 , ELECTRIC , 178 , 10
    db ROCK_THROW   , NO_ADDITIONAL_EFFECT       ,  50 , ROCK     , 165 , 15
    db EARTHQUAKE   , NO_ADDITIONAL_EFFECT       , 100 , GROUND   , 255 , 10
    db FISSURE      , OHKO_EFFECT                ,   1 , GROUND   ,  76 ,  5
    db TRAPHOLE     , CHARGE_EFFECT              , 100 , GROUND   , 255 , 10
    db TOXIC        , POISON_EFFECT              ,   0 , POISON   , 216 , 10
    db CONFUSION    , CONFUSION_SIDE_EFFECT      ,  50 , PSYCHIC  , 255 , 25
    db PSYCHIC_M    , SPECIAL_DOWN_SIDE_EFFECT   ,  90 , PSYCHIC  , 255 , 10
    db HYPNOSIS     , SLEEP_EFFECT               ,   0 , PSYCHIC  , 153 , 20
    db MEDITATE     , ATTACK_UP1_EFFECT          ,   0 , PSYCHIC  , 255 , 40
    db AGILITY      , SPEED_UP2_EFFECT           ,   0 , PSYCHIC  , 255 , 30
    db QUICK_ATTACK , NO_ADDITIONAL_EFFECT       ,  40 , NORMAL   , 255 , 30
    db RAGE         , RAGE_EFFECT                ,  20 , NORMAL   , 255 , 20
    db TELEPORT     , SWITCH_AND_TELEPORT_EFFECT ,   0 , PSYCHIC  , 255 , 20
    db NIGHT_SHADE  , SPECIAL_DAMAGE_EFFECT      ,   0 , GHOST    , 255 , 15
    db MIMIC        , MIMIC_EFFECT               ,   0 , NORMAL   , 255 , 10
    db SCREECH      , DEFENSE_DOWN2_EFFECT       ,   0 , NORMAL   , 216 , 40
    db DOUBLE_TEAM  , EVASION_UP1_EFFECT         ,   0 , NORMAL   , 255 , 15
    db RECOVER      , HEAL_EFFECT                ,   0 , NORMAL   , 255 , 20
    db HARDEN       , DEFENSE_UP1_EFFECT         ,   0 , NORMAL   , 255 , 30
    db MINIMIZE     , EVASION_UP1_EFFECT         ,   0 , NORMAL   , 255 , 20
    db SMOKESCREEN  , ACCURACY_DOWN1_EFFECT      ,   0 , NORMAL   , 255 , 20
    db CONFUSE_RAY  , CONFUSION_EFFECT           ,   0 , GHOST    , 255 , 10
    db WITHDRAW     , DEFENSE_UP1_EFFECT         ,   0 , WATER    , 255 , 40
    db DEFENSE_CURL , DEFENSE_UP1_EFFECT         ,   0 , NORMAL   , 255 , 40
    db BARRIER      , DEFENSE_UP2_EFFECT         ,   0 , PSYCHIC  , 255 , 30
    db LIGHT_SCREEN , LIGHT_SCREEN_EFFECT        ,   0 , PSYCHIC  , 255 , 30
    db HAZE         , HAZE_EFFECT                ,   0 , ICE      , 255 , 30
    db REFLECT      , REFLECT_EFFECT             ,   0 , PSYCHIC  , 255 , 20
    db FOCUS_ENERGY , FOCUS_ENERGY_EFFECT        ,   0 , NORMAL   , 255 , 30
    db BIDE         , BIDE_EFFECT                ,   0 , NORMAL   , 255 , 10
    db METRONOME    , METRONOME_EFFECT           ,   0 , NORMAL   , 255 , 10
    db MIRROR_MOVE  , MIRROR_MOVE_EFFECT         ,   0 , FLYING   , 255 , 20
    db SELFDESTRUCT , EXPLODE_EFFECT             , 130 , NORMAL   , 255 ,  5
    db EGG_BOMB     , NO_ADDITIONAL_EFFECT       , 100 , NORMAL   , 191 , 10
    db LICK         , PARALYZE_SIDE_EFFECT2      ,  20 , GHOST    , 255 , 30
    db SMOG         , POISON_SIDE_EFFECT2        ,  20 , POISON   , 178 , 20
    db SLUDGE       , POISON_SIDE_EFFECT2        ,  65 , POISON   , 255 , 20
    db BONE_CLUB    , FLINCH_SIDE_EFFECT1        ,  65 , GROUND   , 216 , 20
    db FIRE_BLAST   , BURN_SIDE_EFFECT2          , 120 , FIRE     , 216 ,  5
    db WATERFALL    , NO_ADDITIONAL_EFFECT       ,  80 , WATER    , 255 , 15
    db CLAMP        , TRAPPING_EFFECT            ,  35 , WATER    , 191 , 10
    db SWIFT        , SWIFT_EFFECT               ,  60 , NORMAL   , 255 , 20
    db SKULL_BASH   , CHARGE_EFFECT              , 100 , NORMAL   , 255 , 15
    db SPIKE_CANNON , TWO_TO_FIVE_ATTACKS_EFFECT ,  20 , NORMAL   , 255 , 15
    db CONSTRICT    , SPEED_DOWN_SIDE_EFFECT     ,  10 , NORMAL   , 255 , 35
    db AMNESIA      , SPECIAL_UP2_EFFECT         ,   0 , PSYCHIC  , 255 , 20
    db KINESIS      , ACCURACY_DOWN1_EFFECT      ,   0 , PSYCHIC  , 204 , 15
    db SOFTBOILED   , HEAL_EFFECT                ,   0 , NORMAL   , 255 , 10
    db HI_JUMP_KICK , JUMP_KICK_EFFECT           ,  85 , FIGHTING , 229 , 20
    db GLARE        , PARALYZE_EFFECT            ,   0 , NORMAL   , 191 , 30
    db DREAM_EATER  , DREAM_EATER_EFFECT         , 100 , PSYCHIC  , 255 , 15
    db POISON_GAS   , POISON_EFFECT              ,   0 , POISON   , 140 , 40
    db BARRAGE      , TWO_TO_FIVE_ATTACKS_EFFECT ,  15 , NORMAL   , 216 , 20
    db LEECH_LIFE   , DRAIN_HP_EFFECT            ,  20 , BUG      , 255 , 15
    db LOVELY_KISS  , SLEEP_EFFECT               ,   0 , NORMAL   , 191 , 10
    db SKY_ATTACK   , CHARGE_EFFECT              , 140 , FLYING   , 229 ,  5
    db TRANSFORM    , TRANSFORM_EFFECT           ,   0 , NORMAL   , 255 , 10
    db BUBBLE       , SPEED_DOWN_SIDE_EFFECT     ,  20 , WATER    , 255 , 30
    db DIZZY_PUNCH  , NO_ADDITIONAL_EFFECT       ,  70 , NORMAL   , 255 , 10
    db SPORE        , SLEEP_EFFECT               ,   0 , GRASS    , 255 , 15
    db FLASH        , ACCURACY_DOWN1_EFFECT      ,   0 , NORMAL   , 178 , 20
    db PSYWAVE      , SPECIAL_DAMAGE_EFFECT      ,   1 , PSYCHIC  , 204 , 15
    db SPLASH       , SPLASH_EFFECT              ,   0 , NORMAL   , 255 , 40
    db ACID_ARMOR   , DEFENSE_UP2_EFFECT         ,   0 , POISON   , 255 , 40
    db CRABHAMMER   , NO_ADDITIONAL_EFFECT       ,  90 , WATER    , 216 , 10
    db EXPLOSION    , EXPLODE_EFFECT             , 170 , NORMAL   , 255 ,  5
    db FURY_SWIPES  , TWO_TO_FIVE_ATTACKS_EFFECT ,  18 , NORMAL   , 204 , 15
    db BONEMERANG   , ATTACK_TWICE_EFFECT        ,  50 , GROUND   , 229 , 10
    db REST         , HEAL_EFFECT                ,   0 , PSYCHIC  , 255 , 10
    db ROCK_SLIDE   , NO_ADDITIONAL_EFFECT       ,  75 , ROCK     , 229 , 10
    db HYPER_FANG   , FLINCH_SIDE_EFFECT1        ,  80 , NORMAL   , 229 , 15
    db SHARPEN      , ATTACK_UP1_EFFECT          ,   0 , NORMAL   , 255 , 30
    db CONVERSION   , CONVERSION_EFFECT          ,   0 , NORMAL   , 255 , 30
    db TRI_ATTACK   , NO_ADDITIONAL_EFFECT       ,  80 , NORMAL   , 255 , 10
    db SUPER_FANG   , SUPER_FANG_EFFECT          ,   1 , NORMAL   , 229 , 10
    db SLASH        , NO_ADDITIONAL_EFFECT       ,  70 , NORMAL   , 255 , 20
    db SUBSTITUTE   , SUBSTITUTE_EFFECT          ,   0 , NORMAL   , 255 , 10
    db STRUGGLE     , RECOIL_EFFECT              ,  50 , NORMAL   , 255 , 10