; ──────────────────────────────────────────────────────────────────────
MissingNoExclusiveMove:
    db 0
; ──────────────────────────────────────────────────────────────────────
BulbasaurExclusiveMove:
IvysaurExclusiveMove:
VenusaurExclusiveMove:
    db SWORDS_DANCE
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db SOLARBEAM
    db MIMIC
    db REFLECT
    db BIDE
    db REST
    db SUBSTITUTE
    db BLADE
    db STUN_SPORE
    db SLEEP_POWDER
    db SLUDGE
    db BIND
    db RAZOR_WIND
    db EARTHQUAKE
    db FISSURE
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
CharmanderExclusiveMove:
CharmeleonExclusiveMove:
CharizardExclusiveMove:
    db MEGA_PUNCH
    db SWORDS_DANCE
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db DRAGON_RAGE
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SWIFT
    db SKULL_BASH
    db SKY_ATTACK
    db REST
    db SUBSTITUTE
    db BLADE
    db SWOOP
    db STRIKE
    db FIRE_PUNCH
    db SLASH
    db AGILITY
    db FLAMETHROWER
    db SLAM
    db FIRE_SPIN
    db SOLARBEAM
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
SquirtleExclusiveMove:
WartortleExclusiveMove:
BlastoiseExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db REFLECT
    db BIDE
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db TSUNAMI
    db STRIKE
    db HAZE
    db HYDRO_PUMP
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
CaterpieExclusiveMove:
MetapodExclusiveMove:
ButterfreeExclusiveMove:
    db RAZOR_WIND
    db WHIRLWIND
    db TOXIC
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db SOLARBEAM
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SWIFT
    db FLASH
    db REST
    db PSYWAVE
    db SUBSTITUTE
    db LEECH_LIFE
    db CONFUSION
    db SELFDESTRUCT
    db EXPLOSION
    db DREAM_EATER
    db 0
; ──────────────────────────────────────────────────────────────────────
WeedleExclusiveMove:
KakunaExclusiveMove:
BeedrillExclusiveMove:
    db RAZOR_WIND
    db SWORDS_DANCE
    db TOXIC
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SWIFT
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db BLADE
    db LEECH_LIFE
    db TWINEEDLE
    db SELFDESTRUCT
    db EXPLOSION
    db SOLARBEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
PidgeyExclusiveMove:
PidgeottoExclusiveMove:
PidgeotExclusiveMove:
    db RAZOR_WIND
    db WHIRLWIND
    db TOXIC
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SWIFT
    db SKY_ATTACK
    db REST
    db SUBSTITUTE
    db BLADE
    db SWOOP
    db AGILITY
    db MIRROR_MOVE
    db 0
; ──────────────────────────────────────────────────────────────────────
RattataExclusiveMove:
RaticateExclusiveMove:
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db EARTHQUAKE
    db TRAPHOLE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db SWIFT
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db FOCUS_ENERGY
    db SLASH
    db SUPER_FANG
    db SWORDS_DANCE
    db COUNTER
    db THUNDER_WAVE
    db 0
; ──────────────────────────────────────────────────────────────────────
SpearowExclusiveMove:
FearowExclusiveMove:
    db RAZOR_WIND
    db WHIRLWIND
    db TOXIC
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db SWIFT
    db SKY_ATTACK
    db REST
    db SUBSTITUTE
    db BLADE
    db SWOOP
    db MIRROR_MOVE
    db AGILITY
    db QUICK_ATTACK
    db TRI_ATTACK
    db 0
; ──────────────────────────────────────────────────────────────────────
EkansExclusiveMove:
ArbokExclusiveMove:
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db SKULL_BASH
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db STRIKE
    db SCREECH
    db ABSORB
    db 0
; ──────────────────────────────────────────────────────────────────────
PikachuExclusiveMove:
RaichuExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db PAY_DAY
    db SUBMISSION
    db SEISMIC_TOSS
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SWIFT
    db SKULL_BASH
    db FLASH
    db REST
    db THUNDER_WAVE
    db SUBSTITUTE
    db TAIL_WHIP
    db QUICK_ATTACK
    db SLAM
    db AGILITY
    db TRAPHOLE
    db 0
; ──────────────────────────────────────────────────────────────────────
SandshrewExclusiveMove:
SandslashExclusiveMove:
    db SWORDS_DANCE
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db SUBMISSION
    db SEISMIC_TOSS
    db RAGE
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db BIDE
    db SWIFT
    db SKULL_BASH
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db BLADE
    db STRIKE
    db COUNTER
    db 0
; ──────────────────────────────────────────────────────────────────────
NidoranFExclusiveMove:
NidorinaExclusiveMove:
NidoqueenExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db HORN_DRILL
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db PAY_DAY
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SKULL_BASH
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db BLADE
    db TSUNAMI
    db STRIKE
    db SLASH
    db DOUBLE_TEAM
    db BITE
    db FOCUS_ENERGY
    db 0
; ──────────────────────────────────────────────────────────────────────
NidoranMExclusiveMove:
NidorinoExclusiveMove:
NidokingExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db HORN_DRILL
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db PAY_DAY
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SKULL_BASH
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db BLADE
    db TSUNAMI
    db STRIKE
    db HYPER_FANG
    db DOUBLE_TEAM
    db SLAM
    db FOCUS_ENERGY
    db 0
; ──────────────────────────────────────────────────────────────────────
ClefairyExclusiveMove:
ClefableExclusiveMove:
JigglypuffExclusiveMove:
WigglytuffExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db SOLARBEAM
    db THUNDERBOLT
    db THUNDER
    db PSYCHIC_M
    db MIMIC
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SWIFT
    db SKULL_BASH
    db FLASH
    db REST
    db THUNDER_WAVE
    db PSYWAVE
    db TRI_ATTACK
    db SUBSTITUTE
    db STRIKE
    db DEFENSE_CURL
    db DISABLE
    db SING
    db MINIMIZE
    db DREAM_EATER
    db TRAPHOLE
    db METRONOME
    db 0
; ──────────────────────────────────────────────────────────────────────
VulpixExclusiveMove:
NinetalesExclusiveMove:
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db TRAPHOLE
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SWIFT
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db EMBER
    db QUICK_ATTACK
    db FLAMETHROWER
    db SLAM
    db FIRE_SPIN
    db DREAM_EATER
    db SOLARBEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
ZubatExclusiveMove:
GolbatExclusiveMove:
    db RAZOR_WIND
    db WHIRLWIND
    db TOXIC
    db TAKE_DOWN
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db SWIFT
    db SKY_ATTACK
    db REST
    db SUBSTITUTE
    db BLADE
    db SWOOP
    db ABSORB
    db CONFUSE_RAY
    db HAZE
    db 0
; ──────────────────────────────────────────────────────────────────────
OddishExclusiveMove:
GloomExclusiveMove:
VileplumeExclusiveMove:
    db SWORDS_DANCE
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db SOLARBEAM
    db MIMIC
    db REFLECT
    db BIDE
    db REST
    db SUBSTITUTE
    db BLADE
    db RAZOR_LEAF
    db SLUDGE
    db SLAM
    db 0
; ──────────────────────────────────────────────────────────────────────
ParasExclusiveMove:
ParasectExclusiveMove:
    db SWORDS_DANCE
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db SOLARBEAM
    db TRAPHOLE
    db MIMIC
    db REFLECT
    db BIDE
    db REST
    db SUBSTITUTE
    db BLADE
    db COUNTER
    db 0
; ──────────────────────────────────────────────────────────────────────
VenonatExclusiveMove:
VenomothExclusiveMove:
    db RAZOR_WIND
    db WHIRLWIND
    db TOXIC
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db SOLARBEAM
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SWIFT
    db FLASH
    db REST
    db PSYWAVE
    db SUBSTITUTE
    db DREAM_EATER
    db 0
; ──────────────────────────────────────────────────────────────────────
DiglettExclusiveMove:
DugtrioExclusiveMove:
    db SWORDS_DANCE
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db REST
    db ROCK_SLIDE
    db TRI_ATTACK
    db SUBSTITUTE
    db BLADE
    db 0
; ──────────────────────────────────────────────────────────────────────
MeowthExclusiveMove:
PersianExclusiveMove:
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db HYPER_BEAM
    db PAY_DAY
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db SWIFT
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db BLADE
    db DREAM_EATER
    db TRAPHOLE
    db THUNDER_WAVE
    db 0
; ──────────────────────────────────────────────────────────────────────
PsyduckExclusiveMove:
GolduckExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db PAY_DAY
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db TRAPHOLE
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db SWIFT
    db SKULL_BASH
    db REST
    db PSYWAVE
    db SUBSTITUTE
    db BLADE
    db TSUNAMI
    db STRIKE
    db AMNESIA
    db TRI_ATTACK
    db 0
; ──────────────────────────────────────────────────────────────────────
MankeyExclusiveMove:
PrimeapeExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db PAY_DAY
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db EARTHQUAKE
    db TRAPHOLE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db METRONOME
    db SWIFT
    db SKULL_BASH
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db BLADE
    db STRIKE
    db THRASH
    db SCREECH
    db THUNDER_WAVE
    db 0
; ──────────────────────────────────────────────────────────────────────
GrowlitheExclusiveMove:
ArcanineExclusiveMove:
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db DRAGON_RAGE
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SWIFT
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db EMBER
    db LEER
    db AGILITY
    db FLAMETHROWER
    db SLAM
    db SOLARBEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
PoliwagExclusiveMove:
PoliwhirlExclusiveMove:
PoliwrathExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db EARTHQUAKE
    db FISSURE
    db PSYCHIC_M
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db METRONOME
    db SKULL_BASH
    db REST
    db PSYWAVE
    db SUBSTITUTE
    db TSUNAMI
    db STRIKE
    db HAZE
    db AMNESIA
    db HYDRO_PUMP
    db DOUBLE_TEAM
    db TRAPHOLE
    db SWIFT
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
AbraExclusiveMove:
KadabraExclusiveMove:
AlakazamExclusiveMove:
    db TOXIC
    db HYPER_BEAM
    db SEISMIC_TOSS
    db RAGE
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db METRONOME
    db SKULL_BASH
    db FLASH
    db REST
    db THUNDER_WAVE
    db PSYWAVE
    db TRI_ATTACK
    db SUBSTITUTE
    db DREAM_EATER
    db SWIFT
    db 0
; ──────────────────────────────────────────────────────────────────────
MachopExclusiveMove:
MachokeExclusiveMove:
MachampExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db METRONOME
    db FIRE_BLAST
    db SKULL_BASH
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db TSUNAMI
    db STRIKE
    db ROCK_THROW
    db 0
; ──────────────────────────────────────────────────────────────────────
BellsproutExclusiveMove:
WeepinbellExclusiveMove:
VictreebelExclusiveMove:
    db SWORDS_DANCE
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db SOLARBEAM
    db MIMIC
    db REFLECT
    db BIDE
    db REST
    db SUBSTITUTE
    db BLADE
    db RAZOR_LEAF
    db SLUDGE
    db SWIFT
    db 0
; ──────────────────────────────────────────────────────────────────────
TentacoolExclusiveMove:
TentacruelExclusiveMove:
    db SWORDS_DANCE
    db TOXIC
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db BLADE
    db TSUNAMI
    db BARRIER
    db SCREECH
    db HYDRO_PUMP
    db SWIFT
    db 0
; ──────────────────────────────────────────────────────────────────────
GeodudeExclusiveMove:
GravelerExclusiveMove:
GolemExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db BIDE
    db METRONOME
    db SELFDESTRUCT
    db FIRE_BLAST
    db REST
    db EXPLOSION
    db ROCK_SLIDE
    db SUBSTITUTE
    db STRIKE
    db HARDEN
    db FIRE_PUNCH
    db 0
; ──────────────────────────────────────────────────────────────────────
PonytaExclusiveMove:
RapidashExclusiveMove:
    db TOXIC
    db HORN_DRILL
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SWIFT
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db SWORDS_DANCE
    db PAY_DAY
    db SOLARBEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
SlowpokeExclusiveMove:
SlowbroExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db PAY_DAY
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db EARTHQUAKE
    db FISSURE
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SWIFT
    db SKULL_BASH
    db FLASH
    db REST
    db THUNDER_WAVE
    db PSYWAVE
    db TRI_ATTACK
    db SUBSTITUTE
    db TSUNAMI
    db STRIKE
    db AMNESIA
    db DREAM_EATER
    db 0
; ──────────────────────────────────────────────────────────────────────
MagnemiteExclusiveMove:
MagnetonExclusiveMove:
    db TOXIC
    db HYPER_BEAM
    db RAGE
    db SOLARBEAM
    db THUNDERBOLT
    db THUNDER
    db MIMIC
    db REFLECT
    db BIDE
    db SWIFT
    db FLASH
    db REST
    db THUNDER_WAVE
    db TRI_ATTACK
    db SUBSTITUTE
    db CONVERSION
    db SCREECH
    db LIGHT_SCREEN
    db SELFDESTRUCT
    db EXPLOSION
    db 0
; ──────────────────────────────────────────────────────────────────────
FarfetchdExclusiveMove:
    db RAZOR_WIND
    db SWORDS_DANCE
    db WHIRLWIND
    db TOXIC
    db HYPER_BEAM
    db RAGE
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SWIFT
    db SKULL_BASH
    db SKY_ATTACK
    db REST
    db SUBSTITUTE
    db BLADE
    db SWOOP
    db 0
; ──────────────────────────────────────────────────────────────────────
DoduoExclusiveMove:
DodrioExclusiveMove:
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SKULL_BASH
    db REST
    db TRI_ATTACK
    db SUBSTITUTE
    db BLADE
    db SWORDS_DANCE
    db SWIFT
    db 0
; ──────────────────────────────────────────────────────────────────────
SeelExclusiveMove:
DewgongExclusiveMove:
    db TOXIC
    db HORN_DRILL
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db PAY_DAY
    db RAGE
    db MIMIC
    db BIDE
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db TSUNAMI
    db STRIKE
    db AMNESIA
    db 0
; ──────────────────────────────────────────────────────────────────────
GrimerExclusiveMove:
MukExclusiveMove:
    db TOXIC
    db BODY_SLAM
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db THUNDERBOLT
    db THUNDER
    db MIMIC
    db BIDE
    db SELFDESTRUCT
    db FIRE_BLAST
    db REST
    db EXPLOSION
    db SUBSTITUTE
    db SWIFT
    db THUNDER_WAVE
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
ShellderExclusiveMove:
CloysterExclusiveMove:
    db TOXIC
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db MIMIC
    db REFLECT
    db BIDE
    db SELFDESTRUCT
    db SWIFT
    db REST
    db EXPLOSION
    db TRI_ATTACK
    db SUBSTITUTE
    db TSUNAMI
    db BUBBLE
    db LICK
    db BODY_SLAM
    db 0
; ──────────────────────────────────────────────────────────────────────
GastlyExclusiveMove:
HaunterExclusiveMove:
GengarExclusiveMove:
    db TOXIC
    db HYPER_BEAM
    db MEGA_DRAIN
    db THUNDERBOLT
    db THUNDER
    db PSYCHIC_M
    db MIMIC
    db DOUBLE_TEAM
    db TELEPORT
    db BIDE
    db METRONOME
    db SELFDESTRUCT
    db DREAM_EATER
    db REST
    db PSYWAVE
    db EXPLOSION
    db SUBSTITUTE
    db SMOG
    db AMNESIA
    db THUNDER_WAVE
    db 0
; ──────────────────────────────────────────────────────────────────────
OnixExclusiveMove:
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db BIDE
    db SELFDESTRUCT
    db SKULL_BASH
    db REST
    db EXPLOSION
    db ROCK_SLIDE
    db SUBSTITUTE
    db STRIKE
    db 0
; ──────────────────────────────────────────────────────────────────────
DrowzeeExclusiveMove:
HypnoExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db DOUBLE_EDGE
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db METRONOME
    db SKULL_BASH
    db FLASH
    db DREAM_EATER
    db REST
    db THUNDER_WAVE
    db PSYWAVE
    db TRI_ATTACK
    db SUBSTITUTE
    db POISON_GAS
    db LIGHT_SCREEN
    db 0
; ──────────────────────────────────────────────────────────────────────
KrabbyExclusiveMove:
KinglerExclusiveMove:
    db SWORDS_DANCE
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db TRAPHOLE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db REST
    db SUBSTITUTE
    db BLADE
    db TSUNAMI
    db STRIKE
    db STOMP
    db HAZE
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
VoltorbExclusiveMove:
ElectrodeExclusiveMove:
    db TOXIC
    db HYPER_BEAM
    db RAGE
    db SOLARBEAM
    db THUNDERBOLT
    db THUNDER
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SELFDESTRUCT
    db SWIFT
    db SKULL_BASH
    db FLASH
    db REST
    db THUNDER_WAVE
    db EXPLOSION
    db SUBSTITUTE
    db CONVERSION
    db 0
; ──────────────────────────────────────────────────────────────────────
ExeggcuteExclusiveMove:
ExeggutorExclusiveMove:
    db TOXIC
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db SOLARBEAM
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db REFLECT
    db BIDE
    db SELFDESTRUCT
    db EGG_BOMB
    db DREAM_EATER
    db REST
    db PSYWAVE
    db EXPLOSION
    db SUBSTITUTE
    db STRIKE
    db LEECH_SEED
    db STUN_SPORE
    db POISONPOWDER
    db SLEEP_POWDER
    db SWORDS_DANCE
    db BODY_SLAM
    db EARTHQUAKE
    db 0
; ──────────────────────────────────────────────────────────────────────
CuboneExclusiveMove:
MarowakExclusiveMove:
    db MEGA_PUNCH
    db SWORDS_DANCE
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db FIRE_BLAST
    db SKULL_BASH
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db STRIKE
    db THRASH
    db SWIFT
    db 0
; ──────────────────────────────────────────────────────────────────────
HitmonleeExclusiveMove:
HitmonchanExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db EARTHQUAKE
    db FISSURE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db METRONOME
    db SWIFT
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db STRIKE
    db SWORDS_DANCE
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
LickitungExclusiveMove:
    db MEGA_PUNCH
    db SWORDS_DANCE
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db EARTHQUAKE
    db FISSURE
    db MIMIC
    db BIDE
    db FIRE_BLAST
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db BLADE
    db TSUNAMI
    db STRIKE
    db DREAM_EATER
    db SOLARBEAM
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
KoffingExclusiveMove:
WeezingExclusiveMove:
    db TOXIC
    db HYPER_BEAM
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db SELFDESTRUCT
    db FIRE_BLAST
    db REST
    db EXPLOSION
    db SUBSTITUTE
    db THUNDER_WAVE
    db PSYWAVE
    db 0
; ──────────────────────────────────────────────────────────────────────
RhyhornExclusiveMove:
RhydonExclusiveMove:
    db MEGA_PUNCH
    db SWORDS_DANCE
    db MEGA_KICK
    db TOXIC
    db HORN_DRILL
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db PAY_DAY
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db BIDE
    db FIRE_BLAST
    db SKULL_BASH
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db TSUNAMI
    db STRIKE
    db DOUBLE_KICK
    db 0
; ──────────────────────────────────────────────────────────────────────
ChanseyExclusiveMove:
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db SOLARBEAM
    db THUNDERBOLT
    db THUNDER
    db PSYCHIC_M
    db MIMIC
    db REFLECT
    db BIDE
    db METRONOME
    db EGG_BOMB
    db FIRE_BLAST
    db SKULL_BASH
    db FLASH
    db REST
    db THUNDER_WAVE
    db PSYWAVE
    db TRI_ATTACK
    db SUBSTITUTE
    db STRIKE
    db DREAM_EATER
    db EARTHQUAKE
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
TangelaExclusiveMove:
    db SWORDS_DANCE
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db HYPER_BEAM
    db RAGE
    db MEGA_DRAIN
    db SOLARBEAM
    db MIMIC
    db BIDE
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db BLADE
    db 0
; ──────────────────────────────────────────────────────────────────────
KangaskhanExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db EARTHQUAKE
    db FISSURE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db FIRE_BLAST
    db SKULL_BASH
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db TSUNAMI
    db STRIKE
    db SOLARBEAM
    db TRAPHOLE
    db 0
; ──────────────────────────────────────────────────────────────────────
HorseaExclusiveMove:
SeadraExclusiveMove:
    db TOXIC
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db DRAGON_RAGE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db SWIFT
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db TSUNAMI
    db HAZE
    db HYDRO_PUMP
    db RAZOR_WIND
    db 0
; ──────────────────────────────────────────────────────────────────────
GoldeenExclusiveMove:
SeakingExclusiveMove:
    db SWORDS_DANCE
    db TOXIC
    db HORN_DRILL
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db SWIFT
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db TSUNAMI
    db 0
; ──────────────────────────────────────────────────────────────────────
StaryuExclusiveMove:
StarmieExclusiveMove:
    db TOXIC
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SWIFT
    db FLASH
    db REST
    db THUNDER_WAVE
    db PSYWAVE
    db TRI_ATTACK
    db SUBSTITUTE
    db TSUNAMI
    db MINIMIZE
    db SUPERSONIC
    db DREAM_EATER
    db 0
; ──────────────────────────────────────────────────────────────────────
MrMimeExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db DOUBLE_EDGE
    db HYPER_BEAM
    db SEISMIC_TOSS
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db METRONOME
    db SKULL_BASH
    db FLASH
    db DREAM_EATER
    db REST
    db THUNDER_WAVE
    db PSYWAVE
    db SUBSTITUTE
    db SOLARBEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
ScytherExclusiveMove:
    db RAZOR_WIND
    db SWORDS_DANCE
    db TOXIC
    db TAKE_DOWN
    db HYPER_BEAM
    db RAGE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db SWIFT
    db SKULL_BASH
    db SKY_ATTACK
    db REST
    db SUBSTITUTE
    db BLADE
    db SWOOP
    db COUNTER
    db 0
; ──────────────────────────────────────────────────────────────────────
JynxExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db METRONOME
    db SKULL_BASH
    db DREAM_EATER
    db REST
    db PSYWAVE
    db SUBSTITUTE
    db 0
; ──────────────────────────────────────────────────────────────────────
ElectabuzzExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db PSYCHIC_M
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db METRONOME
    db SWIFT
    db SKULL_BASH
    db FLASH
    db REST
    db THUNDER_WAVE
    db PSYWAVE
    db SUBSTITUTE
    db STRIKE
    db 0
; ──────────────────────────────────────────────────────────────────────
MagmarExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db PSYCHIC_M
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db METRONOME
    db FIRE_BLAST
    db SKULL_BASH
    db REST
    db PSYWAVE
    db SUBSTITUTE
    db STRIKE
    db 0
; ──────────────────────────────────────────────────────────────────────
PinsirExclusiveMove:
    db SWORDS_DANCE
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db MIMIC
    db DOUBLE_TEAM
    db EARTHQUAKE
    db FISSURE
    db BIDE
    db REST
    db SUBSTITUTE
    db BLADE
    db STRIKE
    db TRAPHOLE
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
TaurosExclusiveMove:
    db TOXIC
    db HORN_DRILL
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db EARTHQUAKE
    db FISSURE
    db MIMIC
    db DOUBLE_TEAM
    db BIDE
    db FIRE_BLAST
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db STRIKE
    db SOLARBEAM
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
MagikarpExclusiveMove:
GyaradosExclusiveMove:
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db DRAGON_RAGE
    db THUNDERBOLT
    db THUNDER
    db MIMIC
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SKULL_BASH
    db REST
    db SUBSTITUTE
    db TSUNAMI
    db STRIKE
    db AMNESIA
    db EARTHQUAKE
    db THUNDER_WAVE
    db 0
; ──────────────────────────────────────────────────────────────────────
LaprasExclusiveMove:
    db TOXIC
    db HORN_DRILL
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db SOLARBEAM
    db DRAGON_RAGE
    db THUNDERBOLT
    db THUNDER
    db PSYCHIC_M
    db MIMIC
    db REFLECT
    db BIDE
    db SKULL_BASH
    db REST
    db PSYWAVE
    db SUBSTITUTE
    db TSUNAMI
    db DREAM_EATER
    db EARTHQUAKE
    db FISSURE
    db THUNDER_WAVE
    db 0
; ──────────────────────────────────────────────────────────────────────
DittoExclusiveMove:
    db MIMIC
    db METRONOME
    db REST
    db SUBSTITUTE
    db 0
; ──────────────────────────────────────────────────────────────────────
EeveeExclusiveMove:
VaporeonExclusiveMove:
JolteonExclusiveMove:
FlareonExclusiveMove:
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SWIFT
    db SKULL_BASH
    db FLASH
    db REST
    db THUNDER_WAVE
    db SUBSTITUTE
    db TSUNAMI
    db GROWL
    db QUICK_ATTACK
    db DOUBLE_KICK
    db PAY_DAY
    db 0
; ──────────────────────────────────────────────────────────────────────
PorygonExclusiveMove:
    db TOXIC
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db SOLARBEAM
    db THUNDERBOLT
    db THUNDER
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db REFLECT
    db BIDE
    db SWIFT
    db SKULL_BASH
    db FLASH
    db DREAM_EATER
    db REST
    db THUNDER_WAVE
    db PSYWAVE
    db TRI_ATTACK
    db SUBSTITUTE
    db 0
; ──────────────────────────────────────────────────────────────────────
OmanyteExclusiveMove:
OmastarExclusiveMove:
    db TOXIC
    db HORN_DRILL
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db REFLECT
    db BIDE
    db SKULL_BASH
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db TSUNAMI
    db 0
; ──────────────────────────────────────────────────────────────────────
KabutoExclusiveMove:
KabutopsExclusiveMove:
    db RAZOR_WIND
    db SWORDS_DANCE
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db SUBMISSION
    db SEISMIC_TOSS
    db RAGE
    db MEGA_DRAIN
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SKULL_BASH
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db BLADE
    db TSUNAMI
    db 0
; ──────────────────────────────────────────────────────────────────────
AerodactylExclusiveMove:
    db RAZOR_WIND
    db WHIRLWIND
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db DRAGON_RAGE
    db EARTHQUAKE
    db FISSURE
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SWIFT
    db SKY_ATTACK
    db REST
    db ROCK_SLIDE
    db SUBSTITUTE
    db BLADE
    db SWOOP
    db STRIKE
    db 0
; ──────────────────────────────────────────────────────────────────────
SnorlaxExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db PAY_DAY
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db SOLARBEAM
    db THUNDERBOLT
    db THUNDER
    db EARTHQUAKE
    db FISSURE
    db PSYCHIC_M
    db MIMIC
    db REFLECT
    db BIDE
    db METRONOME
    db SELFDESTRUCT
    db FIRE_BLAST
    db SKULL_BASH
    db REST
    db PSYWAVE
    db ROCK_SLIDE
    db SUBSTITUTE
    db TSUNAMI
    db STRIKE
    db 0
; ──────────────────────────────────────────────────────────────────────
ArticunoExclusiveMove:
    db RAZOR_WIND
    db WHIRLWIND
    db TOXIC
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SWIFT
    db SKY_ATTACK
    db REST
    db SUBSTITUTE
    db SWOOP
    db TSUNAMI
    db 0
; ──────────────────────────────────────────────────────────────────────
ZapdosExclusiveMove:
    db RAZOR_WIND
    db WHIRLWIND
    db TOXIC
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db THUNDERBOLT
    db THUNDER
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db SWIFT
    db FLASH
    db SKY_ATTACK
    db REST
    db THUNDER_WAVE
    db SUBSTITUTE
    db SWOOP
    db 0
; ──────────────────────────────────────────────────────────────────────
MoltresExclusiveMove:
    db RAZOR_WIND
    db WHIRLWIND
    db TOXIC
    db TAKE_DOWN
    db DOUBLE_EDGE
    db HYPER_BEAM
    db RAGE
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SWIFT
    db SKY_ATTACK
    db REST
    db SUBSTITUTE
    db SWOOP
    db SOLARBEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
DratiniExclusiveMove:
DragonairExclusiveMove:
DragoniteExclusiveMove:
    db RAZOR_WIND
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db RAGE
    db DRAGON_RAGE
    db THUNDERBOLT
    db THUNDER
    db MIMIC
    db DOUBLE_TEAM
    db EARTHQUAKE
    db FISSURE
    db TRAPHOLE
    db REFLECT
    db BIDE
    db FIRE_BLAST
    db SWIFT
    db SKULL_BASH
    db SKY_ATTACK
    db REST
    db THUNDER_WAVE
    db SUBSTITUTE
    db BLADE
    db SWOOP
    db TSUNAMI
    db STRIKE
    db MEGA_PUNCH
    db MEGA_KICK
    db HORN_DRILL
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
MewtwoExclusiveMove:
    db MEGA_PUNCH
    db MEGA_KICK
    db TOXIC
    db BODY_SLAM
    db TAKE_DOWN
    db DOUBLE_EDGE
    db BUBBLEBEAM
    db WATER_GUN
    db ICE_BEAM
    db BLIZZARD
    db HYPER_BEAM
    db PAY_DAY
    db SUBMISSION
    db COUNTER
    db SEISMIC_TOSS
    db RAGE
    db SOLARBEAM
    db THUNDERBOLT
    db THUNDER
    db PSYCHIC_M
    db TELEPORT
    db MIMIC
    db DOUBLE_TEAM
    db REFLECT
    db BIDE
    db METRONOME
    db SELFDESTRUCT
    db FIRE_BLAST
    db SWIFT
    db SKULL_BASH
    db FLASH
    db REST
    db THUNDER_WAVE
    db PSYWAVE
    db TRI_ATTACK
    db SUBSTITUTE
    db STRIKE
    db DREAM_EATER
    db EARTHQUAKE
    db ROCK_SLIDE
    db 0
; ──────────────────────────────────────────────────────────────────────
MewExclusiveMove:
    db 0
; ──────────────────────────────────────────────────────────────────────