; ──────────────────────────────────────────────────────────────────────
MissingNo_Learnset:
    db  1,WATER_GUN
    db  1,WATER_GUN
    db  1,SKY_ATTACK
    db 0
; ──────────────────────────────────────────────────────────────────────
BULBASAUR_Learnset:
    db  1,TACKLE
    db  1,GROWL
    db  8,LEECH_SEED
    db 10,CONSTRICT
    db 13,VINE_WHIP
    ;  16,IVYSAUR
    db 0
IVYSAUR_Learnset:
    db 16,POISONPOWDER
    db 17,POISON_STING
    db 19,DOUBLE_KICK
    db 20,LEECH_LIFE
    db 21,SMOG
    db 23,RAZOR_LEAF
    db 23,Skill__CUT
    db 25,SLAM
    db 27,ACID
    db 28,STRING_SHOT
    db 29,STUN_SPORE
    db 31,POISON_GAS
    ;  32,VENUSAUR
    db 0
VENUSAUR_Learnset:
    db 32,ABSORB
    db 32,PETAL_DANCE
    db 36,STOMP
    db 36,Skill__STRENGTH
    db 37,BARRAGE
    db 38,GROWTH
    db 39,HAZE
    db 39,Skill__HEAL
    db 40,SLEEP_POWDER
    db 42,BODY_SLAM
    db 44,SLUDGE
    db 47,BIND
    db 52,SOLARBEAM
    db 54,SWORDS_DANCE
    db 56,EARTHQUAKE
    db 58,TOXIC
    db 60,SPORE
    db 0
BULBASAUR_NoEvo_Learnset:
    db 17,LEECH_LIFE ; Exclusive
    db 22,DOUBLE_KICK
    db 25,RAZOR_LEAF
    db 25,Skill__CUT
    db 29,SLAM
    db 31,BARRAGE ; Exclusive
    db 35,STUN_SPORE
    db 39,BIND ; Exclusive
    db 42,ABSORB
    db 44,GROWTH
    db 49,SLEEP_POWDER
    db 52,HAZE
    db 52,Skill__HEAL
    db 54,SOLARBEAM
    db 0
IVYSAUR_NoEvo_Learnset:
    db 33,BARRAGE ; Exclusive
    db 34,BIND ; Exclusive
    db 38,ABSORB
    db 42,GROWTH
    db 44,HAZE
    db 44,Skill__HEAL
    db 46,SLEEP_POWDER
    db 49,SLUDGE
    db 54,SOLARBEAM
    db 59,EARTHQUAKE
    db 0
; ──────────────────────────────────────────────────────────────────────
CHARMANDER_Learnset:
    db  1,SCRATCH
    db  1,GROWL
    db  8,EMBER
    db  9,Skill__LIGHT
    db 10,LEER
    db 13,FURY_SWIPES
    ;  16,CHARMELEON
    db 0
CHARMELEON_Learnset:
    db 16,FOCUS_ENERGY
    db 18,RAGE
    db 19,SMOKESCREEN
    db 22,FIRE_PUNCH
    db 23,QUICK_ATTACK
    db 24,POISON_GAS
    db 25,Skill__DIG
    db 26,TRAPHOLE
    db 28,MEGA_PUNCH
    db 30,SMOG
    db 32,SLASH
    db 32,Skill__CUT
    db 34,FLAMETHROWER
    ;  36,CHARIZARD
    db 0
CHARIZARD_Learnset:
    db 36,Skill__FLY
    db 36,WING_ATTACK
    db 36,SWOOP
    db 39,DRAGON_RAGE
    db 40,AGILITY
    db 41,SEISMIC_TOSS
    db 41,Skill__STRENGTH
    db 42,HYPER_FANG
    db 44,FIRE_SPIN
    db 46,SLAM
    db 48,BODY_SLAM
    db 51,LIGHT_SCREEN
    db 53,FIRE_BLAST
    db 55,SKY_ATTACK
    db 57,SWORDS_DANCE
    db 59,EARTHQUAKE
    db 60,SUPER_FANG
    db 0
CHARMANDER_NoEvo_Learnset:
    db 17,QUICK_ATTACK ; Exclusive
    db 21,FOCUS_ENERGY
    db 24,SMOKESCREEN
    db 26,FIRE_PUNCH
    db 30,AGILITY ; Exclusive
    db 30,Skill__DIG
    db 35,SLASH
    db 38,Skill__CUT
    db 40,FLAMETHROWER
    db 43,POISON_GAS
    db 45,SLAM ; Exclusive
    db 50,FIRE_SPIN
    db 53,HYPER_FANG
    db 55,FIRE_BLAST
    db 0
CHARMELEON_NoEvo_Learnset:
    db 37,AGILITY ; Exclusive
    db 38,SLAM ; Exclusive
    db 41,DRAGON_RAGE
    db 44,SEISMIC_TOSS
    db 44,Skill__STRENGTH
    db 46,FIRE_SPIN
    db 48,HYPER_FANG
    db 51,LIGHT_SCREEN
    db 55,FIRE_BLAST
    db 60,SWORDS_DANCE
    db 0
; ──────────────────────────────────────────────────────────────────────
SQUIRTLE_Learnset:
    db  1,TACKLE
    db  1,TAIL_WHIP
    db  8,BUBBLE
    db 10,PECK
    db 13,DOUBLESLAP
    db 15,Skill__FLOAT
    ;  16,WARTORTLE
    db 0
WARTORTLE_Learnset:
    db 16,WATER_GUN
    db 18,WITHDRAW
    db 19,SAND_ATTACK
    db 21,BITE
    db 22,SONICBOOM
    db 23,WATERFALL
    db 25,SCREECH
    db 26,Skill__DIG
    db 28,TRAPHOLE
    db 31,BUBBLEBEAM
    db 33,HAZE
    db 35,ROCK_THROW
    ;  36,BLASTOISE
    db 0
BLASTOISE_Learnset:
    db 36,Skill__STRENGTH
    db 36,SPIKE_CANNON
    db 36,TSUNAMI
    db 38,MIST
    db 39,SUPERSONIC
    db 40,STOMP
    db 41,REST
    db 42,SKULL_BASH
    db 45,HEADBUTT
    db 46,BODY_SLAM
    db 49,DIZZY_PUNCH
    db 51,HYDRO_PUMP
    db 54,ICE_PUNCH
    db 56,HAMMER
    db 58,EARTHQUAKE
    db 60,SUBSTITUTE
    db 0
SQUIRTLE_NoEvo_Learnset:
    db 17,SONICBOOM ; Exclusive
    db 20,WATER_GUN
    db 22,WITHDRAW
    db 24,BITE
    db 29,SUPERSONIC ; Exclusive
    db 31,Skill__DIG
    db 34,TRAPHOLE
    db 39,BUBBLEBEAM
    db 41,WATERFALL
    db 44,HEADBUTT ; Exclusive
    db 49,SKULL_BASH
    db 52,REST
    db 54,HYDRO_PUMP
    db 0
WARTORTLE_NoEvo_Learnset:
    db 37,SUPERSONIC ; Exclusive
    db 38,HEADBUTT ; Exclusive
    db 42,TSUNAMI
    db 44,Skill__STRENGTH
    db 46,MIST
    db 48,REST
    db 50,SKULL_BASH
    db 52,BODY_SLAM
    db 54,HYDRO_PUMP
    db 58,ICE_PUNCH
    db 0
; ──────────────────────────────────────────────────────────────────────
CATERPIE_Learnset:
    db  1,TACKLE
    db  1,STRING_SHOT
    ;   7,METAPOD
    db 0
METAPOD_Learnset:
    db  7,HARDEN
    ;  10,BUTTERFREE
    db 0
BUTTERFREE_Learnset:
    db 10,CONFUSION
    db 11,TELEPORT
    db 12,DISABLE
    db 13,POISONPOWDER
    db 14,STUN_SPORE
    db 15,SLEEP_POWDER
    db 16,Skill__HEAL
    db 17,PSYWAVE
    db 18,GUST
    db 19,ABSORB
    db 20,SONICBOOM
    db 22,KINESIS
    db 23,SUPERSONIC
    db 24,LEECH_LIFE
    db 26,SCREECH
    db 27,WHIRLWIND
    db 31,PSYBEAM
    db 32,Skill__FLY
    db 33,PIN_MISSILE
    db 36,RAZOR_WIND
    db 38,AGILITY
    db 41,SPORE
    db 43,REFLECT
    db 45,MEGA_DRAIN
    db 48,PSYCHIC_M
    db 49,Skill__LIGHT
    db 51,SWOOP
    db 55,BARRIER
    db 60,SKY_ATTACK
    db 0
CATERPIE_NoEvo_Learnset:
    db 10,LEECH_LIFE ; Exclusive
    db 15,DISABLE
    db 20,CONFUSION ; Exclusive
    db 25,SUPERSONIC
    db 30,SCREECH
    db 0
METAPOD_NoEvo_Learnset:
    db 18,SELFDESTRUCT ; Exclusive*
    db 36,EXPLOSION ; Exclusive*
    db 54,BIDE ; Exclusive
    db 0
; ──────────────────────────────────────────────────────────────────────
WEEDLE_Learnset:
    db  1,POISON_STING
    db  1,STRING_SHOT
    ;   7,KAKUNA
    db 0
KAKUNA_Learnset:
    db  7,HARDEN
    ;  10,BEEDRILL
    db 0
BEEDRILL_Learnset:
    db 10,TWINEEDLE
    db 11,LEER
    db 12,RAGE
    db 13,BLADE
    db 13,Skill__CUT
    db 14,FOCUS_ENERGY
    db 15,FURY_ATTACK
    db 18,POISONPOWDER
    db 21,LEECH_LIFE
    db 22,SCREECH
    db 23,SONICBOOM
    db 23,QUICK_ATTACK
    db 24,ACID
    db 26,GUST
    db 27,DOUBLE_TEAM
    db 30,PIN_MISSILE
    db 31,Skill__FLY
    db 32,WHIRLWIND
    db 34,AGILITY
    db 37,SLAM
    db 39,RAZOR_WIND
    db 41,SLUDGE
    db 43,SPIKE_CANNON
    db 45,SWOOP
    db 48,SUPERSONIC
    db 51,TOXIC
    db 55,SWORDS_DANCE
    db 60,SKY_ATTACK
    db 0
WEEDLE_NoEvo_Learnset:
    db 10,LEECH_LIFE ; Exclusive
    db 15,LEER
    db 20,TWINEEDLE ; Exclusive
    db 25,SCREECH
    db 30,DOUBLE_TEAM
    db 0
KAKUNA_NoEvo_Learnset:
    db 18,SELFDESTRUCT ; Exclusive*
    db 36,EXPLOSION ; Exclusive*
    db 54,BIDE ; Exclusive
    db 0
; ──────────────────────────────────────────────────────────────────────
PIDGEY_Learnset:
    db  1,GUST
    db  1,GROWL
    db  5,TACKLE
    db  7,SAND_ATTACK
    db 10,QUICK_ATTACK
    db 13,PECK
    db 16,LEER
    ;  18,PIDGEOTTO
    db 0
PIDGEOTTO_Learnset:
    db 18,Skill__FLY
    db 18,WING_ATTACK
    db 21,WHIRLWIND
    db 24,SWOOP
    db 28,RAZOR_WIND
    db 30,Skill__CUT
    db 33,FURY_ATTACK
    ;  36,PIDGEOT
    db 0
PIDGEOT_Learnset:
    db 36,DOUBLE_TEAM
    db 40,AGILITY
    db 43,DRILL_PECK
    db 46,MIRROR_MOVE
    db 49,DOUBLE_EDGE
    db 52,MIMIC
    db 56,EGG_BOMB
    db 60,SKY_ATTACK
    db 0
PIDGEY_NoEvo_Learnset:
    db 22,WING_ATTACK
    db 25,WHIRLWIND
    db 28,SWOOP
    db 32,RAZOR_WIND
    db 35,FURY_ATTACK
    db 38,Skill__FLY
    db 40,DOUBLE_TEAM
    db 45,AGILITY
    db 50,MIRROR_MOVE
    db 55,MIMIC
    db 0
PIDGEOTTO_NoEvo_Learnset:
    db 38,DOUBLE_TEAM
    db 41,AGILITY
    db 45,DRILL_PECK
    db 48,MIRROR_MOVE
    db 50,DOUBLE_EDGE
    db 53,MIMIC
    db 57,EGG_BOMB
    db 60,SKY_ATTACK
    db 0
; ──────────────────────────────────────────────────────────────────────
RATTATA_Learnset:
    db  1,TACKLE
    db  1,TAIL_WHIP
    db  4,SCRATCH
    db  8,FURY_SWIPES
    db 10,QUICK_ATTACK
    db 13,BITE
    db 14,Skill__DIG
    db 15,HYPER_FANG
    db 17,DEFENSE_CURL
    ;  20,RATICATE
    db 0
RATICATE_Learnset:
    db 20,TRAPHOLE
    db 24,FOCUS_ENERGY
    db 27,REST
    db 30,THRASH
    db 32,DOUBLE_TEAM
    db 34,TAKE_DOWN
    db 37,SLASH
    db 40,AGILITY
    db 42,SUPER_FANG
    db 47,BODY_SLAM
    db 49,Skill__STRENGTH
    db 51,DOUBLE_EDGE
    db 56,EARTHQUAKE
    db 60,HYPER_BEAM
    db 0
RATTATA_NoEvo_Learnset:
    db 23,TRAPHOLE
    db 25,AGILITY ; Exclusive
    db 27,FOCUS_ENERGY
    db 31,REST
    db 35,THRASH
    db 39,DOUBLE_TEAM
    db 44,SLASH
    db 47,TAKE_DOWN
    db 49,SUPER_FANG
    db 54,DOUBLE_EDGE
    db 0
; ──────────────────────────────────────────────────────────────────────
SPEAROW_Learnset:
    db  1,GUST
    db  1,GROWL
    db  5,LEER
    db  9,PECK
    db 12,FURY_ATTACK
    db 16,WING_ATTACK
    db 19,WHIRLWIND
    ;  20,FEAROW
    db 0
FEAROW_Learnset:
    db 20,Skill__FLY
    db 20,SWOOP
    db 25,MIRROR_MOVE
    db 28,RAZOR_WIND
    db 28,Skill__CUT
    db 31,SCREECH
    db 34,DRILL_PECK
    db 36,AGILITY
    db 38,QUICK_ATTACK
    db 40,MIMIC
    db 45,DOUBLE_EDGE
    db 50,DOUBLE_TEAM
    db 55,EGG_BOMB
    db 60,SKY_ATTACK
    db 0
SPEAROW_NoEvo_Learnset:
    db 24,QUICK_ATTACK ; Exclusive
    db 26,SWOOP
    db 31,MIRROR_MOVE
    db 34,RAZOR_WIND
    db 35,Skill__FLY
    db 36,AGILITY
    db 41,SCREECH
    db 46,DRILL_PECK
    db 51,MIMIC
    db 55,DOUBLE_TEAM
    db 60,SKY_ATTACK
    db 0
; ──────────────────────────────────────────────────────────────────────
EKANS_Learnset:
    db  1,CONSTRICT
    db  1,LEER
    db  5,WRAP
    db  7,POISON_STING
    db 11,LEECH_LIFE
    db 13,BITE
    db 15,POISON_GAS
    db 18,ACID
    db 20,Skill__DIG
    db 21,HYPER_FANG
    ;  22,ARBOK
    db 0
ARBOK_Learnset:
    db 22,TRAPHOLE
    db 25,FLARE
    db 27,SONICBOOM
    db 29,ABSORB
    db 31,SCREECH
    db 32,Skill__LIGHT
    db 33,STRING_SHOT
    db 36,SLUDGE
    db 39,SUPERSONIC
    db 41,MEGA_DRAIN
    db 46,HAZE
    db 49,HYPNOSIS
    db 52,SUPER_FANG
    db 52,Skill__CUT
    db 57,TOXIC
    db 60,EARTHQUAKE
    db 0
EKANS_NoEvo_Learnset:
    db 24,ABSORB ; Exclusive
    db 26,TRAPHOLE
    db 29,FLARE
    db 32,SONICBOOM
    db 34,SCREECH
    db 35,Skill__LIGHT
    db 37,STRING_SHOT
    db 39,SLUDGE
    db 43,SUPERSONIC
    db 47,MEGA_DRAIN
    db 51,HAZE
    db 55,SUPER_FANG
    db 59,TOXIC
    db 0
; ──────────────────────────────────────────────────────────────────────
PIKACHU_Learnset:
    db  1,THUNDERSHOCK
    db  1,GROWL
    db  6,TAIL_WHIP
    db  8,THUNDER_WAVE
    db 10,SCRATCH
    db 11,QUICK_ATTACK ; Exclusive*
    db 13,BITE
    db 15,DOUBLE_TEAM ; Exclusive*
    db 17,FURY_SWIPES
    db 19,FLASH
    db 19,Skill__LIGHT
    db 22,SLAM
    db 26,THUNDERBOLT
    db 28,AGILITY ; Exclusive*
    db 32,THUNDERPUNCH
    db 36,SWIFT
    db 41,THUNDER_M
    db 45,HYPER_FANG
    db 50,LIGHT_SCREEN
    db 55,LOVELY_KISS
    db 0
RAICHU_Learnset:
    db  1,THUNDERSHOCK
    db  1,GROWL
    db  1,THUNDERBOLT
    db  6,TAIL_WHIP
    db  8,THUNDER_WAVE
    db 10,SCRATCH
    db 11,BITE
    db 13,FURY_SWIPES
    db 15,FLASH
    db 15,Skill__LIGHT
    db 20,SLAM
    db 25,THUNDERPUNCH
    db 28,SWIFT
    db 30,SKULL_BASH
    db 35,THUNDER_M
    db 40,HYPER_FANG
    db 40,Skill__DIG
    db 45,LIGHT_SCREEN
    db 49,MEGA_PUNCH
    db 53,BODY_SLAM
    db 55,LOVELY_KISS
    db 60,SUBMISSION
    db 0
; ──────────────────────────────────────────────────────────────────────
SANDSHREW_Learnset:
    db  1,SCRATCH
    db  1,DEFENSE_CURL
    db  5,SAND_ATTACK
    db  7,Skill__DIG
    db  9,TRAPHOLE
    db 12,FURY_SWIPES
    db 14,POISON_STING
    db 17,SLASH
    db 17,Skill__CUT
    db 20,HARDEN
    ;  22,SANDSLASH
    db 0
SANDSLASH_Learnset:
    db 22,PIN_MISSILE
    db 26,ROCK_THROW
    db 28,Skill__STRENGTH
    db 29,BLADE
    db 31,FOCUS_ENERGY
    db 33,EARTHQUAKE
    db 36,REST
    db 40,SWIFT
    db 43,TWINEEDLE
    db 48,SPIKE_CANNON
    db 52,FISSURE
    db 55,ROCK_SLIDE
    db 60,SWORDS_DANCE
    db 0
SANDSHREW_NoEvo_Learnset:
    db 25,PIN_MISSILE
    db 29,ROCK_THROW
    db 33,BLADE
    db 37,FOCUS_ENERGY
    db 39,Skill__STRENGTH
    db 42,EARTHQUAKE
    db 47,REST
    db 52,SWIFT
    db 57,FISSURE
    db 0
; ──────────────────────────────────────────────────────────────────────
NIDORAN_F_Learnset:
    db  1,TACKLE
    db  1,GROWL
    db  5,SCRATCH
    db  7,TAIL_WHIP
    db  9,SAND_ATTACK
    db 11,POISON_STING
    db 13,FURY_SWIPES
    db 14,Skill__DIG
    db 15,LEER
    db 16,DOUBLE_KICK
    db 16,POISONPOWDER
    ;  16,NIDORINA
    db 0
NIDORINA_Learnset:
    db 19,BITE
    db 20,TRAPHOLE ; Exclusive
    db 22,FOCUS_ENERGY
    db 24,DOUBLE_TEAM ; Exclusive*
    db 26,SLAM
    db 28,QUICK_ATTACK ; Exclusive*
    db 30,SLASH
    db 30,Skill__CUT
    db 33,AGILITY ; Exclusive*
    db 37,SKULL_BASH
    db 40,ROCK_THROW
    db 42,SLUDGE
    db 47,BODY_SLAM
    db 49,Skill__STRENGTH
    db 52,EARTHQUAKE
    db 60,TOXIC
    db 0
NIDOQUEEN_Learnset:
    db 16,HORN_ATTACK
    db 16,FURY_ATTACK
    db 17,RAGE
    db 18,BITE
    db 20,FOCUS_ENERGY
    db 20,Skill__FLOAT
    db 21,SLAM
    db 22,THRASH
    db 22,Skill__STRENGTH
    db 25,SLASH
    db 25,Skill__CUT
    db 25,HYPER_FANG
    db 27,BODY_SLAM
    db 29,ROCK_THROW
    db 31,SKULL_BASH
    db 33,STOMP
    db 35,SLUDGE
    db 39,DIZZY_PUNCH
    db 43,EARTHQUAKE
    db 48,HORN_DRILL
    db 53,ROCK_SLIDE
    db 55,TRAPHOLE
    db 57,TOXIC
    db 60,FISSURE
    db 65,HYPER_BEAM
    db 0
NIDORAN_F_NoEvo_Learnset:
    db 21,DOUBLE_TEAM ; Exclusive
    db 23,TRAPHOLE ; Exclusive
    db 24,QUICK_ATTACK ; Exclusive
    db 26,BITE
    db 28,AGILITY ; Exclusive
    db 31,SLAM
    db 36,FOCUS_ENERGY
    db 41,SLASH
    db 41,Skill__CUT
    db 46,SKULL_BASH
    db 51,SLUDGE
    db 0
; ──────────────────────────────────────────────────────────────────────
NIDORAN_M_Learnset:
    db  1,TACKLE
    db  1,GROWL
    db  5,SCRATCH
    db  7,HORN_ATTACK
    db  9,SAND_ATTACK
    db 11,POISON_STING
    db 13,FURY_ATTACK
    db 14,Skill__DIG
    db 15,LEER
    db 16,DOUBLE_KICK
    db 16,POISONPOWDER
    ;  16,NIDORINO
    db 0
NIDORINO_Learnset:
    db 19,BITE
    db 20,TRAPHOLE ; Exclusive
    db 22,FOCUS_ENERGY
    db 24,DOUBLE_TEAM ; Exclusive*
    db 26,SLAM
    db 28,QUICK_ATTACK ; Exclusive*
    db 30,HYPER_FANG
    db 30,Skill__CUT
    db 33,AGILITY ; Exclusive*
    db 37,SKULL_BASH
    db 40,ROCK_THROW
    db 42,SLUDGE
    db 47,BODY_SLAM
    db 49,Skill__STRENGTH
    db 52,EARTHQUAKE
    db 60,TOXIC
    db 0
NIDOKING_Learnset:
    db 16,TAIL_WHIP
    db 16,FURY_SWIPES
    db 17,RAGE
    db 18,BITE
    db 20,FOCUS_ENERGY
    db 20,Skill__FLOAT
    db 21,SLAM
    db 22,THRASH
    db 22,Skill__STRENGTH
    db 25,HYPER_FANG
    db 25,Skill__CUT
    db 25,SLASH
    db 27,BODY_SLAM
    db 29,ROCK_THROW
    db 31,SLUDGE
    db 33,STOMP
    db 35,SKULL_BASH
    db 39,DIZZY_PUNCH
    db 43,EARTHQUAKE
    db 48,HORN_DRILL
    db 53,ROCK_SLIDE
    db 55,TRAPHOLE
    db 57,TOXIC
    db 60,FISSURE
    db 65,HYPER_BEAM
    db 0
NIDORAN_M_NoEvo_Learnset:
    db 21,DOUBLE_TEAM ; Exclusive
    db 23,TRAPHOLE ; Exclusive
    db 24,QUICK_ATTACK ; Exclusive
    db 26,BITE
    db 28,AGILITY ; Exclusive
    db 31,SLAM
    db 36,FOCUS_ENERGY
    db 41,HYPER_FANG
    db 41,Skill__CUT
    db 46,SKULL_BASH
    db 51,SLUDGE
    db 0
; ──────────────────────────────────────────────────────────────────────
CLEFAIRY_Learnset:
    db  1,POUND
    db  1,GROWL
    db  7,DEFENSE_CURL ; Exclusive
    db 10,DISABLE
    db 13,SING
    db 16,DOUBLESLAP
    db 18,SUPERSONIC
    db 20,SWIFT
    db 22,SLAM
    db 23,SCREECH
    db 24,MINIMIZE
    db 26,BIDE
    db 28,METRONOME
    db 30,TELEPORT
    db 32,REST
    db 34,SONICBOOM
    db 37,BODY_SLAM
    db 40,Skill__FLOAT
    db 42,SOFTBOILED
    db 42,Skill__HEAL
    db 47,LIGHT_SCREEN
    db 52,REFLECT
    db 57,DOUBLE_EDGE
    db 0
CLEFABLE_Learnset:
    db  1,POUND
    db  1,GROWL
    db  1,SWIFT
    db  8,DISABLE
    db 10,TELEPORT
    db 12,SING
    db 15,DOUBLESLAP
    db 16,SUPERSONIC
    db 17,BIDE
    db 19,SLAM
    db 20,SCREECH
    db 21,DEFENSE_CURL
    db 23,MINIMIZE
    db 25,SONICBOOM
    db 27,METRONOME
    db 29,COUNTER
    db 31,REST
    db 34,BODY_SLAM
    db 36,Skill__FLOAT
    db 39,SOFTBOILED
    db 39,Skill__HEAL
    db 44,LIGHT_SCREEN
    db 46,ROAR
    db 48,REFLECT
    db 51,DOUBLE_EDGE
    db 56,LOVELY_KISS
    db 60,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
VULPIX_Learnset:
    db  1,TACKLE
    db  1,TAIL_WHIP
    db  8,EMBER ; Exclusive
    db  9,Skill__LIGHT
    db 13,ROAR
    db 17,BITE
    db 19,SMOKESCREEN
    db 21,QUICK_ATTACK ; Exclusive
    db 23,Skill__DIG
    db 25,DOUBLE_KICK
    db 28,CONFUSE_RAY
    db 30,AGILITY ; Exclusive
    db 32,DOUBLE_TEAM ; Exclusive
    db 34,POISON_GAS
    db 37,SLAM
    db 40,SMOG
    db 41,Skill__CUT
    db 42,FLAMETHROWER
    db 47,FIRE_SPIN
    db 52,SLASH
    db 54,LOVELY_KISS
    db 56,FIRE_BLAST
    db 0
NINETALES_Learnset:
    db  1,TACKLE
    db  1,TAIL_WHIP
    db  1,BITE
    db  5,EMBER
    db  6,Skill__LIGHT
    db 10,ROAR
    db 15,SMOKESCREEN
    db 18,Skill__DIG
    db 20,HYPER_FANG
    db 22,DOUBLE_KICK
    db 25,CONFUSE_RAY
    db 27,POISON_GAS
    db 28,QUICK_ATTACK
    db 31,SLAM
    db 31,Skill__CUT
    db 32,SMOG
    db 33,FLAMETHROWER
    db 36,SKULL_BASH
    db 37,CONFUSION
    db 38,TRAPHOLE
    db 40,AGILITY
    db 40,FIRE_PUNCH
    db 43,FIRE_SPIN
    db 45,SLASH
    db 48,LOVELY_KISS
    db 48,Skill__HEAL
    db 50,FIRE_BLAST
    db 55,BODY_SLAM
    db 60,NIGHT_SHADE
    db 60,SUPER_FANG
    db 0
; ──────────────────────────────────────────────────────────────────────
VULPIX_Alola_Learnset:
    db  1,TACKLE
    db  1,TAIL_WHIP
    db  8,AURORA_BEAM ; Exclusive
    db 13,ROAR
    db 17,BITE
    db 19,MIST
    db 20,Skill__FLOAT
    db 21,QUICK_ATTACK ; Exclusive
    db 23,Skill__DIG
    db 25,DOUBLE_KICK
    db 28,CONFUSE_RAY
    db 30,AGILITY ; Exclusive
    db 32,DOUBLE_TEAM ; Exclusive
    db 34,HAZE
    db 37,SLAM
    db 40,SCREECH
    db 41,Skill__CUT
    db 42,ICE_BEAM
    db 47,TSUNAMI
    db 52,SLASH
    db 54,LOVELY_KISS
    db 56,BLIZZARD
    db 0
NINETALES_Alola_Learnset:
    db  1,TACKLE
    db  1,TAIL_WHIP
    db  1,BITE
    db  8,ROAR
    db 13,MIST
    db 16,Skill__FLOAT
    db 17,AURORA_BEAM
    db 18,Skill__DIG
    db 20,HYPER_FANG
    db 22,DOUBLE_KICK
    db 25,CONFUSE_RAY
    db 27,HAZE
    db 28,QUICK_ATTACK
    db 31,SLAM
    db 31,Skill__CUT
    db 32,SCREECH
    db 33,ICE_BEAM
    db 36,SKULL_BASH
    db 37,CONFUSION
    db 38,TRAPHOLE
    db 40,AGILITY
    db 40,ICE_PUNCH
    db 43,TSUNAMI
    db 45,SLASH
    db 48,LOVELY_KISS
    db 48,Skill__HEAL
    db 50,BLIZZARD
    db 55,BODY_SLAM
    db 60,NIGHT_SHADE
    db 60,SUPER_FANG
    db 0
; ──────────────────────────────────────────────────────────────────────
JIGGLYPUFF_Learnset:
    db  1,POUND
    db  1,SING
    db  7,DEFENSE_CURL ; Exclusive
    db 10,GROWL
    db 13,DISABLE
    db 16,DOUBLESLAP
    db 18,SONICBOOM
    db 20,SWIFT
    db 22,SLAM
    db 23,SCREECH
    db 24,MINIMIZE
    db 26,BIDE
    db 28,REST
    db 30,TELEPORT
    db 32,METRONOME
    db 34,SUPERSONIC
    db 37,BODY_SLAM
    db 40,Skill__FLOAT
    db 42,SOFTBOILED
    db 42,Skill__HEAL
    db 47,REFLECT
    db 52,LIGHT_SCREEN
    db 57,DOUBLE_EDGE
    db 0
WIGGLYTUFF_Learnset:
    db  1,POUND
    db  1,SING
    db  1,SWIFT
    db  8,GROWL
    db 10,TELEPORT
    db 12,DISABLE
    db 15,DOUBLESLAP
    db 16,SONICBOOM
    db 17,BIDE
    db 19,SLAM
    db 20,SCREECH
    db 21,DEFENSE_CURL
    db 23,MINIMIZE
    db 25,SUPERSONIC
    db 27,REST
    db 29,COUNTER
    db 31,METRONOME
    db 34,BODY_SLAM
    db 36,Skill__FLOAT
    db 39,SOFTBOILED
    db 39,Skill__HEAL
    db 44,REFLECT
    db 46,ROAR
    db 48,LIGHT_SCREEN
    db 51,DOUBLE_EDGE
    db 56,LOVELY_KISS
    db 60,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
ZUBAT_Learnset:
    db  1,LEECH_LIFE
    db  1,SUPERSONIC
    db  7,POISON_STING
    db 10,QUICK_ATTACK
    db 11,BITE
    db 13,LEER
    db 15,ACID
    db 16,POISONPOWDER
    db 17,GUST
    db 19,SCREECH
    db 21,HYPER_FANG
    ;  22,GOLBAT
    db 0
GOLBAT_Learnset:
    db 22,Skill__FLY
    db 22,WING_ATTACK
    db 24,AGILITY
    db 26,RAZOR_WIND
    db 26,Skill__CUT
    db 27,ABSORB
    db 28,MEGA_DRAIN
    db 30,SONICBOOM
    db 31,POISON_GAS
    db 32,SWOOP
    db 34,CONFUSE_RAY
    db 36,DISABLE
    db 37,LICK
    db 38,STRING_SHOT
    db 40,HAZE
    db 43,SLUDGE
    db 45,WHIRLWIND
    db 47,DOUBLE_TEAM
    db 51,TOXIC
    db 55,SUPER_FANG
    db 58,NIGHT_SHADE
    db 60,SKY_ATTACK
    db 0
ZUBAT_NoEvo_Learnset:
    db 24,ABSORB ; Exclusive
    db 27,WING_ATTACK
    db 30,AGILITY
    db 33,LICK ; Exclusive
    db 37,SONICBOOM
    db 38,POISON_GAS
    db 40,CONFUSE_RAY
    db 42,DISABLE
    db 44,STRING_SHOT
    db 46,HAZE
    db 49,SLUDGE
    db 53,DOUBLE_TEAM
    db 55,Skill__FLY
    db 57,TOXIC
    db 0
; ──────────────────────────────────────────────────────────────────────
ODDISH_Learnset:
    db  1,ABSORB
    db  1,GROWTH
    db  9,LEECH_SEED
    db 11,DEFENSE_CURL
    db 13,POISON_STING
    db 15,POISONPOWDER
    db 17,SLEEP_POWDER
    db 19,STUN_SPORE
    ;  21,GLOOM
    db 0
GLOOM_Learnset:
    db 21,Skill__CUT
    db 21,ACID
    db 25,MEGA_DRAIN
    db 28,SLUDGE
    db 28,Skill__HEAL
    db 30,LEECH_LIFE ; Exclusive
    db 32,PETAL_DANCE
    db 34,STRING_SHOT
    db 35,VINE_WHIP
    db 37,SLAM
    db 42,BARRAGE
    db 45,HAZE
    db 46,BIND
    db 47,SPORE
    db 52,SOLARBEAM
    db 56,RAZOR_LEAF ; Exclusive
    db 60,TOXIC
    db 0
VILEPLUME_Learnset:
    db 21,Skill__CUT
    db 21,ACID
    db 21,MEGA_DRAIN
    db 25,PETAL_DANCE
    db 28,SLUDGE
    db 28,Skill__HEAL
    db 30,STRING_SHOT
    db 32,SLAM
    db 34,VINE_WHIP
    db 36,LEECH_LIFE
    db 38,BARRAGE
    db 39,REFLECT
    db 41,BIND
    db 42,HAZE
    db 44,SPORE
    db 46,Skill__LIGHT
    db 49,SOLARBEAM
    db 52,TOXIC
    db 58,NIGHT_SHADE
    db 60,SWORDS_DANCE
    db 60,RAZOR_LEAF
    db 0
ODDISH_NoEvo_Learnset:
    db 23,LEECH_LIFE ; Exclusive
    db 27,MEGA_DRAIN
    db 28,Skill__HEAL
    db 31,RAZOR_LEAF ; Exclusive
    db 35,VINE_WHIP
    db 36,Skill__CUT
    db 39,SLAM
    db 44,BARRAGE
    db 0
; ──────────────────────────────────────────────────────────────────────
PARAS_Learnset:
    db  1,SCRATCH
    db  1,STUN_SPORE
    db  9,LEECH_SEED
    db 11,LEECH_LIFE
    db 13,POISONPOWDER
    db 14,SLEEP_POWDER
    db 15,FURY_SWIPES
    db 17,ABSORB
    db 19,BLADE
    db 19,Skill__CUT
    db 22,VICEGRIP
    ;  24,PARASECT
    db 0
PARASECT_Learnset:
    db 24,GROWTH
    db 25,PIN_MISSILE
    db 26,CONFUSION
    db 27,SPORE
    db 27,Skill__HEAL
    db 30,MEGA_DRAIN
    db 32,SLASH
    db 32,Skill__DIG
    db 33,STRING_SHOT
    db 35,LIGHT_SCREEN
    db 37,BARRAGE
    db 39,TWINEEDLE
    db 42,TRAPHOLE
    db 45,SOLARBEAM
    db 48,SWORDS_DANCE
    db 56,GUILLOTINE
    db 60,HAMMER
    db 0
PARAS_NoEvo_Learnset:
    db 25,GROWTH
    db 27,CONFUSION
    db 29,PIN_MISSILE
    db 33,SPORE
    db 33,Skill__HEAL
    db 37,MEGA_DRAIN
    db 39,SLASH
    db 39,Skill__DIG
    db 41,STRING_SHOT
    db 43,LIGHT_SCREEN
    db 47,BARRAGE
    db 53,TWINEEDLE
    db 57,SOLARBEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
VENONAT_Learnset:
    db  1,TACKLE
    db  1,DISABLE
    db  4,SUPERSONIC
    db  5,TELEPORT
    db  8,PSYWAVE
    db 11,POISONPOWDER
    db 13,CONFUSION
    db 15,LEECH_LIFE
    db 17,HYPNOSIS
    db 19,SONICBOOM
    db 21,Skill__LIGHT
    db 22,STUN_SPORE
    db 24,ABSORB
    db 26,LIGHT_SCREEN
    db 28,SLEEP_POWDER
    db 29,Skill__HEAL
    ;  31,VENOMOTH
    db 0
VENOMOTH_Learnset:
    db 31,GUST
    db 31,PIN_MISSILE
    db 31,KINESIS
    db 31,Skill__FLY
    db 32,STRING_SHOT
    db 33,WHIRLWIND
    db 35,PSYBEAM
    db 37,RAZOR_WIND
    db 39,SLUDGE
    db 41,SPORE
    db 43,REFLECT
    db 44,PSYCHIC_M
    db 47,TWINEEDLE
    db 50,BARRIER
    db 52,MEGA_DRAIN
    db 53,SWOOP
    db 55,NIGHT_SHADE
    db 60,TOXIC
    db 0
VENONAT_NoEvo_Learnset:
    db 33,STRING_SHOT
    db 35,KINESIS
    db 36,PIN_MISSILE
    db 40,PSYBEAM
    db 45,SPORE
    db 47,SLUDGE
    db 49,REFLECT
    db 50,PSYCHIC_M
    db 54,BARRIER
    db 56,MEGA_DRAIN
    db 58,NIGHT_SHADE
    db 60,TOXIC
    db 0
; ──────────────────────────────────────────────────────────────────────
DIGLETT_Learnset:
    db  1,SCRATCH
    db  1,GROWL
    db  3,Skill__DIG
    db  5,SAND_ATTACK
    db  9,TRAPHOLE
    db 13,AGILITY
    db 17,FURY_SWIPES
    db 21,DOUBLE_TEAM
    db 23,QUICK_ATTACK
    db 25,SLASH
    db 26,Skill__CUT
    ;  26,DUGTRIO
    db 0
DUGTRIO_Learnset:
    db 26,TRI_ATTACK
    db 28,ROCK_THROW
    db 30,Skill__STRENGTH
    db 31,EARTHQUAKE
    db 36,SCREECH
    db 38,REST
    db 40,BLADE
    db 45,FISSURE
    db 50,ROCK_SLIDE
    db 55,SUPERSONIC
    db 60,SWORDS_DANCE
    db 0
DIGLETT_NoEvo_Learnset:
    db 30,ROCK_THROW
    db 34,EARTHQUAKE
    db 38,SCREECH
    db 43,REST
    db 48,BLADE
    db 53,ROCK_SLIDE
    db 58,FISSURE
    db 0
; ──────────────────────────────────────────────────────────────────────
MEOWTH_Learnset:
    db  1,SCRATCH
    db  1,GROWL
    db  5,TAIL_WHIP
    db  9,PAY_DAY
    db 11,DEFENSE_CURL
    db 13,QUICK_ATTACK
    db 15,BITE
    db 18,FURY_SWIPES
    db 21,SLAM
    db 24,SCREECH
    db 26,FLARE
    db 26,Skill__LIGHT
    ;  28,PERSIAN
    db 0
PERSIAN_Learnset:
    db 28,Skill__DIG
    db 28,HYPER_FANG
    db 29,REST
    db 32,SLASH
    db 32,Skill__CUT
    db 34,AGILITY
    db 36,TAKE_DOWN
    db 41,DOUBLE_TEAM
    db 46,BODY_SLAM
    db 50,LOVELY_KISS
    db 55,DOUBLE_EDGE
    db 58,SUPER_FANG
    db 60,HYPER_BEAM
    db 0
MEOWTH_NoEvo_Learnset:
    db 29,HYPER_FANG
    db 34,REST
    db 39,SLASH
    db 41,AGILITY
    db 41,Skill__CUT
    db 43,TAKE_DOWN
    db 45,KINESIS ; Exclusive*
    db 48,DOUBLE_TEAM
    db 52,LOVELY_KISS
    db 57,DOUBLE_EDGE
    db 0
; ──────────────────────────────────────────────────────────────────────
PSYDUCK_Learnset:
    db  1,SCRATCH
    db  1,TAIL_WHIP
    db  7,PSYWAVE
    db  9,KINESIS
    db 10,DISABLE
    db 13,CONFUSION
    db 15,TELEPORT
    db 17,PECK
    db 19,AMNESIA
    db 21,FURY_SWIPES
    db 23,BUBBLE
    db 25,MEDITATE
    db 26,Skill__LIGHT
    db 27,SCREECH
    db 29,SUPERSONIC
    db 31,PSYBEAM
    ;  33,GOLDUCK
    db 0
GOLDUCK_Learnset:
    db 33,Skill__FLOAT
    db 33,WATER_GUN
    db 33,BUBBLEBEAM
    db 33,PAY_DAY
    db 35,SLASH
    db 35,Skill__CUT
    db 37,WATERFALL
    db 39,SONICBOOM
    db 39,Skill__DIG
    db 42,TSUNAMI
    db 44,FLARE
    db 46,LIGHT_SCREEN
    db 46,REFLECT
    db 46,BARRIER
    db 48,ICE_PUNCH
    db 52,HYDRO_PUMP
    db 55,PSYCHIC_M
    db 58,DRILL_PECK
    db 60,HYPER_BEAM
    db 0
PSYDUCK_NoEvo_Learnset:
    db 34,LIGHT_SCREEN ; Exclusive
    db 34,REFLECT ; Exclusive
    db 34,BARRIER ; Exclusive
    db 36,FLARE ; Exclusive
    db 40,PAY_DAY
    db 41,PSYCHIC_M ; Exclusive
    db 43,SLASH
    db 48,SONICBOOM
    db 0
; ──────────────────────────────────────────────────────────────────────
MANKEY_Learnset:
    db  1,SCRATCH
    db  1,LEER
    db  8,KARATE_CHOP
    db 10,LOW_KICK
    db 12,FURY_SWIPES
    db 14,FOCUS_ENERGY
    db 14,Skill__STRENGTH
    db 15,RAGE
    db 17,DOUBLE_TEAM
    db 19,DOUBLE_KICK
    db 21,COMET_PUNCH
    db 22,Skill__DIG
    db 23,ROLLING_KICK
    db 25,MEGA_PUNCH
    ;  28,PRIMEAPE
    db 0
PRIMEAPE_Learnset:
    db 28,STRIKE
    db 30,TRAPHOLE
    db 32,ROCK_THROW
    db 34,SUBMISSION
    db 36,SLASH
    db 36,Skill__CUT
    db 37,SEISMIC_TOSS
    db 39,BARRAGE
    db 41,JUMP_KICK
    db 45,THRASH
    db 46,SCREECH
    db 49,COUNTER
    db 50,Skill__FLOAT
    db 51,MEGA_KICK
    db 55,EARTHQUAKE
    db 58,HI_JUMP_KICK
    db 60,ROCK_SLIDE
    db 0
MANKEY_NoEvo_Learnset:
    db 30,BARRAGE ; Exclusive
    db 34,STRIKE
    db 38,SUBMISSION
    db 42,SEISMIC_TOSS
    db 46,JUMP_KICK
    db 48,SLASH
    db 48,Skill__CUT
    db 50,THRASH
    db 54,SCREECH
    db 58,MEGA_KICK
    db 0
; ──────────────────────────────────────────────────────────────────────
GROWLITHE_Learnset:
    db  1,BITE
    db  1,ROAR
    db  8,EMBER ; Exclusive
    db  9,Skill__LIGHT
    db 13,LEER
    db 17,HYPER_FANG
    db 19,SMOKESCREEN
    db 21,AGILITY ; Exclusive
    db 23,Skill__DIG
    db 25,DOUBLE_KICK
    db 28,TAKE_DOWN
    db 30,QUICK_ATTACK ; Exclusive
    db 32,DOUBLE_TEAM ; Exclusive
    db 34,POISON_GAS
    db 37,SLAM
    db 40,SMOG
    db 41,Skill__CUT
    db 42,FLAMETHROWER
    db 47,FIRE_SPIN
    db 52,SUPER_FANG
    db 54,THRASH
    db 56,FIRE_BLAST
    db 0
ARCANINE_Learnset:
    db  1,BITE
    db  1,ROAR
    db  1,HYPER_FANG
    db  5,EMBER
    db  6,Skill__LIGHT
    db 10,LEER
    db 15,SMOKESCREEN
    db 18,Skill__DIG
    db 20,TAKE_DOWN
    db 22,DOUBLE_KICK
    db 25,TRAPHOLE
    db 27,POISON_GAS
    db 28,AGILITY
    db 31,SLAM
    db 31,Skill__CUT
    db 32,SMOG
    db 33,FLAMETHROWER
    db 36,SKULL_BASH
    db 37,FOCUS_ENERGY
    db 38,BODY_SLAM
    db 40,QUICK_ATTACK
    db 40,FIRE_PUNCH
    db 43,FIRE_SPIN
    db 45,SUPER_FANG
    db 48,THRASH
    db 48,Skill__STRENGTH
    db 50,FIRE_BLAST
    db 55,EARTHQUAKE
    db 60,SOLARBEAM
    db 60,DOUBLE_EDGE
    db 0
; ──────────────────────────────────────────────────────────────────────
POLIWAG_Learnset:
    db  1,BUBBLE
    db  1,SPLASH
    db  7,HYPNOSIS
    db  9,TACKLE
    db 11,STRING_SHOT
    db 12,QUICK_ATTACK
    db 13,WATER_GUN
    db 15,DOUBLESLAP
    db 17,AGILITY
    db 19,SLAM
    db 21,BUBBLEBEAM
    db 23,FOCUS_ENERGY
    db 23,Skill__FLOAT
    ;  25,POLIWHIRL
    db 0
POLIWHIRL_Learnset:
    db 25,Skill__STRENGTH
    db 25,KARATE_CHOP
    db 26,DOUBLE_KICK
    db 27,WATERFALL
    db 27,LOW_KICK
    db 28,COMET_PUNCH
    db 28,ROLLING_KICK
    db 29,MEGA_PUNCH
    db 32,AMNESIA ; Exclusive
    db 32,DOUBLE_TEAM ; Exclusive
    db 34,STRIKE
    db 36,HAZE
    db 38,LEECH_LIFE
    db 40,TSUNAMI
    db 43,SEISMIC_TOSS
    db 45,SUBMISSION
    db 47,CONFUSION ; Exclusive
    db 49,JUMP_KICK
    db 50,HYDRO_PUMP
    db 52,MEGA_KICK
    db 55,ICE_PUNCH
    db 0
POLIWRATH_Learnset:
    db 25,Skill__STRENGTH
    db 25,KARATE_CHOP
    db 25,DOUBLE_KICK
    db 25,LOW_KICK
    db 26,COMET_PUNCH
    db 26,ROLLING_KICK
    db 27,WATERFALL
    db 28,MEGA_PUNCH
    db 30,STRIKE
    db 32,HAZE
    db 34,SEISMIC_TOSS
    db 36,TSUNAMI
    db 37,LEECH_LIFE
    db 39,SUBMISSION
    db 43,BODY_SLAM
    db 46,JUMP_KICK
    db 48,HYDRO_PUMP
    db 50,MEGA_KICK
    db 53,DOUBLE_TEAM
    db 55,ICE_PUNCH
    db 58,AMNESIA
    db 58,CONFUSION
    db 60,HI_JUMP_KICK
    db 0
POLIWAG_NoEvo_Learnset:
    db 28,AMNESIA ; Exclusive
    db 28,DOUBLE_TEAM ; Exclusive
    db 32,CONFUSION ; Exclusive
    db 36,HAZE
    db 39,LEECH_LIFE
    db 41,WATERFALL
    db 46,LOW_KICK
    db 51,TSUNAMI
    db 0
; ──────────────────────────────────────────────────────────────────────
ABRA_Learnset:
    db  1,TELEPORT
    db  9,PSYWAVE
    db 10,FLASH
    db 12,CONFUSION
    db 15,DISABLE
    ;  16,KADABRA
    db 0
KADABRA_Learnset:
    db 16,KINESIS
    db 20,PSYBEAM
    db 0
ALAKAZAM_Learnset:
    db 16,KINESIS
    db 16,PSYBEAM
    db 0
KADABRA_ALAKAZAM_Learnset:
    db 21,SUPERSONIC
    db 24,SWIFT
    db 27,MIST
    db 31,RECOVER
    db 33,FLARE
    db 35,AGILITY
    db 38,PSYCHIC_M
    db 41,HYPNOSIS
    db 44,REFLECT
    db 48,LIGHT_SCREEN
    db 51,BARRIER
    db 56,NIGHT_SHADE
    db 60,DREAM_EATER
    db 65,HYPER_BEAM
    db 0
ABRA_NoEvo_Learnset:
    db 20,KINESIS
    db 24,PSYBEAM
    db 27,SUPERSONIC
    db 31,SWIFT
    db 35,RECOVER
    db 38,AGILITY
    db 43,PSYCHIC_M
    db 48,REFLECT
    db 50,LIGHT_SCREEN
    db 53,BARRIER
    db 0
; ──────────────────────────────────────────────────────────────────────
MACHOP_Learnset:
    db  1,KARATE_CHOP
    db  1,LEER
    db  9,LOW_KICK
    db 11,COMET_PUNCH
    db 13,FOCUS_ENERGY
    db 13,Skill__STRENGTH
    db 16,DOUBLE_KICK
    db 18,DOUBLE_TEAM
    db 21,ROLLING_KICK
    db 23,MEGA_PUNCH
    db 26,ROCK_THROW
    ;  28,MACHOKE
    db 0
MACHOKE_Learnset:
    db 28,STRIKE
    db 31,SUBMISSION
    db 0
MACHAMP_Learnset:
    db 28,STRIKE
    db 28,SUBMISSION
    db 0
MACHOKE_MACHAMP_Learnset:
    db 33,SEISMIC_TOSS
    db 35,AGILITY
    db 36,Skill__DIG
    db 37,JUMP_KICK
    db 40,TRAPHOLE
    db 42,THRASH
    db 44,ROCK_SLIDE
    db 46,COUNTER
    db 48,Skill__FLOAT
    db 51,MEGA_KICK
    db 55,EARTHQUAKE
    db 58,HI_JUMP_KICK
    db 60,FISSURE
    db 65,HYPER_BEAM
    db 0
MACHOP_NoEvo_Learnset:
    db 31,AGILITY ; Exclusive
    db 34,STRIKE
    db 37,SUBMISSION
    db 41,SEISMIC_TOSS
    db 45,JUMP_KICK
    db 50,COUNTER
    db 55,MEGA_KICK
    db 0
; ──────────────────────────────────────────────────────────────────────
BELLSPROUT_Learnset:
    db  1,VINE_WHIP
    db  1,GROWTH
    db  9,LEECH_LIFE
    db 11,CONSTRICT
    db 13,POISON_STING
    db 15,POISONPOWDER
    db 17,SLEEP_POWDER
    db 19,STUN_SPORE
    ;  21,WEEPINBELL
    db 0
WEEPINBELL_Learnset:
    db 21,Skill__CUT
    db 21,ACID
    db 25,STRING_SHOT
    db 28,SLUDGE
    db 28,Skill__HEAL
    db 30,ABSORB ; Exclusive
    db 32,RAZOR_LEAF
    db 34,BIND
    db 35,SLAM
    db 37,PIN_MISSILE
    db 42,BARRAGE
    db 45,HAZE
    db 46,HYPER_FANG
    db 47,SPORE
    db 52,SOLARBEAM
    db 56,LEECH_SEED ; Exclusive
    db 60,TOXIC
    db 0
VICTREEBEL_Learnset:
    db 21,Skill__CUT
    db 21,ACID
    db 21,STRING_SHOT
    db 25,RAZOR_LEAF
    db 28,SLUDGE
    db 28,Skill__HEAL
    db 30,BIND
    db 32,SLAM
    db 34,ABSORB
    db 36,PIN_MISSILE
    db 38,BARRAGE
    db 40,LIGHT_SCREEN
    db 41,HYPER_FANG
    db 42,HAZE
    db 44,SPORE
    db 46,Skill__LIGHT
    db 49,SOLARBEAM
    db 52,TOXIC
    db 58,SUPER_FANG
    db 60,SWORDS_DANCE
    db 60,LEECH_SEED
    db 0
BELLSPROUT_NoEvo_Learnset:
    db 23,ABSORB ; Exclusive
    db 27,BIND
    db 28,Skill__HEAL
    db 31,LEECH_SEED ; Exclusive
    db 35,RAZOR_LEAF
    db 36,Skill__CUT
    db 39,SLAM
    db 44,PIN_MISSILE
    db 0
; ──────────────────────────────────────────────────────────────────────
TENTACOOL_Learnset:
    db  1,CONSTRICT
    db  1,SUPERSONIC
    db  6,POISON_STING
    db  7,BUBBLE
    db  9,ACID
    db 10,LEECH_LIFE
    db 12,DISABLE
    db 14,LEER
    db 15,WATER_GUN
    db 15,Skill__FLOAT
    db 16,SONICBOOM
    db 18,POISONPOWDER
    db 20,BIND
    db 21,FLASH
    db 21,Skill__LIGHT
    db 24,ABSORB
    db 26,FLARE
    db  1,Skill__LIGHT
    db 28,BUBBLEBEAM
    ;  30,TENTACRUEL
    db 0
TENTACRUEL_Learnset:
    db 30,SLUDGE
    db 32,WATERFALL
    db 34,BARRIER
    db 36,STRING_SHOT
    db 38,SCREECH
    db 40,TSUNAMI
    db 42,MEGA_DRAIN
    db 43,HAZE
    db 45,VINE_WHIP
    db 45,Skill__CUT
    db 47,HYDRO_PUMP
    db 51,AURORA_BEAM
    db 53,ACID_ARMOR
    db 55,BODY_SLAM
    db 58,TOXIC
    db 60,SWORDS_DANCE
    db 65,HYPER_BEAM
    db 0
TENTACOOL_NoEvo_Learnset:
    db 33,VINE_WHIP ; Exclusive
    db 37,SLUDGE
    db 41,SCREECH
    db 44,STRING_SHOT
    db 47,TSUNAMI
    db 51,HAZE
    db 55,HYDRO_PUMP
    db 58,ACID_ARMOR
    db 60,TOXIC
    db 0
; ──────────────────────────────────────────────────────────────────────
GEODUDE_Learnset:
    db  1,TACKLE
    db  1,DEFENSE_CURL
    db  6,POUND
    db  9,DOUBLESLAP
    db 11,SAND_ATTACK
    db 12,Skill__DIG
    db 13,ROCK_THROW
    db 14,HEADBUTT
    db 15,HARDEN
    db 17,TRAPHOLE
    db 19,MEGA_PUNCH
    db 21,SELFDESTRUCT
    db 24,Skill__STRENGTH
    ;  25,GRAVELER
    db 0
GRAVELER_Learnset:
    db 25,STOMP
    db 28,BODY_SLAM
    db 0
GOLEM_Learnset:
    db 25,STOMP
    db 25,BODY_SLAM
    db 0
GRAVELER_GOLEM_Learnset:
    db 30,ROCK_SLIDE
    db 33,SKULL_BASH
    db 36,EARTHQUAKE
    db 38,LEER
    db 40,REST
    db 44,FIRE_PUNCH
    db 48,THRASH
    db 51,EXPLOSION
    db 54,FLAMETHROWER
    db 58,FISSURE
    db 60,SUBSTITUTE
    db 65,HYPER_BEAM
    db 0
GEODUDE_NoEvo_Learnset:
    db 26,LEER ; Exclusive
    db 31,BODY_SLAM
    db 35,ROCK_SLIDE
    db 38,SKULL_BASH
    db 42,EARTHQUAKE
    db 47,REST
    db 52,FIRE_PUNCH
    db 57,EXPLOSION
    db 0
; ──────────────────────────────────────────────────────────────────────
PONYTA_Learnset:
    db  1,TACKLE
    db  1,GROWL
    db  5,TAIL_WHIP
    db  8,Skill__LIGHT
    db 12,QUICK_ATTACK
    db 10,AGILITY
    db 12,EMBER
    db 14,STOMP
    db 16,ROAR
    db 18,DOUBLE_KICK
    db 20,SLAM
    db 22,SMOKESCREEN
    db 24,DOUBLE_TEAM
    db 26,FIRE_SPIN
    db 29,TAKE_DOWN
    db 32,REST
    db 35,FLAMETHROWER
    db 37,SKULL_BASH
    db 39,POISON_GAS
    ;  40,RAPIDASH
    db 0
RAPIDASH_Learnset:
    db 40,HORN_ATTACK
    db 40,FURY_ATTACK
    db 40,FIRE_PUNCH
    db 42,RAGE
    db 42,THRASH
    db 43,Skill__STRENGTH
    db 44,HORN_DRILL
    db 46,DOUBLE_EDGE
    db 50,FIRE_BLAST
    db 55,BODY_SLAM
    db 60,NIGHT_SHADE
    db 0
PONYTA_NoEvo_Learnset:
    db 43,RAGE
    db 43,THRASH
    db 48,DOUBLE_EDGE
    db 53,FIRE_BLAST
    db 58,BODY_SLAM
    db 0
; ──────────────────────────────────────────────────────────────────────
SLOWPOKE_Learnset:
    db  1,TACKLE
    db  1,GROWL
    db  5,TAIL_WHIP
    db  7,PSYWAVE
    db 10,BUBBLE
    db 12,CONFUSION
    db 14,DISABLE
    db 16,WATER_GUN
    db 17,TELEPORT
    db 18,BIDE
    db 20,MEDITATE
    db 22,KINESIS
    db 24,WATERFALL
    db 26,AMNESIA
    db 26,REST
    db 28,HEADBUTT
    db 30,PSYBEAM
    db 32,HAZE
    db 34,BUBBLEBEAM
    db 37,SKULL_BASH
    ;  37,SLOWBRO
    db 0
SLOWBRO_Learnset:
    db 37,MEGA_PUNCH
    db 37,WITHDRAW
    db 37,Skill__FLOAT
    db 40,TSUNAMI
    db 42,MIST
    db 46,HYPNOSIS
    db 48,PSYCHIC_M
    db 52,ICE_PUNCH
    db 56,HAMMER
    db 59,HYDRO_PUMP
    db 0
SLOWPOKE_NoEvo_Learnset:
    db 42,TSUNAMI
    db 47,MIST
    db 52,HYPNOSIS
    db 55,PSYCHIC_M
    db 60,HYDRO_PUMP
    db 0
; ──────────────────────────────────────────────────────────────────────
MAGNEMITE_Learnset:
    db  1,TACKLE
    db  1,FLASH
    db  3,Skill__LIGHT
    db  6,THUNDERSHOCK
    db  8,HARDEN
    db 10,SUPERSONIC
    db 12,SONICBOOM
    db 14,LIGHT_SCREEN
    db 16,THUNDER_WAVE
    db 18,SCREECH
    db 21,THUNDERBOLT
    db 24,BLADE
    db 24,Skill__CUT
    db 26,SWIFT
    db 28,TELEPORT
    ;  30,MAGNETON
    db 0
MAGNETON_Learnset:
    db 30,TRI_ATTACK
    db 33,CONVERSION
    db 35,REFLECT
    db 37,SLAM
    db 40,DOUBLE_TEAM
    db 41,DISABLE
    db 43,SELFDESTRUCT
    db 45,BARRIER
    db 48,THUNDER_M
    db 51,RECOVER
    db 56,BODY_SLAM
    db 60,PSYBEAM
    db 0
MAGNEMITE_NoEvo_Learnset:
    db 33,DISABLE ; Exclusive
    db 36,CONVERSION
    db 40,REFLECT
    db 44,SLAM
    db 48,BARRIER
    db 53,THUNDER_M
    db 58,RECOVER
    db 0
; ──────────────────────────────────────────────────────────────────────
FARFETCH_D_Learnset:
    db  1,BLADE
    db  1,LEER
    db  3,Skill__CUT
    db  7,PECK
    db  9,WHIRLWIND
    db 11,GUST
    db 13,SHARPEN
    db 14,Skill__FLOAT
    db 15,FURY_ATTACK
    db 18,SAND_ATTACK
    db 20,QUICK_ATTACK
    db 21,Skill__FLY
    db 23,SWORDS_DANCE
    db 25,WING_ATTACK
    db 27,HEADBUTT
    db 29,SWOOP
    db 32,AGILITY
    db 35,RAZOR_WIND
    db 39,SLASH
    db 43,DOUBLE_TEAM
    db 45,MIRROR_MOVE
    db 47,DRILL_PECK
    db 49,MIMIC
    db 53,DOUBLE_EDGE
    db 56,EGG_BOMB
    db 60,SKY_ATTACK
    db 60,HAMMER
    db 0
; ──────────────────────────────────────────────────────────────────────
DODUO_Learnset:
    db  1,PECK
    db  1,LEER
    db  5,GROWL
    db  7,FURY_ATTACK
    db  9,RAGE
    db 10,WING_ATTACK
    db 13,QUICK_ATTACK
    db 16,LOW_KICK
    db 18,STOMP
    db 19,Skill__CUT
    db 21,SCREECH
    db 25,SLAM
    db 27,DOUBLE_KICK
    db 30,DRILL_PECK
    ;  31,DODRIO
    db 0
DODRIO_Learnset:
    db 31,TRI_ATTACK
    db 34,AGILITY
    db 38,ROLLING_KICK
    db 42,HAZE
    db 45,DOUBLE_TEAM
    db 47,JUMP_KICK
    db 49,DOUBLE_EDGE
    db 52,EGG_BOMB
    db 55,BODY_SLAM
    db 60,HI_JUMP_KICK
    db 0
DODUO_NoEvo_Learnset:
    db 35,AGILITY
    db 39,ROLLING_KICK
    db 43,HAZE
    db 47,DOUBLE_TEAM
    db 51,JUMP_KICK
    db 55,DOUBLE_EDGE
    db 59,EGG_BOMB
    db 0
; ──────────────────────────────────────────────────────────────────────
SEEL_Learnset:
    db  1,HEADBUTT
    db  1,GROWL
    db  6,LICK
    db  9,BUBBLE
    db 11,TAIL_WHIP
    db 13,WATER_GUN
    db 13,Skill__FLOAT
    db 15,DISABLE
    db 17,AURORA_BEAM
    db 19,TAKE_DOWN
    db 21,BUBBLEBEAM
    db 23,SKULL_BASH
    db 26,WATERFALL
    db 28,DEFENSE_CURL
    db 29,AMNESIA
    db 30,REST
    db 31,ICE_PUNCH
    db 33,MIST
    ;  34,DEWGONG
    db 0
DEWGONG_Learnset:
    db 34,HORN_ATTACK
    db 34,FURY_ATTACK
    db 36,TSUNAMI
    db 38,BODY_SLAM
    db 40,HAZE
    db 42,ICE_BEAM
    db 44,SCREECH
    db 46,HYDRO_PUMP
    db 50,HORN_DRILL
    db 55,BLIZZARD
    db 60,SUBSTITUTE
    db 0
SEEL_NoEvo_Learnset:
    db 38,SCREECH ; Exclusive
    db 42,TSUNAMI
    db 45,BODY_SLAM
    db 48,HAZE
    db 51,ICE_BEAM
    db 56,HYDRO_PUMP
    db 60,BLIZZARD
    db 0
; ──────────────────────────────────────────────────────────────────────
GRIMER_Learnset:
    db  1,POUND
    db  1,POISON_GAS
    db  7,DEFENSE_CURL
    db  9,ACID
    db 11,DOUBLESLAP
    db 13,LICK
    db 15,STRING_SHOT
    db 17,SMOG
    db 19,DISABLE
    db 21,SLUDGE
    db 23,FOCUS_ENERGY
    db 25,MINIMIZE
    db 27,HARDEN
    db 30,SLAM
    db 32,ROCK_THROW
    db 34,HAZE
    db 35,SCREECH
    ;  38,MUK
    db 0
MUK_Learnset:
    db 38,ACID_ARMOR
    db 38,Skill__FLOAT
    db 41,SWIFT
    db 43,LEECH_LIFE
    db 44,THUNDERPUNCH
    db 46,ABSORB
    db 48,MEGA_DRAIN
    db 51,TOXIC
    db 54,RECOVER
    db 57,BODY_SLAM
    db 57,Skill__STRENGTH
    db 60,SUBSTITUTE
    db 0
GRIMER_NoEvo_Learnset:
    db 39,LEECH_LIFE ; Exclusive
    db 42,ACID_ARMOR
    db 42,Skill__FLOAT
    db 45,THUNDERPUNCH
    db 47,ABSORB
    db 49,MEGA_DRAIN
    db 53,TOXIC
    db 57,RECOVER
    db 60,SUBSTITUTE
    db 0
; ──────────────────────────────────────────────────────────────────────
SHELLDER_Learnset:
    db  1,TACKLE
    db  1,WITHDRAW
    db  6,BUBBLE
    db 10,LICK
    db 12,SONICBOOM
    db 14,SUPERSONIC
    db 18,CLAMP
    db 20,LEER
    db 22,WATER_GUN
    db 26,SCREECH
    db 30,AURORA_BEAM
    db 32,BUBBLEBEAM ; Exclusive
    db 34,LOVELY_KISS ; Exclusive
    db 36,BIDE
    db 40,HAZE
    db 44,WATERFALL
    db 48,ICE_BEAM
    db 52,SELFDESTRUCT
    db 0
CLOYSTER_Learnset:
    db  1,TACKLE
    db  1,WITHDRAW
    db  1,SPIKE_CANNON
    db  5,BUBBLE
    db  7,LICK
    db  9,SONICBOOM
    db 11,SUPERSONIC
    db 13,CLAMP
    db 16,AURORA_BEAM
    db 19,LEER
    db 21,WATER_GUN
    db 21,Skill__FLOAT
    db 23,MIST
    db 25,SCREECH
    db 27,WATERFALL
    db 31,BARRIER
    db 33,HAZE
    db 35,BIDE
    db 37,SELFDESTRUCT
    db 39,BUBBLEBEAM
    db 41,ICE_BEAM
    db 45,TSUNAMI
    db 49,HYDRO_PUMP
    db 53,BLIZZARD
    db 57,EXPLOSION
    db 58,LOVELY_KISS
    db 60,HAMMER
    db 0
; ──────────────────────────────────────────────────────────────────────
GASTLY_Learnset:
    db  1,LICK
    db  1,CONFUSE_RAY
    db  5,DISABLE
    db  7,LEECH_LIFE
    db  7,POISONPOWDER
    db  9,STRING_SHOT
    db 11,SONICBOOM
    db 13,POISON_GAS
    db 15,PSYWAVE
    db 17,NIGHT_SHADE
    db 19,SMOKESCREEN
    db 21,SMOG
    db 23,HYPNOSIS
    db 24,DREAM_EATER
    db 25,TELEPORT
    ;  25,HAUNTER
    db 0
HAUNTER_Learnset:
    db 25,CONFUSION
    db 28,ACID
    db 0
GENGAR_Learnset:
    db 25,CONFUSION
    db 25,ACID
    db 0
HAUNTER_GENGAR_Learnset:
    db 30,MIST
    db 32,SCREECH
    db 33,ABSORB
    db 34,MEGA_DRAIN
    db 36,REFLECT
    db 38,THUNDERPUNCH
    db 40,PSYBEAM
    db 42,SLUDGE
    db 44,HAZE
    db 46,PSYCHIC_M
    db 48,AMNESIA
    db 49,TRANSFORM
    db 52,TOXIC
    db 55,ACID_ARMOR
    db 60,SUBSTITUTE
    db 65,HYPER_BEAM
    db 0
GASTLY_NoEvo_Learnset:
    db 27,ABSORB ; Exclusive
    db 29,AMNESIA ; Exclusive
    db 32,CONFUSION
    db 35,MIST
    db 39,REFLECT
    db 43,PSYBEAM
    db 48,HAZE
    db 50,SLUDGE
    db 53,PSYCHIC_M
    db 55,TRANSFORM
    db 60,SUBSTITUTE
    db 0
; ──────────────────────────────────────────────────────────────────────
ONIX_Learnset:
    db  1,TACKLE
    db  1,SCREECH
    db  4,Skill__DIG
    db  5,CONSTRICT
    db  8,BIDE
    db  8,RAGE
    db 12,ROCK_THROW
    db 12,Skill__STRENGTH
    db 14,WRAP
    db 16,SLAM
    db 17,SAND_ATTACK
    db 19,BLADE
    db 19,Skill__CUT
    db 21,SHARPEN
    db 23,TRAPHOLE
    db 26,HARDEN
    db 29,ROCK_SLIDE
    db 31,STRIKE
    db 34,BODY_SLAM
    db 36,SELFDESTRUCT
    db 39,THRASH
    db 42,DRAGON_RAGE
    db 46,EARTHQUAKE
    db 50,EXPLOSION
    db 55,SUBSTITUTE
    db 58,SWORDS_DANCE
    db 60,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
ONIX_Crystal_Learnset:
    db  1,TACKLE
    db  1,SCREECH
    db  4,Skill__DIG
    db  5,CONSTRICT
    db  8,BIDE
    db  8,RAGE
    db 12,ROCK_THROW
    db 12,Skill__STRENGTH
    db 14,WRAP
    db 16,SLAM
    db 17,SAND_ATTACK
    db 19,BLADE
    db 19,Skill__CUT
    db 21,SHARPEN
    db 23,TRAPHOLE
    db 26,HARDEN
    db 29,ROCK_SLIDE
    db 31,STRIKE
    db 33,Skill__FLOAT
    db 34,BODY_SLAM
    db 36,SELFDESTRUCT
    db 39,THRASH
    db 42,DRAGON_RAGE
    db 46,EARTHQUAKE
    db 50,EXPLOSION
    db 55,SUBSTITUTE
    db 58,SWORDS_DANCE
    db 60,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
DROWZEE_Learnset:
    db  1,POUND
    db  1,DISABLE
    db  6,TELEPORT
    db  9,PSYWAVE
    db 13,HYPNOSIS
    db 14,DREAM_EATER
    db 17,CONFUSION
    db 20,HEADBUTT
    db 23,CONFUSE_RAY
    db 26,MEDITATE
    ;  26,HYPNO
    db 0
HYPNO_Learnset:
    db 26,PSYBEAM
    db 28,SWIFT
    db 30,KINESIS
    db 32,POISON_GAS
    db 35,REFLECT
    db 38,PSYCHIC_M
    db 40,FLARE
    db 42,LIGHT_SCREEN
    db 45,REST
    db 49,NIGHT_SHADE
    db 52,BARRIER
    db 55,HAZE
    db 58,RECOVER
    db 60,HYPER_BEAM
    db 0
DROWZEE_NoEvo_Learnset:
    db 31,PSYBEAM
    db 34,SWIFT
    db 36,KINESIS
    db 37,POISON_GAS
    db 41,REFLECT
    db 45,PSYCHIC_M
    db 49,LIGHT_SCREEN
    db 55,REST
    db 57,BARRIER
    db 59,NIGHT_SHADE
    db 0
; ──────────────────────────────────────────────────────────────────────
KRABBY_Learnset:
    db  1,BUBBLE
    db  1,LEER
    db  6,VICEGRIP
    db  8,SPLASH
    db  9,BLADE
    db  9,Skill__CUT
    db 11,WATER_GUN
    db 13,CLAMP
    db 15,SAND_ATTACK
    db 18,BUBBLEBEAM
    db 20,STOMP
    db 21,LEECH_LIFE
    db 22,BONE_CLUB
    db 24,HARDEN
    db 25,SHARPEN
    db 27,STRIKE
    ;  28,KINGLER
    db 0
KINGLER_Learnset:
    db 28,HAMMER
    db 28,Skill__DIG
    db 30,FOCUS_ENERGY
    db 32,WATERFALL
    db 32,Skill__FLOAT
    db 34,SPIKE_CANNON
    db 36,ROCK_THROW
    db 36,Skill__STRENGTH
    db 38,TRAPHOLE
    db 40,GUILLOTINE
    db 44,HAZE
    db 47,TSUNAMI
    db 49,BODY_SLAM
    db 52,SWORDS_DANCE
    db 56,ROCK_SLIDE
    db 60,HYDRO_PUMP
    db 0
KRABBY_NoEvo_Learnset:
    db 32,HAMMER
    db 32,Skill__DIG
    db 35,WATERFALL
    db 35,Skill__FLOAT
    db 38,SPIKE_CANNON
    db 42,ROCK_THROW
    db 42,Skill__STRENGTH
    db 46,TRAPHOLE
    db 51,GUILLOTINE
    db 56,HAZE
    db 60,SWORDS_DANCE
    db 0
; ──────────────────────────────────────────────────────────────────────
VOLTORB_Learnset:
    db  1,TACKLE
    db  1,SCREECH
    db  6,FLASH
    db  8,DEFENSE_CURL
    db  9,Skill__LIGHT
    db 10,SONICBOOM
    db 12,LIGHT_SCREEN
    db 14,SUPERSONIC
    db 16,THUNDERSHOCK
    db 17,SELFDESTRUCT
    db 20,QUICK_ATTACK
    db 24,THUNDER_WAVE
    db 26,SLAM
    db 28,SWIFT
    ;  30,ELECTRODE
    db 0
ELECTRODE_Learnset:
    db 30,EXPLOSION
    db 33,THUNDERBOLT
    db 35,AGILITY
    db 37,DOUBLE_TEAM
    db 40,BODY_SLAM
    db 41,DISABLE
    db 43,CONVERSION
    db 45,REFLECT
    db 48,TELEPORT
    db 51,THUNDER_M
    db 56,RECOVER
    db 60,PSYBEAM
    db 0
VOLTORB_NoEvo_Learnset:
    db 33,DISABLE ; Exclusive
    db 36,EXPLOSION
    db 40,THUNDERBOLT
    db 44,AGILITY
    db 48,DOUBLE_TEAM
    db 53,REFLECT
    db 58,THUNDER_M
    db 0
; ──────────────────────────────────────────────────────────────────────
VOLTORB_HISUI_Learnset:
    db  1,TACKLE
    db  1,GROWTH
    db  7,LEECH_SEED
    db 10,FLASH
    db 12,STUN_SPORE
    db 12,Skill__LIGHT
    db 14,ABSORB
    db 16,THUNDERSHOCK
    db 17,SELFDESTRUCT
    db 20,QUICK_ATTACK
    db 24,SLEEP_POWDER
    db 26,MEGA_DRAIN
    db 28,SWIFT
    db 33,DISABLE ; Exclusive
    db 36,EXPLOSION
    db 40,THUNDERBOLT
    db 44,AGILITY
    db 48,DOUBLE_TEAM
    db 53,LIGHT_SCREEN
    db 58,SOLARBEAM
    db 0
ELECTRODE_HISUI_Learnset:
    db  1,TACKLE
    db  1,GROWTH
    db  6,LEECH_SEED
    db  9,FLASH
    db 11,STUN_SPORE
    db 11,Skill__LIGHT
    db 13,ABSORB
    db 15,THUNDERSHOCK
    db 16,SELFDESTRUCT
    db 18,QUICK_ATTACK
    db 21,SLEEP_POWDER
    db 24,MEGA_DRAIN
    db 25,Skill__HEAL
    db 27,SWIFT
    db 30,EXPLOSION
    db 33,THUNDERBOLT
    db 35,AGILITY
    db 37,DOUBLE_TEAM
    db 40,BARRAGE
    db 41,DISABLE
    db 43,CONVERSION
    db 45,LIGHT_SCREEN
    db 48,TELEPORT
    db 51,SOLARBEAM
    db 56,RECOVER
    db 60,THUNDER_M
    db 0
; ──────────────────────────────────────────────────────────────────────
EXEGGCUTE_Learnset:
    db  1,BARRAGE
    db  1,HYPNOSIS
    db  7,PSYWAVE
    db 10,REFLECT
    db 13,TELEPORT
    db 16,CONFUSION
    db 19,LEECH_SEED
    db 22,SLAM
    db 25,ABSORB
    db 27,STUN_SPORE ; Exclusive
    db 29,POISONPOWDER ; Exclusive
    db 31,SLEEP_POWDER ; Exclusive
    db 32,Skill__HEAL
    db 33,LEECH_LIFE
    db 35,EGG_BOMB
    db 37,STRING_SHOT
    db 37,KINESIS
    db 39,PSYBEAM
    db 42,SELFDESTRUCT
    db 46,MEGA_DRAIN
    db 48,BARRIER
    db 50,SOLARBEAM
    db 55,PSYCHIC_M
    db 60,DREAM_EATER
    db 0
EXEGGUTOR_Learnset:
    db  1,Skill__HEAL
    db  1,BARRAGE
    db  1,HYPNOSIS
    db  1,STOMP
    db  7,PSYWAVE
    db  9,REFLECT
    db 10,TELEPORT
    db 13,CONFUSION
    db 15,LEECH_SEED
    db 17,SLAM
    db 20,ABSORB
    db 23,EGG_BOMB
    db 25,STRING_SHOT
    db 26,KINESIS
    db 26,Skill__HEAL
    db 27,GROWTH
    db 29,LEECH_LIFE
    db 32,PSYBEAM
    db 35,SELFDESTRUCT
    db 37,MEGA_DRAIN
    db 39,RAZOR_LEAF
    db 40,BARRIER
    db 40,STUN_SPORE
    db 42,SOLARBEAM
    db 44,PSYCHIC_M
    db 49,POISONPOWDER
    db 52,EXPLOSION
    db 56,BODY_SLAM
    db 60,SLEEP_POWDER
    db 60,DREAM_EATER
    db 0
; ──────────────────────────────────────────────────────────────────────
CUBONE_Learnset:
    db  1,TACKLE
    db  1,GROWL
    db  5,TAIL_WHIP
    db  7,BONE_CLUB
    db  7,Skill__DIG
    db  8,SAND_ATTACK
    db 10,TRAPHOLE
    db 12,RAGE
    db 13,LEER
    db 15,WITHDRAW
    db 17,SKULL_BASH
    db 19,FOCUS_ENERGY
    db 21,HEADBUTT
    db 23,BLADE
    db 23,Skill__CUT
    db 25,BONEMERANG
    db 27,REST
    ;  28,MAROWAK
    db 0
MAROWAK_Learnset:
    db 28,NIGHT_SHADE
    db 28,Skill__STRENGTH
    db 32,ROCK_THROW
    db 35,EARTHQUAKE
    db 37,MEDITATE
    db 39,STRIKE
    db 42,THRASH
    db 44,SPIKE_CANNON
    db 47,DIZZY_PUNCH
    db 50,ROCK_SLIDE
    db 55,SWORDS_DANCE
    db 57,FISSURE
    db 60,HAMMER
    db 65,HYPER_BEAM
    db 0
MAROWAK_Alola_Learnset:
    db 28,EMBER
    db 28,FLASH
    db 28,CONFUSE_RAY
    db 28,TELEPORT
    db 28,NIGHT_SHADE
    db 28,Skill__LIGHT
    db 32,FIRE_PUNCH
    db 33,SCREECH
    db 35,HAZE
    db 37,MEDITATE
    db 39,STRIKE
    db 39,FLAMETHROWER
    db 40,ROCK_THROW
    db 42,THRASH
    db 44,FIRE_SPIN
    db 47,DIZZY_PUNCH
    db 48,EARTHQUAKE
    db 50,SUBSTITUTE
    db 55,SWORDS_DANCE
    db 57,FIRE_BLAST
    db 60,HAMMER
    db 61,ROCK_SLIDE
    db 62,SPIKE_CANNON
    db 65,HYPER_BEAM
    db 65,FISSURE
    db 0
CUBONE_NoEvo_Learnset:
    db 30,MEDITATE ; Exclusive
    db 34,ROCK_THROW ; Exclusive (Alola)
    db 38,EARTHQUAKE ; Exclusive (Alola)
    db 42,STRIKE
    db 46,THRASH
    db 49,SPIKE_CANNON ; Exclusive (Alola)
    db 53,ROCK_SLIDE ; Exclusive (Alola)
    db 58,SWORDS_DANCE
    db 60,FISSURE ; Exclusive (Alola)
    db 0
; ──────────────────────────────────────────────────────────────────────
HITMONLEE_Learnset:
    db  1,LOW_KICK
    db  1,MEDITATE
    db  6,DOUBLE_KICK
    db  9,FOCUS_ENERGY
    db  9,Skill__STRENGTH
    db 11,ROLLING_KICK
    db 13,KARATE_CHOP
    db 15,AGILITY
    db 16,QUICK_ATTACK
    db 17,JUMP_KICK
    db 19,BIDE
    db 21,STRIKE
    db 23,DOUBLE_TEAM
    db 26,MEGA_KICK
    db 27,COMET_PUNCH
    db 28,TRAPHOLE
    db 29,SLAM
    db 30,ROCK_THROW
    db 32,MEGA_PUNCH
    db 35,SKULL_BASH
    db 37,SUBMISSION
    db 39,HI_JUMP_KICK
    db 42,SEISMIC_TOSS
    db 44,Skill__FLOAT
    db 47,REST
    db 49,ROCK_SLIDE
    db 52,COUNTER
    db 57,BODY_SLAM
    db 60,EARTHQUAKE
    db 60,RAZOR_LEAF
    db 0
; ──────────────────────────────────────────────────────────────────────
HITMONCHAN_Learnset:
    db  1,KARATE_CHOP
    db  1,AGILITY
    db  6,COMET_PUNCH
    db  9,FOCUS_ENERGY
    db  9,Skill__STRENGTH
    db 11,BIDE
    db 13,LOW_KICK
    db 15,MEDITATE
    db 16,QUICK_ATTACK
    db 17,MEGA_PUNCH
    db 19,DOUBLE_KICK
    db 21,STRIKE
    db 23,DOUBLE_TEAM
    db 26,FIRE_PUNCH
    db 27,ICE_PUNCH
    db 28,THUNDERPUNCH
    db 29,SLAM
    db 30,ROCK_THROW
    db 32,ROLLING_KICK
    db 35,SKULL_BASH
    db 37,SUBMISSION
    db 39,JUMP_KICK
    db 42,SEISMIC_TOSS
    db 44,Skill__FLOAT
    db 47,ROCK_SLIDE
    db 49,MEGA_KICK
    db 52,COUNTER
    db 57,BODY_SLAM
    db 60,EARTHQUAKE
    db 60,HI_JUMP_KICK
    db 0
; ──────────────────────────────────────────────────────────────────────
LICKITUNG_Learnset:
    db  1,LICK
    db  1,STRING_SHOT
    db  5,SUPERSONIC
    db  7,DEFENSE_CURL
    db  9,POUND
    db 11,DISABLE
    db 13,DOUBLESLAP
    db 15,STOMP
    db 18,SLAM
    db 21,WRAP
    db 23,SONICBOOM
    db 25,STRIKE
    db 25,Skill__CUT
    db 26,LEECH_LIFE
    db 28,SCREECH
    db 31,REST
    db 34,BODY_SLAM
    db 34,Skill__FLOAT
    db 37,TSUNAMI
    db 40,MINIMIZE
    db 42,DOUBLE_EDGE
    db 44,SOFTBOILED
    db 44,Skill__HEAL
    db 46,Skill__STRENGTH
    db 47,EARTHQUAKE
    db 49,LIGHT_SCREEN
    db 51,LOVELY_KISS
    db 55,SWORDS_DANCE
    db 60,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
KOFFING_Learnset:
    db  1,TACKLE
    db  1,POISON_GAS
    db  9,SMOG
    db 11,ACID
    db 13,SMOKESCREEN
    db 15,SCREECH
    db 17,DEFENSE_CURL
    db 19,SELFDESTRUCT
    db 21,SLUDGE
    db 23,FOCUS_ENERGY
    db 23,Skill__FLOAT
    db 25,SONICBOOM
    db 27,THUNDERSHOCK
    db 27,Skill__LIGHT
    db 30,HARDEN
    db 32,SUPERSONIC
    db 34,HAZE
    ;  35,WEEZING
    db 0
WEEZING_Learnset:
    db 35,EXPLOSION
    db 38,FLARE
    db 41,SWIFT
    db 42,Skill__FLY
    db 43,ABSORB
    db 44,PSYBEAM
    db 46,DISABLE
    db 48,THUNDERBOLT
    db 51,TOXIC
    db 54,RECOVER
    db 57,FLAMETHROWER
    db 60,SUBSTITUTE
    db 0
KOFFING_NoEvo_Learnset:
    db 39,ABSORB ; Exclusive
    db 42,EXPLOSION
    db 45,FLARE
    db 47,DISABLE
    db 49,THUNDERBOLT
    db 53,TOXIC
    db 57,RECOVER
    db 60,SUBSTITUTE
    db 0
; ──────────────────────────────────────────────────────────────────────
RHYHORN_Learnset:
    db  1,HORN_ATTACK
    db  1,TAIL_WHIP
    db  5,GROWL
    db  8,HARDEN
    db 10,SAND_ATTACK
    db 11,FURY_ATTACK
    db 11,Skill__CUT
    db 13,ROCK_THROW
    db 13,Skill__STRENGTH
    db 15,BONE_CLUB
    db 17,FOCUS_ENERGY
    db 17,RAGE
    db 18,STOMP
    db 18,Skill__DIG
    db 20,LEER
    db 22,TRAPHOLE
    db 24,SLAM
    db 26,STRIKE
    db 28,TAKE_DOWN
    db 30,BODY_SLAM
    db 32,ROCK_SLIDE
    db 34,SKULL_BASH
    db 36,REST
    db 38,THRASH
    db 40,EARTHQUAKE
    db 42,HORN_DRILL
    ;  42,RHYDON
    db 0
RHYDON_Learnset:
    db 42,MEGA_PUNCH
    db 42,HEADBUTT
    db 42,DIZZY_PUNCH
    db 45,SHARPEN
    db 45,Skill__FLOAT
    db 49,FISSURE
    db 52,SEISMIC_TOSS
    db 54,HYPER_BEAM
    db 55,DOUBLE_KICK
    db 57,SWORDS_DANCE
    db 60,SUBSTITUTE
    db 0
RHYHORN_NoEvo_Learnset:
    db 47,DOUBLE_KICK ; Exclusive
    db 50,SHARPEN
    db 53,FISSURE
    db 57,HYPER_BEAM
    db 59,SWORDS_DANCE
    db 60,SUBSTITUTE
    db 0
; ──────────────────────────────────────────────────────────────────────
CHANSEY_Learnset:
    db  1,POUND
    db  1,TAIL_WHIP
    db  5,GROWL
    db  8,SOFTBOILED
    db  8,Skill__HEAL
    db 12,DEFENSE_CURL
    db 14,BIDE
    db 16,DOUBLESLAP
    db 18,DISABLE
    db 20,MINIMIZE
    db 20,Skill__FLOAT
    db 23,SING
    db 25,SLAM
    db 27,COUNTER
    db 30,LIGHT_SCREEN
    db 32,REFLECT
    db 35,EGG_BOMB
    db 37,LOVELY_KISS
    db 40,METRONOME
    db 43,REST
    db 46,DOUBLE_EDGE
    db 50,BODY_SLAM
    db 55,BARRIER
    db 60,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
TANGELA_Learnset:
    db  1,CONSTRICT
    db  1,SLEEP_POWDER
    db  8,VINE_WHIP
    db 10,BIND
    db 12,LEECH_SEED
    db 14,ABSORB
    db 16,POISONPOWDER
    db 17,STUN_SPORE
    db 17,Skill__HEAL
    db 19,BLADE
    db 19,Skill__CUT
    db 21,GROWTH
    db 23,LEECH_LIFE
    db 25,MEGA_DRAIN
    db 27,SLAM
    db 29,STRING_SHOT
    db 31,BARRAGE
    db 33,CONFUSION
    db 35,RAZOR_LEAF
    db 36,SPORE
    db 37,HAZE
    db 39,AMNESIA
    db 40,SOLARBEAM
    db 44,PSYBEAM
    db 48,BODY_SLAM
    db 51,SWORDS_DANCE
    db 55,RECOVER
    db 60,TOXIC
    db 0
; ──────────────────────────────────────────────────────────────────────
KANGASKHAN_Learnset:
    db  1,SCRATCH
    db  1,TAIL_WHIP
    db  7,COMET_PUNCH
    db  9,SUBSTITUTE
    db 11,LEER
    db 13,FURY_SWIPES
    db 15,FOCUS_ENERGY
    db 17,LOW_KICK
    db 18,RAGE
    db 19,BONE_CLUB
    db 21,REST
    db 23,BITE
    db 25,ROCK_THROW
    db 25,Skill__STRENGTH
    db 27,STOMP
    db 29,MEGA_PUNCH
    db 31,SLAM
    db 33,HEADBUTT
    db 35,DIZZY_PUNCH
    db 37,STRIKE
    db 39,THRASH
    db 41,SKULL_BASH
    db 43,SLASH
    db 25,Skill__CUT
    db 45,TAKE_DOWN
    db 47,BODY_SLAM
    db 47,Skill__FLOAT
    db 49,DOUBLE_EDGE
    db 52,ROCK_SLIDE
    db 56,EARTHQUAKE
    db 60,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
HORSEA_Learnset:
    db  1,BUBBLE
    db  1,SMOKESCREEN
    db  8,LEER
    db 11,DISABLE
    db 13,SMOG
    db 15,WATER_GUN
    db 15,Skill__FLOAT
    db 17,MIST
    db 19,LEECH_LIFE
    db 21,SCREECH
    db 22,SONICBOOM
    db 23,BUBBLEBEAM
    db 25,AGILITY
    db 27,SLAM
    db 29,WATERFALL
    db 31,SAND_ATTACK
    ;  32,SEADRA
    db 0
SEADRA_Learnset:
    db 32,DRAGON_RAGE
    db 32,SUPERSONIC
    db 34,CONFUSION
    db 36,HAZE
    db 36,Skill__HEAL
    db 37,AURORA_BEAM
    db 39,POISON_GAS
    db 41,RAZOR_WIND
    db 41,Skill__CUT
    db 43,TSUNAMI
    db 47,ICE_BEAM
    db 49,STRING_SHOT
    db 51,HYDRO_PUMP
    db 53,DOUBLE_TEAM
    db 56,HYPER_BEAM
    db 60,TOXIC
    db 0
HORSEA_NoEvo_Learnset:
    db 36,DOUBLE_TEAM ; Exclusive
    db 39,SUPERSONIC
    db 42,HAZE
    db 46,AURORA_BEAM
    db 50,POISON_GAS
    db 55,TSUNAMI
    db 57,STRING_SHOT
    db 60,HYDRO_PUMP
    db 0
; ──────────────────────────────────────────────────────────────────────
GOLDEEN_Learnset:
    db  1,SPLASH
    db  1,TAIL_WHIP
    db  7,PECK
    db  9,BUBBLE
    db 11,SUPERSONIC
    db 13,POISON_STING
    db 15,HORN_ATTACK
    db 18,WATERFALL
    db 18,Skill__FLOAT
    db 20,AGILITY
    db 23,WATER_GUN
    db 26,FURY_ATTACK
    db 28,SONICBOOM
    db 29,BUBBLEBEAM
    db 31,REST
    ;  33,SEAKING
    db 0
SEAKING_Learnset:
    db 33,HORN_DRILL
    db 35,HAZE
    db 38,SCREECH
    db 40,PSYBEAM
    db 43,TSUNAMI
    db 48,LOVELY_KISS
    db 51,TOXIC
    db 53,BODY_SLAM
    db 55,HYDRO_PUMP
    db 58,SWORDS_DANCE
    db 60,DRILL_PECK
    db 0
GOLDEEN_NoEvo_Learnset:
    db 36,LOVELY_KISS ; Exclusive
    db 41,HAZE
    db 46,SCREECH
    db 51,TSUNAMI
    db 56,TOXIC
    db 60,HYDRO_PUMP
    db 0
; ──────────────────────────────────────────────────────────────────────
STARYU_Learnset:
    db  1,TACKLE
    db  1,HARDEN
    db  7,BUBBLE
    db  9,PSYWAVE
    db 11,AGILITY
    db 13,WATER_GUN
    db 16,MINIMIZE
    db 19,CONFUSION
    db 21,CONVERSION
    db 22,TELEPORT
    db 23,RECOVER
    db 25,FLASH
    db 25,Skill__LIGHT
    db 27,SUPERSONIC ; Exclusive
    db 29,QUICK_ATTACK
    db 32,SWIFT
    db 34,BUBBLEBEAM
    db 36,PSYBEAM
    db 38,SONICBOOM
    db 40,REFLECT
    db 43,FLARE
    db 46,SCREECH
    db 46,KINESIS
    db 49,LIGHT_SCREEN
    db 53,PSYCHIC_M
    db 58,BARRIER
    db 0
STARMIE_Learnset:
    db  1,TACKLE
    db  1,HARDEN
    db  1,BUBBLE
    db  1,PSYWAVE
    db  7,AGILITY
    db 10,WATER_GUN
    db 11,TELEPORT
    db 12,MINIMIZE
    db 14,CONFUSION
    db 16,CONVERSION
    db 18,RECOVER
    db 21,BUBBLEBEAM
    db 23,FLASH
    db 23,Skill__LIGHT
    db 25,LEECH_LIFE
    db 26,SWIFT
    db 27,QUICK_ATTACK
    db 28,PSYBEAM
    db 29,KINESIS
    db 30,SONICBOOM
    db 32,REFLECT
    db 34,FLARE
    db 35,SUPERSONIC
    db 35,CONFUSE_RAY
    db 36,SCREECH
    db 38,WATERFALL
    db 38,Skill__FLOAT
    db 40,AURORA_BEAM
    db 42,LIGHT_SCREEN
    db 44,HYPNOSIS
    db 46,PSYCHIC_M
    db 49,TSUNAMI
    db 53,BARRIER
    db 58,HYDRO_PUMP
    db 0
; ──────────────────────────────────────────────────────────────────────
MR_MIME_Learnset:
    db  1,POUND
    db  1,BARRIER
    db  6,PSYWAVE
    db  9,SUBSTITUTE
    db 11,TELEPORT
    db 13,CONFUSION
    db 15,DOUBLESLAP
    db 17,KINESIS
    db 17,Skill__LIGHT
    db 19,DISABLE
    db 21,MEDITATE
    db 23,MIMIC
    db 24,LIGHT_SCREEN
    db 26,HEADBUTT
    db 28,CONFUSE_RAY
    db 30,SLAM
    db 32,PSYBEAM
    db 34,REST
    db 36,FLARE
    db 39,REFLECT
    db 42,PSYCHIC_M
    db 45,MIRROR_MOVE
    db 48,SEISMIC_TOSS
    db 50,HYPNOSIS
    db 55,DOUBLE_TEAM
    db 58,DREAM_EATER
    db 60,RECOVER
    db 0
; ──────────────────────────────────────────────────────────────────────
SCYTHER_Learnset:
    db  1,SCRATCH
    db  1,LEER
    db  7,AGILITY
    db  9,QUICK_ATTACK
    db 11,STRING_SHOT
    db 13,GUST
    db 15,FURY_SWIPES
    db 15,Skill__CUT
    db 16,RAGE
    db 17,PIN_MISSILE
    db 18,SAND_ATTACK
    db 19,BLADE
    db 20,SHARPEN
    db 21,DOUBLE_TEAM
    db 22,Skill__FLY
    db 23,WING_ATTACK
    db 25,LEECH_LIFE
    db 26,CONFUSE_RAY
    db 27,SLASH
    db 29,RAZOR_WIND
    db 29,ABSORB
    db 31,FOCUS_ENERGY
    db 31,TRAPHOLE
    db 33,SWORDS_DANCE
    db 34,CLAMP
    db 35,WHIRLWIND
    db 37,SWOOP
    db 37,MIRROR_MOVE
    db 39,TWINEEDLE
    db 42,MIMIC
    db 44,RAZOR_LEAF
    db 46,MEGA_DRAIN
    db 47,SPIKE_CANNON
    db 49,LIGHT_SCREEN
    db 52,JUMP_KICK
    db 55,GUILLOTINE
    db 60,SKY_ATTACK
    db 0
; ──────────────────────────────────────────────────────────────────────
JYNX_Learnset:
    db  1,POUND
    db  1,SING
    db  5,LICK
    db  8,DOUBLESLAP
    db 10,PSYWAVE
    db 12,AURORA_BEAM
    db 13,TELEPORT
    db 14,CONFUSION
    db 16,BARRIER
    db 17,LOVELY_KISS
    db 18,MIST
    db 20,ICE_PUNCH
    db 21,SLAM
    db 22,DISABLE
    db 24,KARATE_CHOP
    db 25,SWIFT
    db 26,KINESIS
    db 27,MEDITATE
    db 29,REFLECT
    db 31,LIGHT_SCREEN
    db 33,LEECH_LIFE
    db 34,ICE_BEAM
    db 36,PSYBEAM
    db 38,BODY_SLAM
    db 40,CONFUSE_RAY
    db 43,HAZE
    db 46,PSYCHIC_M
    db 48,THRASH
    db 50,BLIZZARD
    db 52,NIGHT_SHADE
    db 55,DREAM_EATER
    db 58,RECOVER
    db 60,SUBSTITUTE
    db 0
; ──────────────────────────────────────────────────────────────────────
ELECTABUZZ_Learnset:
    db  1,KARATE_CHOP
    db  1,LEER
    db  5,FLASH
    db  5,Skill__LIGHT
    db  8,THUNDERSHOCK
    db 10,QUICK_ATTACK
    db 12,THUNDER_WAVE
    db 13,COMET_PUNCH
    db 14,LOW_KICK
    db 16,LIGHT_SCREEN
    db 17,DOUBLE_KICK
    db 18,DOUBLE_TEAM
    db 20,THUNDERPUNCH
    db 21,FOCUS_ENERGY
    db 22,SCREECH
    db 24,SWIFT
    db 25,MEGA_PUNCH
    db 26,RAGE
    db 27,MEDITATE
    db 29,STRIKE
    db 31,REFLECT
    db 33,ROLLING_KICK
    db 34,THUNDERBOLT
    db 36,SEISMIC_TOSS
    db 38,BODY_SLAM
    db 40,AGILITY
    db 43,SUBMISSION
    db 46,JUMP_KICK
    db 48,THRASH
    db 50,THUNDER_M
    db 52,MEGA_KICK
    db 55,COUNTER
    db 58,BARRIER
    db 60,HI_JUMP_KICK
    db 0
; ──────────────────────────────────────────────────────────────────────
MAGMAR_Learnset:
    db  1,SCRATCH
    db  1,LEER
    db  5,SMOG
    db  8,EMBER
    db  8,Skill__LIGHT
    db 10,SMOKESCREEN
    db 12,PECK
    db 13,RAGE
    db 14,ACID
    db 16,POISON_GAS
    db 17,ROCK_THROW
    db 18,REFLECT
    db 20,FIRE_PUNCH
    db 21,SLAM
    db 22,KARATE_CHOP
    db 24,FIRE_SPIN
    db 25,FOCUS_ENERGY
    db 26,SWIFT
    db 27,MEDITATE
    db 29,MEGA_PUNCH
    db 31,LIGHT_SCREEN
    db 33,SCREECH
    db 34,FLAMETHROWER
    db 36,STRIKE
    db 38,BODY_SLAM
    db 40,CONFUSE_RAY
    db 43,MIRROR_MOVE
    db 46,SLUDGE
    db 48,THRASH
    db 50,FIRE_BLAST
    db 52,ROCK_SLIDE
    db 55,TOXIC
    db 58,ACID_ARMOR
    db 60,DRILL_PECK
    db 0
; ──────────────────────────────────────────────────────────────────────
PINSIR_Learnset:
    db  1,BLADE
    db  1,FOCUS_ENERGY
    db  3,Skill__CUT
    db  7,VICEGRIP
    db  9,HARDEN
    db 11,STRING_SHOT
    db 13,FURY_ATTACK
    db 15,LEER
    db 16,RAGE
    db 17,LEECH_LIFE
    db 18,KARATE_CHOP
    db 19,BONE_CLUB
    db 19,Skill__DIG
    db 20,COMET_PUNCH
    db 21,CLAMP
    db 23,SHARPEN
    db 23,Skill__STRENGTH
    db 25,SEISMIC_TOSS
    db 26,LOW_KICK
    db 27,DOUBLE_KICK
    db 29,PIN_MISSILE
    db 29,MEGA_PUNCH
    db 31,GUILLOTINE
    db 31,ROLLING_KICK
    db 33,TRAPHOLE
    db 34,STRIKE
    db 35,SLASH
    db 37,SPIKE_CANNON
    db 37,SUBMISSION
    db 39,TWINEEDLE
    db 42,JUMP_KICK
    db 44,DIZZY_PUNCH
    db 46,SWORDS_DANCE
    db 47,COUNTER
    db 49,MEGA_KICK
    db 52,HAMMER
    db 55,EARTHQUAKE
    db 60,HI_JUMP_KICK
    db 0
; ──────────────────────────────────────────────────────────────────────
TAUROS_Learnset:
    db  1,TACKLE
    db  1,TAIL_WHIP
    db  5,GROWL
    db  7,HORN_ATTACK
    db  9,LEER
    db 10,RAGE
    db 11,STOMP
    db 13,FURY_ATTACK
    db 15,BONE_CLUB
    db 17,DOUBLE_KICK
    db 19,FOCUS_ENERGY
    db 21,SLAM
    db 23,ROCK_THROW
    db 23,Skill__STRENGTH
    db 25,REST
    db 26,QUICK_ATTACK
    db 28,DOUBLE_TEAM
    db 30,AGILITY
    db 32,STRIKE
    db 35,TAKE_DOWN
    db 37,SKULL_BASH
    db 39,THRASH
    db 41,HORN_DRILL
    db 43,SHARPEN
    db 44,BODY_SLAM
    db 49,DOUBLE_EDGE
    db 53,EARTHQUAKE
    db 57,ROCK_SLIDE
    db 60,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
MAGIKARP_Learnset:
    db  1,SPLASH
    db 15,TACKLE
    db 20,TAIL_WHIP
    ;  20,GYARADOS
    db 0
GYARADOS_Learnset:
    db 20,BITE
    db 20,GROWL
    db 20,LEER
    db 20,WATER_GUN
    db 20,ROAR
    db 20,HYPER_FANG
    db 20,Skill__FLOAT
    db 21,FOCUS_ENERGY
    db 21,RAGE
    db 21,Skill__STRENGTH
    db 22,SLAM
    db 24,WATERFALL
    db 25,WRAP
    db 26,DRAGON_RAGE
    db 28,TAKE_DOWN
    db 31,AURORA_BEAM
    db 33,STRIKE
    db 35,TSUNAMI
    db 37,HAZE
    db 38,SKULL_BASH
    db 39,MIST
    db 40,BODY_SLAM
    db 41,HYDRO_PUMP
    db 43,THRASH
    db 45,ICE_BEAM
    db 47,THUNDERBOLT
    db 49,FLAMETHROWER
    db 52,HYPER_BEAM
    db 56,SUPER_FANG
    db 60,EARTHQUAKE
    db 65,AMNESIA
    db 0
MAGIKARP_NoEvo_Learnset:
    db 30,SLAM
    db 40,AMNESIA ; Exclusive
    db 50,BODY_SLAM
    db 60,TSUNAMI
    db 0
; ──────────────────────────────────────────────────────────────────────
LAPRAS_Learnset:
    db  1,BUBBLE
    db  1,GROWL
    db  3,Skill__FLOAT
    db  7,BIDE
    db  9,WATER_GUN
    db 11,SING
    db 13,MIST
    db 15,AURORA_BEAM
    db 17,WITHDRAW
    db 19,CONFUSE_RAY
    db 21,BUBBLEBEAM
    db 23,TAKE_DOWN
    db 25,WATERFALL
    db 27,SCREECH
    db 29,SKULL_BASH
    db 29,Skill__STRENGTH
    db 31,BODY_SLAM
    db 33,TSUNAMI
    db 35,THUNDERSHOCK
    db 37,SPIKE_CANNON
    db 39,HAZE
    db 42,ICE_BEAM
    db 46,HYDRO_PUMP
    db 49,THRASH
    db 54,BLIZZARD
    db 56,HAMMER
    db 58,HYPER_BEAM
    db 60,HORN_DRILL
    db 0
; ──────────────────────────────────────────────────────────────────────
DITTO_Learnset:
    db  1,TRANSFORM
    db 30,CONVERSION
    db 40,MIMIC
    db 50,MIRROR_MOVE
    db 0
; ──────────────────────────────────────────────────────────────────────
EEVEE_Learnset:
    db  1,TACKLE
    db  1,TAIL_WHIP
    db  8,SAND_ATTACK
    db 11,GROWL
    db 15,QUICK_ATTACK
    db 18,DOUBLE_KICK
    db 22,BITE
    db 26,DOUBLE_TEAM
    db 29,SLAM
    db 32,SKULL_BASH
    db 36,FOCUS_ENERGY
    db 40,MIMIC ; Exclusive
    db 45,HYPER_FANG
    db 50,TAKE_DOWN
    db 53,BODY_SLAM
    db 57,DOUBLE_EDGE
    db 60,HYPER_BEAM ; Exclusive
    db 60,LOVELY_KISS
    db 0
VAPOREON_Learnset:
    db  1,TACKLE
    db  1,TAIL_WHIP
    db  1,GROWL
    db  1,BUBBLE
    db  6,SAND_ATTACK
    db  8,WATER_GUN
    db  8,Skill__FLOAT
    db 11,MIST
    db 14,QUICK_ATTACK
    db 16,DOUBLE_KICK
    db 19,BITE
    db 22,ACID_ARMOR
    db 25,DOUBLE_TEAM
    db 26,BUBBLEBEAM
    db 28,SLAM
    db 30,SKULL_BASH
    db 31,WATERFALL
    db 32,AURORA_BEAM
    db 34,FOCUS_ENERGY
    db 34,Skill__DIG
    db 37,TSUNAMI
    db 39,HAZE
    db 40,ICE_PUNCH
    db 42,HYPER_FANG
    db 45,TAKE_DOWN
    db 48,HYDRO_PUMP
    db 50,BODY_SLAM
    db 52,LIGHT_SCREEN
    db 55,DOUBLE_EDGE
    db 57,LOVELY_KISS
    db 60,SUPER_FANG
    db 0
JOLTEON_Learnset:
    db  1,TACKLE
    db  1,TAIL_WHIP
    db  1,GROWL
    db  1,THUNDERSHOCK
    db  6,SAND_ATTACK
    db  8,SONICBOOM
    db  8,Skill__LIGHT
    db 11,AGILITY
    db 14,QUICK_ATTACK
    db 16,DOUBLE_KICK
    db 19,BITE
    db 22,THUNDER_WAVE
    db 25,DOUBLE_TEAM
    db 26,SWIFT
    db 28,SLAM
    db 30,SKULL_BASH
    db 31,SUPERSONIC
    db 32,PIN_MISSILE
    db 34,FOCUS_ENERGY
    db 34,Skill__DIG
    db 37,THUNDERBOLT
    db 39,FLASH
    db 40,THUNDERPUNCH
    db 42,HYPER_FANG
    db 45,TAKE_DOWN
    db 48,THUNDER_M
    db 50,BODY_SLAM
    db 52,LIGHT_SCREEN
    db 55,DOUBLE_EDGE
    db 57,LOVELY_KISS
    db 60,SUPER_FANG
    db 0
FLAREON_Learnset:
    db  1,TACKLE
    db  1,TAIL_WHIP
    db  1,GROWL
    db  1,EMBER
    db  6,SAND_ATTACK
    db  8,ROAR
    db  8,Skill__LIGHT
    db 11,LEER
    db 14,QUICK_ATTACK
    db 16,DOUBLE_KICK
    db 19,BITE
    db 22,SMOKESCREEN
    db 25,DOUBLE_TEAM
    db 26,SMOG
    db 28,SLAM
    db 30,SKULL_BASH
    db 31,CONFUSE_RAY
    db 32,FIRE_SPIN
    db 34,FOCUS_ENERGY
    db 34,Skill__DIG
    db 37,FLAMETHROWER
    db 39,POISON_GAS
    db 40,FIRE_PUNCH
    db 42,HYPER_FANG
    db 45,TAKE_DOWN
    db 48,FIRE_BLAST
    db 50,BODY_SLAM
    db 52,LIGHT_SCREEN
    db 55,DOUBLE_EDGE
    db 57,LOVELY_KISS
    db 60,SUPER_FANG
    db 0
; ──────────────────────────────────────────────────────────────────────
PORYGON_Learnset:
    db  1,TACKLE
    db  1,CONVERSION
    db  6,AGILITY
    db  9,PSYWAVE
    db 11,TELEPORT
    db 12,THUNDERSHOCK
    db 13,SONICBOOM
    db 14,SUPERSONIC
    db 15,CONFUSION
    db 17,BLADE
    db 17,Skill__CUT
    db 19,FLASH
    db 19,Skill__LIGHT
    db 21,SHARPEN
    db 23,SWIFT
    db 25,RECOVER
    db 25,Skill__HEAL
    db 27,PSYBEAM
    db 29,DISABLE
    db 30,KINESIS
    db 31,LIGHT_SCREEN
    db 33,THUNDER_WAVE
    db 34,Skill__FLY
    db 35,BARRIER
    db 38,HYPNOSIS
    db 39,DREAM_EATER
    db 40,AMNESIA
    db 41,TRI_ATTACK
    db 43,THUNDERBOLT
    db 45,SCREECH
    db 47,PSYCHIC_M
    db 51,REFLECT
    db 55,THUNDER_M
    db 60,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
OMANYTE_Learnset:
    db  1,CONSTRICT
    db  1,WITHDRAW
    db  8,BUBBLE
    db 11,BITE
    db 13,ROCK_THROW
    db 15,WATER_GUN
    db 15,Skill__FLOAT
    db 16,DISABLE
    db 17,LEER
    db 18,SONICBOOM
    db 19,BIND
    db 19,VINE_WHIP
    db 20,BUBBLEBEAM
    db 21,LEECH_LIFE
    db 22,AURORA_BEAM
    db 23,SAND_ATTACK
    db 24,REST
    db 26,SCREECH
    db 28,WATERFALL
    db 30,SUPERSONIC
    db 31,SLAM
    db 33,HAZE
    db 35,ROCK_SLIDE
    db 38,TSUNAMI
    ;  40,OMASTAR
    db 0
OMASTAR_Learnset:
    db 40,HORN_ATTACK
    db 40,FURY_ATTACK
    db 40,SPIKE_CANNON
    db 40,Skill__CUT
    db 40,Skill__DIG
    db 42,ABSORB
    db 43,TRAPHOLE
    db 45,SELFDESTRUCT
    db 46,Skill__STRENGTH
    db 47,HYDRO_PUMP
    db 49,BODY_SLAM
    db 52,HORN_DRILL
    db 54,BARRIER
    db 56,EARTHQUAKE
    db 58,EXPLOSION
    db 60,HAMMER
    db 0
OMANYTE_NoEvo_Learnset:
    db 43,ABSORB
    db 44,Skill__DIG
    db 46,TRAPHOLE
    db 49,SELFDESTRUCT
    db 56,HYDRO_PUMP
    db 58,BARRIER
    db 60,EXPLOSION
    db 0
; ──────────────────────────────────────────────────────────────────────
KABUTO_Learnset:
    db  1,SCRATCH
    db  1,HARDEN
    db  8,BUBBLE
    db 11,LEECH_LIFE
    db 13,ROCK_THROW
    db 15,AGILITY
    db 16,WATER_GUN
    db 17,LEER
    db 18,SAND_ATTACK
    db 19,BLADE
    db 19,SHARPEN
    db 19,Skill__CUT
    db 20,PIN_MISSILE
    db 21,CLAMP
    db 22,STRING_SHOT
    db 23,BUBBLEBEAM
    db 24,REST
    db 26,ABSORB
    db 28,DOUBLE_TEAM
    db 30,FOCUS_ENERGY
    db 31,SLAM
    db 33,MEGA_DRAIN
    db 35,ROCK_SLIDE
    db 38,TWINEEDLE
    ;  40,KABUTOPS
    db 0
KABUTOPS_Learnset:
    db 40,FURY_SWIPES
    db 40,SLASH
    db 40,GUILLOTINE
    db 40,Skill__DIG
    db 40,Skill__STRENGTH
    db 42,TSUNAMI
    db 43,TRAPHOLE
    db 45,SWORDS_DANCE
    db 46,Skill__FLOAT
    db 47,WATERFALL
    db 49,BODY_SLAM
    db 52,CONFUSE_RAY
    db 54,HYDRO_PUMP
    db 56,EARTHQUAKE
    db 58,COUNTER
    db 60,HAMMER
    db 0
KABUTO_NoEvo_Learnset:
    db 43,SLASH
    db 44,Skill__DIG
    db 46,TRAPHOLE
    db 49,SWORDS_DANCE
    db 56,WATERFALL
    db 58,HYDRO_PUMP
    db 60,COUNTER
    db 0
; ──────────────────────────────────────────────────────────────────────
AERODACTYL_Learnset:
    db  1,GUST
    db  1,AGILITY
    db  3,Skill__FLY
    db  6,WING_ATTACK
    db  8,WHIRLWIND
    db 10,QUICK_ATTACK
    db 11,BITE
    db 13,ROCK_THROW
    db 13,Skill__STRENGTH
    db 15,SUPERSONIC
    db 17,HYPER_FANG
    db 19,SCREECH
    db 21,SWOOP
    db 23,REST
    db 25,DOUBLE_TEAM
    db 27,RAZOR_WIND
    db 27,Skill__CUT
    db 29,ROCK_SLIDE
    db 31,FOCUS_ENERGY
    db 32,RAGE
    db 33,DRAGON_RAGE
    db 37,BODY_SLAM
    db 40,TAKE_DOWN
    db 42,Skill__DIG
    db 44,THRASH
    db 48,FLAMETHROWER
    db 52,EARTHQUAKE
    db 54,HYPER_BEAM
    db 57,SUPER_FANG
    db 59,SKY_ATTACK
    db 0
; ──────────────────────────────────────────────────────────────────────
SNORLAX_Learnset:
    db  1,LICK
    db  1,DEFENSE_CURL
    db  6,POUND
    db  8,BITE
    db 11,STOMP
    db 13,DOUBLESLAP
    db 16,REST
    db 18,SLAM
    db 20,ROCK_THROW
    db 20,Skill__STRENGTH
    db 21,HEADBUTT
    db 22,MEGA_PUNCH
    db 24,BODY_SLAM
    db 27,AMNESIA
    db 29,DISABLE
    db 31,STRIKE
    db 32,TAKE_DOWN
    db 34,HARDEN
    db 34,Skill__FLOAT
    db 36,RAGE
    db 37,ROAR
    db 40,EARTHQUAKE
    db 43,TSUNAMI
    db 47,DOUBLE_EDGE
    db 51,ROCK_SLIDE
    db 55,HYPER_BEAM
    db 60,FISSURE
    db 0
; ──────────────────────────────────────────────────────────────────────
ARTICUNO_Learnset:
    db  1,GUST
    db  1,MIST
    db  3,Skill__FLY
    db  3,Skill__FLOAT
    db  9,PECK
    db 11,BUBBLE
    db 13,WATER_GUN
    db 16,WING_ATTACK
    db 18,WHIRLWIND
    db 18,Skill__CUT
    db 21,SWOOP
    db 23,HAZE
    db 25,SCREECH
    db 26,AURORA_BEAM
    db 28,REFLECT
    db 31,RAZOR_WIND
    db 33,MIRROR_MOVE
    db 35,ICE_BEAM
    db 38,BUBBLEBEAM
    db 40,ICE_PUNCH
    db 43,SWIFT
    db 46,LIGHT_SCREEN
    db 48,DOUBLE_EDGE
    db 51,AGILITY
    db 54,EGG_BOMB
    db 56,DRILL_PECK
    db 58,BLIZZARD
    db 60,BARRIER
    db 62,TSUNAMI
    db 65,SKY_ATTACK
    db 70,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
ZAPDOS_Learnset:
    db  1,GUST
    db  1,FLASH
    db  3,Skill__FLY
    db  3,Skill__LIGHT
    db  9,PECK
    db 11,LEER
    db 13,THUNDERSHOCK
    db 16,WING_ATTACK
    db 18,WHIRLWIND
    db 18,Skill__CUT
    db 21,SWOOP
    db 23,THUNDER_WAVE
    db 25,SCREECH
    db 26,QUICK_ATTACK
    db 28,LIGHT_SCREEN
    db 31,RAZOR_WIND
    db 33,MIRROR_MOVE
    db 35,THUNDERBOLT
    db 38,DRILL_PECK
    db 40,THUNDERPUNCH
    db 43,SWIFT
    db 46,BARRIER
    db 48,DOUBLE_EDGE
    db 51,AGILITY
    db 54,EGG_BOMB
    db 56,PIN_MISSILE
    db 58,THUNDER_M
    db 60,REFLECT
    db 62,TWINEEDLE
    db 65,SKY_ATTACK
    db 70,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
MOLTRES_Learnset:
    db  1,GUST
    db  1,LEER
    db  3,Skill__FLY
    db  3,Skill__LIGHT
    db  9,PECK
    db 11,SMOKESCREEN
    db 13,EMBER
    db 16,WING_ATTACK
    db 18,WHIRLWIND
    db 18,Skill__CUT
    db 21,SWOOP
    db 23,POISON_GAS
    db 25,SCREECH
    db 26,SMOG
    db 28,BARRIER
    db 31,RAZOR_WIND
    db 33,MIRROR_MOVE
    db 35,FLAMETHROWER
    db 38,FIRE_SPIN
    db 40,FIRE_PUNCH
    db 43,SWIFT
    db 46,REFLECT
    db 48,DOUBLE_EDGE
    db 51,AGILITY
    db 54,EGG_BOMB
    db 56,DRILL_PECK
    db 58,FIRE_BLAST
    db 60,LIGHT_SCREEN
    db 62,SOLARBEAM
    db 65,SKY_ATTACK
    db 70,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
DRATINI_Learnset:
    db  1,CONSTRICT
    db  1,LEER
    db  6,WRAP
    db  8,SUPERSONIC
    db  9,WATER_GUN
    db  9,Skill__FLOAT
    db 10,THUNDER_WAVE
    db 13,BUBBLEBEAM
    db 15,BITE
    db 17,SLAM
    db 20,THUNDERSHOCK
    db 21,EMBER
    db 22,AURORA_BEAM
    db 24,DRAGON_RAGE
    db 26,AGILITY
    db 28,MIST
    db 30,WATERFALL
    ;  30,DRAGONAIR
    db 0
DRAGONAIR_Learnset:
    db 30,HORN_ATTACK
    db 30,FURY_ATTACK
    db 30,GUST
    db 32,HYPER_FANG
    db 34,LIGHT_SCREEN
    db 36,SKULL_BASH
    db 37,Skill__DIG
    db 38,HAZE
    db 40,RAZOR_WIND
    db 40,Skill__CUT
    db 40,Skill__FLY
    db 41,TRAPHOLE
    db 43,ICE_BEAM
    db 44,FLAMETHROWER
    db 45,THUNDERBOLT
    db 47,BODY_SLAM
    db 48,TSUNAMI
    db 50,HYPER_BEAM
    db 55,WING_ATTACK
    ;  55,DRAGONITE
    db 0
DRAGONITE_Learnset:
    db 55,Skill__STRENGTH
    db 55,SWOOP
    db 56,HYDRO_PUMP
    db 57,THUNDERPUNCH
    db 57,THUNDER_M
    db 58,ICE_PUNCH
    db 58,BLIZZARD
    db 59,FIRE_PUNCH
    db 59,FIRE_BLAST
    db 60,HORN_DRILL
    db 60,SKY_ATTACK
    db 65,ROAR
    db 0
DRATINI_NoEvo_Learnset:
    db 35,LIGHT_SCREEN
    db 40,HAZE
    db 45,ICE_BEAM
    db 46,FLAMETHROWER
    db 47,THUNDERBOLT
    db 50,TSUNAMI
    db 55,HYPER_BEAM
    db 60,HYDRO_PUMP
    db 0
DRAGONAIR_NoEvo_Learnset:
    db 58,HYDRO_PUMP
    db 0
; ──────────────────────────────────────────────────────────────────────
MEWTWO_Learnset:
    db  1,CONFUSION
    db  1,DISABLE
    db  4,RAGE
    db  7,REFLECT
    db  7,Skill__LIGHT
    db  8,PSYWAVE
    db 10,TELEPORT
    db 14,KINESIS
    db 16,PSYBEAM
    db 18,AMNESIA
    db 20,MEDITATE
    db 20,Skill__FLY
    db 22,LIGHT_SCREEN
    db 25,SUPERSONIC
    db 28,PSYCHIC_M
    db 30,SWIFT
    db 30,Skill__CUT
    db 33,RECOVER
    db 34,HYPNOSIS
    db 38,DREAM_EATER
    db 40,MIST
    db 42,HAZE
    db 44,SUBSTITUTE
    db 46,ROCK_THROW
    db 46,Skill__STRENGTH
    db 48,BARRIER
    db 50,NIGHT_SHADE
    db 53,THUNDERBOLT
    db 56,FLAMETHROWER
    db 58,ICE_BEAM
    db 61,SOLARBEAM
    db 63,SELFDESTRUCT
    db 65,ROCK_SLIDE
    db 68,EARTHQUAKE
    db 70,HYPER_BEAM
    db 0
; ──────────────────────────────────────────────────────────────────────
MEW_Learnset:
    db  1,Skill__CUT
    db  1,Skill__FLY
    db  1,Skill__FLOAT
    db  1,Skill__STRENGTH
    db  1,Skill__LIGHT
    db  1,TELEPORT
    db  1,Skill__DIG
    db  1,Skill__HEAL
    db  1,TRANSFORM
    db  1,CONVERSION
    db  1,MIMIC
    db  1,MIRROR_MOVE
    db  1,METRONOME
    db  1,PSYCHIC_M
    db  1,SOFTBOILED
    db 0
; ──────────────────────────────────────────────────────────────────────
LITWICK_Learnset:
    db  1,SMOG
    db  1,MINIMIZE
    db  5,TELEPORT
    db  7,DEFENSE_CURL
    db  9,EMBER
    db 11,FLASH
    db 11,Skill__LIGHT
    db 13,CONFUSE_RAY
    db 15,SMOKESCREEN
    db 17,NIGHT_SHADE
    db 20,PSYWAVE
    db 23,FIRE_PUNCH
    db 25,SONICBOOM
    db 27,CONFUSION
    db 29,POISON_GAS
    db 31,HYPNOSIS
    db 32,DREAM_EATER
    db 35,HAZE
    db 38,FLAMETHROWER
    db 40,PSYBEAM
    ;  41,LAMPENT
    db 0
LAMPENT_Learnset:
    db 41,ACID
    db 43,FIRE_SPIN
    db 45,REFLECT
    db 47,PSYCHIC_M
    db 50,SELFDESTRUCT
    db 53,FIRE_BLAST
    db 58,ACID_ARMOR
    db 0
CHANDELURE_Learnset:
    db 41,ACID
    db 43,FIRE_SPIN
    db 45,REFLECT
    db 47,PSYCHIC_M
    db 50,SELFDESTRUCT
    db 53,FIRE_BLAST
    db 57,SUBSTITUTE
    db 58,ACID_ARMOR
    db 60,RECOVER
    db 0
LITWICK_NoEvo_Learnset:
    db 45,FIRE_SPIN
    db 50,ACID_ARMOR ; Exclusive
    db 0
; ──────────────────────────────────────────────────────────────────────