FLY_SKILL_SORT      EQU 1
TELEPORT_SKILL_SORT EQU 2
DIG_SKILL_SORT      EQU 3
CUT_SKILL_SORT      EQU 4
FLOAT_SKILL_SORT    EQU 5
STRENGTH_SKILL_SORT EQU 6
LIGHT_SKILL_SORT    EQU 7
HEAL_SKILL_SORT     EQU 8

CUT_FLAG_BYTE EQU $d803
CUT_FLAG_BIT  EQU 0

FLY_FLAG_BYTE EQU $d7e0
FLY_FLAG_BIT  EQU 6

FLOAT_FLAG_BYTE EQU $d857
FLOAT_FLAG_BIT  EQU 0

STRENGTH_FLAG_BYTE EQU $d78e
STRENGTH_FLAG_BIT  EQU 0

LIGHT_FLAG_BYTE EQU $d7c2
LIGHT_FLAG_BIT  EQU 0