; ────────────────────────────────────────────────

SpecialTrainer: MACRO
    db \1,\2
    dw \3
    ENDM

; ────────────────────────────────────────────────

SpecialTrainerMoves:
    SpecialTrainer BROCK,1,BrockMove1
    SpecialTrainer BROCK,2,BrockMove2
    SpecialTrainer BROCK,3,BrockMove3
    SpecialTrainer BROCK,4,BrockMove4
    SpecialTrainer BROCK,5,BrockMove5
    SpecialTrainer BROCK,6,BrockMove6
    SpecialTrainer BROCK,7,BrockMove7
    SpecialTrainer BROCK,8,BrockMove8
    SpecialTrainer BROCK,9,BrockMove9
    SpecialTrainer MISTY,1,MistyMove2
    SpecialTrainer MISTY,2,MistyMove3
    SpecialTrainer MISTY,3,MistyMove4
    SpecialTrainer MISTY,4,MistyMove5
    SpecialTrainer MISTY,5,MistyMove6
    SpecialTrainer MISTY,6,MistyMove7
    SpecialTrainer MISTY,7,MistyMove8
    SpecialTrainer MISTY,8,MistyMove9
    SpecialTrainer LT_SURGE,1,LtSurgeMove3
    SpecialTrainer LT_SURGE,2,LtSurgeMove4
    SpecialTrainer LT_SURGE,3,LtSurgeMove5
    SpecialTrainer LT_SURGE,4,LtSurgeMove6
    SpecialTrainer LT_SURGE,5,LtSurgeMove7
    SpecialTrainer LT_SURGE,6,LtSurgeMove8
    SpecialTrainer LT_SURGE,7,LtSurgeMove9
    SpecialTrainer ERIKA,1,ErikaMove4
    SpecialTrainer ERIKA,2,ErikaMove5
    SpecialTrainer ERIKA,3,ErikaMove6
    SpecialTrainer ERIKA,4,ErikaMove7
    SpecialTrainer ERIKA,5,ErikaMove8
    SpecialTrainer ERIKA,6,ErikaMove9
    SpecialTrainer KOGA,1,KogaMove6
    SpecialTrainer KOGA,2,KogaMove7
    SpecialTrainer KOGA,3,KogaMove8
    SpecialTrainer KOGA,4,KogaMove9
    SpecialTrainer SABRINA,1,SabrinaMove6
    SpecialTrainer SABRINA,2,SabrinaMove7
    SpecialTrainer SABRINA,3,SabrinaMove8
    SpecialTrainer SABRINA,4,SabrinaMove9
    SpecialTrainer BLAINE,1,BlaineMove7
    SpecialTrainer BLAINE,2,BlaineMove8
    SpecialTrainer BLAINE,3,BlaineMove9
    SpecialTrainer BLACKBELT,1,DojoLeader
    SpecialTrainer GIOVANNI,1,Giovanni1Move
    SpecialTrainer GIOVANNI,2,Giovanni2Move
    SpecialTrainer GIOVANNI,3,Giovanni3Move
    SpecialTrainer LORELEI,1,LoreleiMove1
    SpecialTrainer LORELEI,2,LoreleiMove2
    SpecialTrainer BRUNO,1,BrunoMove1
    SpecialTrainer BRUNO,2,BrunoMove2
    SpecialTrainer AGATHA,1,AgathaMove1
    SpecialTrainer AGATHA,2,AgathaMove2
    SpecialTrainer LANCE,1,LanceMove1
    SpecialTrainer LANCE,2,LanceMove2
    SpecialTrainer SONY2,7,Sony2Move7
    SpecialTrainer SONY2,8,Sony2Move8
    SpecialTrainer SONY2,9,Sony2Move9
    SpecialTrainer SONY2,10,Sony2MoveA
    SpecialTrainer SONY2,11,Sony2MoveB
    SpecialTrainer SONY2,12,Sony2MoveC
    SpecialTrainer SONY3,1,Sony3Move1
    SpecialTrainer SONY3,2,Sony3Move2
    SpecialTrainer SONY3,3,Sony3Move3
    SpecialTrainer COOLTRAINER_F,2,CooltrainerFMove2
    SpecialTrainer COOLTRAINER_F,3,CooltrainerFMove3
    SpecialTrainer COOLTRAINER_F,4,CooltrainerFMove4
    SpecialTrainer COOLTRAINER_M,2,CooltrainerMMove2
    SpecialTrainer COOLTRAINER_M,3,CooltrainerMMove3
    SpecialTrainer COOLTRAINER_M,4,CooltrainerMMove4
    SpecialTrainer BLACKBELT,9,BlackBeltMove9
    SpecialTrainer JUGGLER,2,JugglerMove2
    SpecialTrainer JUGGLER,5,JugglerMove5
    SpecialTrainer TAMER,5,TamerMove5
    SpecialTrainer POKEMANIAC,6,PokemaniacMove6
    SpecialTrainer CHANNELER,14,ChannelerMove14
    SpecialTrainer CHANNELER,15,ChannelerMove15
    SpecialTrainer CHANNELER,16,ChannelerMove16
    SpecialTrainer POKEMANIAC,8,PokemaniacMove8
    db $ff

; ────────────────────────────────────────────────

BrockMove1:
    ; 12,GEODUDE
    db SAND_ATTACK,DEFENSE_CURL,DOUBLESLAP,BIDE 
    ; 14,ONIX
    db SCREECH,BIDE,ROCK_THROW,RAGE
    db 0

BrockMove2:
    ; 18,GEODUDE
    db TRAPHOLE,HARDEN,ROCK_THROW,BIDE
    ; 21,ONIX
    db SHARPEN,BIDE,BLADE,SAND_ATTACK
    db 0

BrockMove3:
    ; 25,GRAVELER
    db BODY_SLAM,HARDEN,ROCK_THROW,BIDE
    ; 21,VULPIX
    db QUICK_ATTACK,EMBER,TAIL_WHIP,BITE
    ; 29,ONIX
    db SHARPEN,BIDE,ROCK_SLIDE,TRAPHOLE
    db 0

BrockMove4:
    ; 28,GRAVELER
    db BODY_SLAM,HARDEN,ROCK_THROW,BIDE
    ; 26,VULPIX
    db QUICK_ATTACK,EMBER,TAIL_WHIP,DOUBLE_KICK
    ; 25,OMANYTE
    db WITHDRAW,REST,AURORA_BEAM,ROCK_THROW
    ; 25,KABUTO
    db REST,ROCK_THROW,STRING_SHOT,CLAMP
    ; 38,ONIX
    db SHARPEN,BIDE,ROCK_SLIDE,BODY_SLAM
    db 0

BrockMove5:
    ; 32,GRAVELER
    db BODY_SLAM,HARDEN,ROCK_SLIDE,TRAPHOLE
    ; 31,VULPIX
    db DOUBLE_KICK,EMBER,CONFUSE_RAY,AGILITY
    ; 30,OMANYTE
    db WITHDRAW,SUPERSONIC,BUBBLEBEAM,ROCK_THROW
    ; 30,KABUTO
    db DOUBLE_TEAM,ROCK_THROW,ABSORB,LEECH_LIFE
    ; 44,ONIX
    db DRAGON_RAGE,SHARPEN,ROCK_SLIDE,BODY_SLAM
    db 0

BrockMove6:
    ; 39,GRAVELER
    db EARTHQUAKE,HARDEN,ROCK_SLIDE,SAND_ATTACK
    ; 42,NINETALES
    db TRAPHOLE,FLAMETHROWER,CONFUSE_RAY,DOUBLE_TEAM
    ; 39,OMANYTE
    db WITHDRAW,SUPERSONIC,TSUNAMI,ROCK_SLIDE
    ; 39,KABUTO
    db FOCUS_ENERGY,ROCK_SLIDE,MEGA_DRAIN,TWINEEDLE
    ; 52,ONIX
    db DRAGON_RAGE,SHARPEN,ROCK_SLIDE,EARTHQUAKE
    db 0

BrockMove7:
    ; 44,NINETALES
    db TRAPHOLE,FLAMETHROWER,CONFUSE_RAY,DOUBLE_TEAM
    ; 49,GOLEM
    db EARTHQUAKE,FIRE_PUNCH,ROCK_SLIDE,REST
    ; 43,OMASTAR
    db WITHDRAW,SUPERSONIC,TSUNAMI,TRAPHOLE
    ; 43,KABUTOPS
    db REST,ROCK_SLIDE,SLASH,TWINEEDLE
    ; 43,AERODACTYL
    db ROCK_SLIDE,DRAGON_RAGE,BODY_SLAM,REST
    ; 55,ONIX
    db SUBSTITUTE,EARTHQUAKE,ROCK_SLIDE,SWORDS_DANCE
    db 0

BrockMove8:
    ; 56,NINETALES
    db SLASH,FIRE_BLAST,DREAM_EATER,LOVELY_KISS
    ; 57,GOLEM
    db EARTHQUAKE,DIZZY_PUNCH,ROCK_SLIDE,REST
    ; 53,OMASTAR
    db SCREECH,WATERFALL,ROCK_SLIDE,BODY_SLAM
    ; 53,KABUTOPS
    db SWORDS_DANCE,ROCK_SLIDE,WATERFALL,TWINEEDLE
    ; 55,AERODACTYL
    db ROCK_SLIDE,SUPERSONIC,EARTHQUAKE,WING_ATTACK
    ; 60,ONIX
    db SUBSTITUTE,EARTHQUAKE,ROCK_SLIDE,HYPER_BEAM
    db 0

BrockMove9:
    ; 61,NINETALES
    db NIGHT_SHADE,FIRE_BLAST,CONFUSE_RAY,LOVELY_KISS
    ; 62,GOLEM
    db BODY_SLAM,FIRE_PUNCH,ROCK_SLIDE,SUBSTITUTE
    ; 58,OMASTAR
    db WITHDRAW,SUPERSONIC,HYDRO_PUMP,BLIZZARD
    ; 58,KABUTOPS
    db SWORDS_DANCE,ROCK_SLIDE,EARTHQUAKE,TWINEEDLE
    ; 60,AERODACTYL
    db ROCK_SLIDE,DOUBLE_TEAM,EARTHQUAKE,HYPER_BEAM
    ; 65,ONIX
    db SUBSTITUTE,EARTHQUAKE,ROCK_SLIDE,SLUDGE
    db 0

; ────────────────────────────────────────────────

MistyMove2:
    ; 18,STARYU
    db BUBBLEBEAM,HARDEN,WATER_GUN,MINIMIZE
    ; 21,STARMIE
    db TACKLE,BUBBLEBEAM,CONVERSION,RECOVER
    db 0

MistyMove3:
    ; 25,STARYU
    db BUBBLEBEAM,AGILITY,CONFUSION,RECOVER
    ; 15,PSYDUCK
    db CONFUSION,DISABLE,PSYWAVE,TAIL_WHIP
    ; 19,MAGIKARP
    db SPLASH,TACKLE,0,0
    ; 29,STARMIE
    db SWIFT,BUBBLEBEAM,PSYBEAM,RECOVER
    db 0

MistyMove4:
    ; 29,STARYU
    db BUBBLEBEAM,SUPERSONIC,CONFUSION,RECOVER
    ; 24,GOLDEEN
    db BUBBLEBEAM,WATERFALL,HORN_ATTACK,SUPERSONIC
    ; 33,GOLDUCK
    db BUBBLEBEAM,PSYBEAM,SUPERSONIC,AMNESIA
    ; 25,GYARADOS
    db BUBBLEBEAM,FOCUS_ENERGY,HYPER_FANG,WATERFALL
    ; 38,STARMIE
    db FLARE,BUBBLEBEAM,PSYBEAM,RECOVER
    db 0

MistyMove5:
    ; 30,HORSEA
    db BUBBLEBEAM,LEECH_LIFE,SMOKESCREEN,DISABLE
    ; 32,GOLDEEN
    db BUBBLEBEAM,REST,WATERFALL,SUPERSONIC
    ; 35,GOLDUCK
    db BUBBLEBEAM,PSYBEAM,SLASH,AMNESIA
    ; 35,GYARADOS
    db TSUNAMI,DRAGON_RAGE,WRAP,WATERFALL
    ; 44,STARMIE
    db HYPNOSIS,AURORA_BEAM,PSYBEAM,RECOVER
    db 0

MistyMove6:
    ; 36,SEADRA
    db SAND_ATTACK,DRAGON_RAGE,SUPERSONIC,SMOKESCREEN
    ; 39,SEAKING
    db SCREECH,REST,WATERFALL,HORN_ATTACK
    ; 45,GOLDUCK
    db TSUNAMI,PSYBEAM,ICE_PUNCH,FLARE
    ; 43,GYARADOS
    db HYDRO_PUMP,HAZE,BODY_SLAM,WATERFALL
    ; 52,STARMIE
    db FLARE,TSUNAMI,PSYCHIC_M,RECOVER
    db 0

MistyMove7:
    ; 47,GOLDUCK
    db TSUNAMI,PSYBEAM,FLARE,AMNESIA
    ; 39,SEADRA
    db AURORA_BEAM,DRAGON_RAGE,SUPERSONIC,SLUDGE
    ; 43,SEAKING
    db TSUNAMI,AGILITY,WATERFALL,HORN_DRILL
    ; 43,LAPRAS
    db ICE_BEAM,TSUNAMI,BODY_SLAM,CONFUSE_RAY
    ; 48,GYARADOS
    db HYDRO_PUMP,HAZE,BODY_SLAM,THUNDERBOLT
    ; 55,STARMIE
    db FLARE,TSUNAMI,THUNDERBOLT,RECOVER
    db 0

MistyMove8:
    ; 53,GOLDUCK
    db HYDRO_PUMP,ICE_BEAM,FLARE,LIGHT_SCREEN
    ; 51,SEADRA
    db ICE_BEAM,DRAGON_RAGE,POISON_GAS,TSUNAMI
    ; 52,VAPOREON
    db BODY_SLAM,HYDRO_PUMP,AURORA_BEAM,ACID_ARMOR
    ; 53,LAPRAS
    db ICE_BEAM,HYDRO_PUMP,THUNDERBOLT,CONFUSE_RAY
    ; 55,GYARADOS
    db HYDRO_PUMP,HAZE,HYPER_BEAM,ICE_BEAM
    ; 60,STARMIE
    db HYPNOSIS,HYDRO_PUMP,THUNDER_M,FLARE
    db 0

MistyMove9:
    ; 58,GOLDUCK
    db PSYCHIC_M,HYDRO_PUMP,FLARE,AMNESIA
    ; 56,SEADRA
    db ICE_BEAM,HYPER_BEAM,SUPERSONIC,HYDRO_PUMP
    ; 57,VAPOREON
    db BODY_SLAM,HYDRO_PUMP,AURORA_BEAM,ACID_ARMOR
    ; 58,LAPRAS
    db BLIZZARD,HYPER_BEAM,HYDRO_PUMP,THUNDER_WAVE
    ; 60,GYARADOS
    db HYDRO_PUMP,HAZE,SUPER_FANG,EARTHQUAKE
    ; 65,STARMIE
    db FLARE,THUNDERBOLT,BLIZZARD,RECOVER
    db 0

; ────────────────────────────────────────────────

LtSurgeMove3:
    ; 29,RAICHU
    db SUBMISSION,GROWL,THUNDERBOLT,THUNDER_WAVE
    db 0

LtSurgeMove4:
    ; 28,VOLTORB
    db SELFDESTRUCT,SLAM,SUPERSONIC,QUICK_ATTACK
    ; 28,MAGNEMITE
    db SUPERSONIC,BLADE,THUNDERBOLT,THUNDER_WAVE
    ; 38,RAICHU
    db SUBMISSION,FLASH,THUNDER_M,THUNDER_WAVE
    db 0

LtSurgeMove5:
    ; 33,ELECTRODE
    db EXPLOSION,SLAM,THUNDER_WAVE,THUNDERBOLT
    ; 33,MAGNETON
    db CONVERSION,BLADE,THUNDERBOLT,THUNDER_WAVE
    ; 32,JOLTEON
    db PIN_MISSILE,QUICK_ATTACK,THUNDERBOLT,DOUBLE_TEAM
    ; 44,RAICHU
    db SUBMISSION,REFLECT,THUNDER_M,THUNDER_WAVE
    db 0

LtSurgeMove6:
    ; 47,ELECTRODE
    db EXPLOSION,BODY_SLAM,THUNDER_WAVE,THUNDERBOLT
    ; 43,MAGNETON
    db REFLECT,TRI_ATTACK,THUNDERBOLT,SUPERSONIC
    ; 44,JOLTEON
    db PIN_MISSILE,HYPER_FANG,THUNDERBOLT,THUNDER_WAVE
    ; 42,ELECTABUZZ
    db ROLLING_KICK,BODY_SLAM,THUNDER_WAVE,THUNDERBOLT
    ; 52,RAICHU
    db SUBMISSION,REFLECT,THUNDER_M,THUNDER_WAVE
    db 0

LtSurgeMove7:
    ; 47,JOLTEON
    db PIN_MISSILE,HYPER_FANG,THUNDERBOLT,THUNDER_WAVE
    ; 50,ELECTRODE
    db EXPLOSION,BODY_SLAM,THUNDER_WAVE,THUNDERBOLT
    ; 48,MAGNETON
    db SCREECH,SELFDESTRUCT,THUNDER_M,SUPERSONIC
    ; 46,ELECTABUZZ
    db JUMP_KICK,BODY_SLAM,THUNDER_WAVE,THUNDERBOLT
    ; 43,PIKACHU
    db DOUBLE_TEAM,QUICK_ATTACK,THUNDERBOLT,THUNDER_WAVE
    ; 55,RAICHU
    db BODY_SLAM,REFLECT,THUNDER_M,LOVELY_KISS
    db 0

LtSurgeMove8:
    ; 52,JOLTEON
    db PIN_MISSILE,BODY_SLAM,THUNDERBOLT,THUNDER_WAVE
    ; 56,ELECTRODE
    db RECOVER,BODY_SLAM,THUNDER_WAVE,THUNDER_M
    ; 55,MAGNETON
    db REFLECT,RECOVER,THUNDER_M,TRI_ATTACK
    ; 53,ELECTABUZZ
    db JUMP_KICK,DIZZY_PUNCH,THUNDER_WAVE,THUNDER_M
    ; 55,PIKACHU
    db MEGA_PUNCH,THUNDER_WAVE,THUNDERBOLT,LOVELY_KISS
    ; 60,RAICHU
    db DIZZY_PUNCH,THUNDER_WAVE,THUNDERBOLT,LOVELY_KISS
    db 0

LtSurgeMove9:
    ; 57,JOLTEON
    db PIN_MISSILE,BODY_SLAM,THUNDERBOLT,THUNDER_WAVE
    ; 61,ELECTRODE
    db RECOVER,BODY_SLAM,THUNDER_WAVE,THUNDER_M
    ; 60,MAGNETON
    db REFLECT,RECOVER,THUNDER_M,TRI_ATTACK
    ; 58,ELECTABUZZ
    db MEGA_KICK,BODY_SLAM,THUNDER_WAVE,THUNDERBOLT
    ; 60,PIKACHU
    db MEGA_PUNCH,THUNDER_WAVE,THUNDERBOLT,LOVELY_KISS
    ; 65,RAICHU
    db DIZZY_PUNCH,THUNDER_WAVE,THUNDERBOLT,LOVELY_KISS
    db 0

; ────────────────────────────────────────────────

ErikaMove4:
    ; 30,TANGELA
    db BIND,POISONPOWDER,STUN_SPORE,LEECH_SEED
    ; 34,WEEPINBELL
    db STUN_SPORE,BIND,SLUDGE,RAZOR_LEAF
    ; 38,GLOOM
    db SLEEP_POWDER,MEGA_DRAIN,STUN_SPORE,PETAL_DANCE
    db 0

ErikaMove5:
    ; 36,TANGELA
    db BARRAGE,SPORE,STUN_SPORE,LEECH_SEED
    ; 35,EXEGGCUTE
    db STUN_SPORE,MEGA_DRAIN,SLEEP_POWDER,CONFUSION
    ; 34,PARASECT
    db STUN_SPORE,PIN_MISSILE,MEGA_DRAIN,SPORE
    ; 38,WEEPINBELL
    db STUN_SPORE,POISONPOWDER,SLUDGE,RAZOR_LEAF
    ; 44,GLOOM
    db SLEEP_POWDER,BARRAGE,SLUDGE,REST
    db 0

ErikaMove6:
    ; 45,TANGELA
    db MEGA_DRAIN,PSYBEAM,SPORE,AMNESIA
    ; 44,EXEGGCUTE
    db EGG_BOMB,MEGA_DRAIN,SLEEP_POWDER,PSYBEAM
    ; 42,PARASECT
    db LEECH_SEED,TWINEEDLE,STUN_SPORE,SPORE
    ; 46,WEEPINBELL
    db SLEEP_POWDER,STUN_SPORE,SLUDGE,RAZOR_LEAF
    ; 52,GLOOM
    db SPORE,SOLARBEAM,TOXIC,STUN_SPORE
    db 0

ErikaMove7:
    ; 47,EXEGGCUTE
    db STUN_SPORE,MEGA_DRAIN,SLEEP_POWDER,PSYBEAM
    ; 49,TANGELA
    db MEGA_DRAIN,PSYCHIC_M,SPORE,AMNESIA
    ; 46,PARASECT
    db SOLARBEAM,LEECH_SEED,STUN_SPORE,SPORE
    ; 49,VICTREEBEL
    db SPORE,STUN_SPORE,SLUDGE,RAZOR_LEAF
    ; 52,VILEPLUME
    db TOXIC,SPORE,PETAL_DANCE,LEECH_LIFE
    ; 55,GLOOM
    db SPORE,MEGA_DRAIN,SLUDGE,STUN_SPORE
    db 0

ErikaMove8:
    ; 55,EXEGGUTOR
    db STUN_SPORE,RAZOR_LEAF,SLEEP_POWDER,PSYCHIC_M
    ; 55,TANGELA
    db RECOVER,RAZOR_LEAF,BODY_SLAM,SWORDS_DANCE
    ; 54,PARASECT
    db SWORDS_DANCE,TWINEEDLE,BARRAGE,SPORE
    ; 58,VICTREEBEL
    db TOXIC,SUPER_FANG,SLUDGE,RAZOR_LEAF
    ; 56,VILEPLUME
    db TOXIC,SPORE,LEECH_SEED,BIND
    ; 60,GLOOM
    db SPORE,STUN_SPORE,SLUDGE,RAZOR_LEAF
    db 0

ErikaMove9:
    ; 60,EXEGGUTOR
    db MEGA_DRAIN,STUN_SPORE,SLEEP_POWDER,PSYCHIC_M
    ; 60,TANGELA
    db SPORE,MEGA_DRAIN,TOXIC,AMNESIA
    ; 59,PARASECT
    db SWORDS_DANCE,TWINEEDLE,BARRAGE,SPORE
    ; 62,VICTREEBEL
    db SPORE,SWORDS_DANCE,SLUDGE,RAZOR_LEAF
    ; 61,VILEPLUME
    db TOXIC,NIGHT_SHADE,SPORE,STUN_SPORE
    ; 65,GLOOM
    db SPORE,SWORDS_DANCE,SLUDGE,RAZOR_LEAF
    db 0

; ────────────────────────────────────────────────

KogaMove6:
    ; 48,VENOMOTH
    db SUPERSONIC,PIN_MISSILE,SPORE,PSYCHIC_M
    ; 52,GOLBAT
    db SWOOP,CONFUSE_RAY,TOXIC,DOUBLE_TEAM
    db 0

KogaMove7:
    ; 49,ELECTRODE
    db EXPLOSION,THUNDERBOLT,QUICK_ATTACK,SUPERSONIC
    ; 46,HAUNTER
    db PSYCHIC_M,SLUDGE,CONFUSE_RAY,HYPNOSIS
    ; 51,WEEZING
    db TOXIC,EXPLOSION,SUPERSONIC,SLUDGE
    ; 51,MUK
    db MEGA_DRAIN,SLUDGE,MINIMIZE,ACID_ARMOR
    ; 47,SCYTHER
    db SUBSTITUTE,RAZOR_LEAF,TWINEEDLE,DOUBLE_TEAM
    ; 55,GOLBAT
    db SWOOP,CONFUSE_RAY,TOXIC,SUPER_FANG
    db 0

KogaMove8:
    ; 54,ELECTRODE
    db EXPLOSION,THUNDERBOLT,PSYCHIC_M,SUPERSONIC
    ; 54,VENOMOTH
    db TOXIC,PIN_MISSILE,SPORE,PSYCHIC_M
    ; 57,WEEZING
    db RECOVER,FLAMETHROWER,SUPERSONIC,SLUDGE
    ; 57,ARBOK
    db SUPER_FANG,SLUDGE,HYPNOSIS,SUPERSONIC
    ; 52,TENTACRUEL
    db MEGA_DRAIN,SUPERSONIC,TSUNAMI,SLUDGE
    ; 60,GOLBAT
    db SWOOP,CONFUSE_RAY,TOXIC,NIGHT_SHADE
    db 0

KogaMove9:
    ; 59,VENOMOTH
    db NIGHT_SHADE,PIN_MISSILE,SPORE,PSYCHIC_M
    ; 56,GENGAR
    db NIGHT_SHADE,TOXIC,CONFUSE_RAY,HYPNOSIS
    ; 62,WEEZING
    db RECOVER,TOXIC,SUBSTITUTE,SLUDGE
    ; 62,MUK
    db RECOVER,MEGA_DRAIN,SUBSTITUTE,SLUDGE
    ; 57,SCYTHER
    db SUBSTITUTE,RAZOR_LEAF,TWINEEDLE,CLAMP
    ; 65,GOLBAT
    db SUPER_FANG,CONFUSE_RAY,SLUDGE,NIGHT_SHADE
    db 0

; ────────────────────────────────────────────────

SabrinaMove6:
    ; 48,HAUNTER
    db HYPNOSIS,THUNDERBOLT,PSYCHIC_M,DREAM_EATER
    ; 52,KADABRA
    db RECOVER,PSYCHIC_M,HYPNOSIS,REFLECT
    db 0

SabrinaMove7:
    ; 49,EXEGGUTOR
    db DREAM_EATER,MEGA_DRAIN,HYPNOSIS,PSYCHIC_M
    ; 46,VENOMOTH
    db LIGHT_SCREEN,PIN_MISSILE,SPORE,PSYCHIC_M
    ; 51,SLOWBRO
    db PSYCHIC_M,HYPNOSIS,AMNESIA,TSUNAMI
    ; 51,MR_MIME
    db HYPNOSIS,PSYCHIC_M,MIMIC,BARRIER
    ; 47,HYPNO
    db PSYCHIC_M,HYPNOSIS,DREAM_EATER,RECOVER
    ; 55,ALAKAZAM
    db RECOVER,PSYCHIC_M,HYPNOSIS,REFLECT
    db 0

SabrinaMove8:
    ; 54,GENGAR
    db HYPNOSIS,MEGA_DRAIN,PSYCHIC_M,NIGHT_SHADE
    ; 54,HYPNO
    db PSYCHIC_M,HYPNOSIS,REFLECT,RECOVER
    ; 57,EXEGGUTOR
    db DREAM_EATER,MEGA_DRAIN,HYPNOSIS,PSYCHIC_M
    ; 57,MR_MIME
    db HYPNOSIS,PSYCHIC_M,DREAM_EATER,REST
    ; 52,JYNX
    db LOVELY_KISS,BLIZZARD,PSYCHIC_M,LIGHT_SCREEN
    ; 60,ALAKAZAM
    db RECOVER,PSYCHIC_M,HYPNOSIS,NIGHT_SHADE
    db 0

SabrinaMove9:
    ; 59,GENGAR
    db HYPNOSIS,THUNDERBOLT,PSYCHIC_M,NIGHT_SHADE
    ; 56,VENOMOTH
    db LIGHT_SCREEN,NIGHT_SHADE,SPORE,PSYCHIC_M
    ; 62,SLOWBRO
    db PSYCHIC_M,HYPNOSIS,AMNESIA,BLIZZARD
    ; 62,MR_MIME
    db HYPNOSIS,PSYCHIC_M,SUBSTITUTE,RECOVER
    ; 57,JYNX
    db LOVELY_KISS,NIGHT_SHADE,PSYCHIC_M,LIGHT_SCREEN
    ; 65,ALAKAZAM
    db RECOVER,PSYCHIC_M,HYPNOSIS,NIGHT_SHADE
    db 0

; ────────────────────────────────────────────────

BlaineMove7:
    ; 48,NINETALES
    db FIRE_BLAST,CONFUSE_RAY,LOVELY_KISS,FIRE_SPIN
    ; 47,RHYDON
    db FIRE_BLAST,DIZZY_PUNCH,HORN_DRILL,ROCK_SLIDE
    ; 55,MAGMAR
    db CONFUSE_RAY,BODY_SLAM,FIRE_BLAST,SLUDGE
    db 0

BlaineMove8:
    ; 58,NINETALES
    db FIRE_BLAST,CONFUSE_RAY,LOVELY_KISS,BODY_SLAM
    ; 58,ARCANINE
    db EARTHQUAKE,FIRE_BLAST,SUPER_FANG,FIRE_SPIN
    ; 52,FLAREON
    db BODY_SLAM,FIRE_BLAST,FIRE_SPIN,POISON_GAS
    ; 55,RAPIDASH
    db BODY_SLAM,FIRE_BLAST,HORN_DRILL,FIRE_SPIN
    ; 57,RHYDON
    db FIRE_BLAST,DIZZY_PUNCH,HYPER_BEAM,ROCK_SLIDE
    ; 60,MAGMAR
    db ACID_ARMOR,DIZZY_PUNCH,FIRE_BLAST,SLUDGE
    db 0

BlaineMove9:
    ; 63,NINETALES
    db FIRE_BLAST,NIGHT_SHADE,LOVELY_KISS,BODY_SLAM
    ; 63,ARCANINE
    db EARTHQUAKE,FIRE_BLAST,SUPER_FANG,FIRE_SPIN
    ; 57,FLAREON
    db BODY_SLAM,FIRE_PUNCH,FIRE_SPIN,POISON_GAS
    ; 60,RAPIDASH
    db BODY_SLAM,FIRE_BLAST,NIGHT_SHADE,FIRE_SPIN
    ; 62,RHYDON
    db FIRE_PUNCH,DIZZY_PUNCH,SUBSTITUTE,ROCK_SLIDE
    ; 65,MAGMAR
    db TOXIC,CONFUSE_RAY,FIRE_BLAST,SLUDGE
    db 0

; ────────────────────────────────────────────────

DojoLeader:
    ; 39,HITMONLEE
    db ROCK_THROW,TRAPHOLE,HI_JUMP_KICK,EARTHQUAKE
    ; 39,HITMONCHAN
    db FIRE_PUNCH,ICE_PUNCH,THUNDERPUNCH,SUBMISSION
    db 0

; ────────────────────────────────────────────────

Giovanni1Move:
    ; 24,CUBONE
    db BONE_CLUB,TRAPHOLE,FOCUS_ENERGY,LEER
    ; 25,KRABBY
    db BONE_CLUB,TRAPHOLE,BUBBLEBEAM,SHARPEN
    ; 38,RHYHORN
    db STOMP,TRAPHOLE,ROCK_SLIDE,BODY_SLAM
    ; 40,PERSIAN
    db FLARE,TRAPHOLE,REST,SLASH
    db 0

Giovanni2Move:
    ; 42,NIDORINO
    db DOUBLE_KICK,DOUBLE_TEAM,TRAPHOLE,SLUDGE
    ; 43,PERSIAN
    db FLARE,TRAPHOLE,REST,SLASH
    ; 44,RHYDON
    db BODY_SLAM,DOUBLE_KICK,EARTHQUAKE,HORN_DRILL
    ; 45,NIDOQUEEN
    db BODY_SLAM,SLASH,SLUDGE,EARTHQUAKE
    db 0

Giovanni3Move:
    ; 59,PERSIAN
    db LOVELY_KISS,TRAPHOLE,REST,HYPER_BEAM
    ; 55,NIDOQUEEN
    db SLUDGE,EARTHQUAKE,DIZZY_PUNCH,ICE_PUNCH
    ; 55,NIDOKING
    db SLUDGE,EARTHQUAKE,DIZZY_PUNCH,THUNDERPUNCH
    ; 56,RHYDON
    db EARTHQUAKE,ROCK_SLIDE,FISSURE,SWORDS_DANCE
    ; 55,KINGLER
    db SWORDS_DANCE,ROCK_SLIDE,CRABHAMMER,GUILLOTINE
    ; 60,MAROWAK
    db FISSURE,CRABHAMMER,EARTHQUAKE,ROCK_SLIDE
    db 0

; ────────────────────────────────────────────────

BrunoMove1:
    ; 53,PRIMEAPE
    db JUMP_KICK,SCREECH,SEISMIC_TOSS,ROCK_SLIDE
    ; 55,HITMONCHAN
    db MEGA_PUNCH,BODY_SLAM,AGILITY,ICE_PUNCH
    ; 55,HITMONLEE
    db HI_JUMP_KICK,MEDITATE,BODY_SLAM,SEISMIC_TOSS
    ; 58,ONIX
    db BODY_SLAM,DRAGON_RAGE,ROCK_SLIDE,EARTHQUAKE
    ; 57,PINSIR
    db SUBMISSION,CRABHAMMER,SWORDS_DANCE,TWINEEDLE
    ; 58,MACHAMP
    db HI_JUMP_KICK,EARTHQUAKE,BODY_SLAM,COUNTER
    db 0

BrunoMove2:
    ; 62,POLIWRATH
    db HYPNOSIS,ICE_PUNCH,JUMP_KICK,WATERFALL
    ; 63,HITMONCHAN
    db MEGA_PUNCH,COUNTER,THUNDERPUNCH,ICE_PUNCH
    ; 63,HITMONLEE
    db HI_JUMP_KICK,SWORDS_DANCE,RAZOR_LEAF,SEISMIC_TOSS
    ; 64,PINSIR
    db JUMP_KICK,CRABHAMMER,SWORDS_DANCE,TWINEEDLE
    ; 65,MACHAMP
    db HI_JUMP_KICK,EARTHQUAKE,HYPER_BEAM,COUNTER
    ; 65,ONIX
    db BODY_SLAM,SUBSTITUTE,SLUDGE,EARTHQUAKE
    db 0

; ────────────────────────────────────────────────

AgathaMove1:
    ; 55,HAUNTER
    db MEGA_DRAIN,NIGHT_SHADE,HYPNOSIS,DREAM_EATER
    ; 56,GOLBAT
    db SLUDGE,CONFUSE_RAY,SWOOP,DOUBLE_TEAM
    ; 58,ARBOK
    db TRAPHOLE,SUPER_FANG,SLUDGE,HAZE
    ; 55,VENUSAUR
    db RAZOR_LEAF,SLEEP_POWDER,SLUDGE,TOXIC
    ; 56,HYPNO
    db HYPNOSIS,RECOVER,PSYCHIC_M,NIGHT_SHADE
    ; 60,GENGAR
    db SLUDGE,PSYCHIC_M,TOXIC,ACID_ARMOR
    db 0

AgathaMove2:
    ; 61,GENGAR
    db MEGA_DRAIN,PSYCHIC_M,HYPNOSIS,AMNESIA
    ; 64,GOLBAT
    db SLUDGE,CONFUSE_RAY,SWOOP,TOXIC
    ; 63,ARBOK
    db EARTHQUAKE,SUPER_FANG,WRAP,FLARE
    ; 64,HYPNO
    db HYPNOSIS,RECOVER,PSYCHIC_M,NIGHT_SHADE
    ; 65,GENGAR
    db SLUDGE,NIGHT_SHADE,HYPER_BEAM,SUBSTITUTE
    ; 65,MAROWAK
    db NIGHT_SHADE,BONEMERANG,FIRE_PUNCH,SWORDS_DANCE
    db 0

; ────────────────────────────────────────────────

LoreleiMove1:
    ; 54,DEWGONG
    db WATERFALL,BODY_SLAM,REST,ICE_BEAM
    ; 53,CLOYSTER
    db ICE_BEAM,HAZE,CLAMP,SPIKE_CANNON
    ; 54,SLOWBRO
    db TSUNAMI,ICE_BEAM,AMNESIA,PSYCHIC_M
    ; 55,BLASTOISE
    db COUNTER,HYDRO_PUMP,DIZZY_PUNCH,ICE_PUNCH
    ; 56,JYNX
    db REFLECT,LOVELY_KISS,BLIZZARD,PSYCHIC_M
    ; 56,LAPRAS
    db THUNDERBOLT,REST,CRABHAMMER,BLIZZARD
    db 0

LoreleiMove2:
    ; 63,JYNX
    db REFLECT,LOVELY_KISS,BLIZZARD,PSYCHIC_M
    ; 63,DEWGONG
    db WATERFALL,BODY_SLAM,REST,BLIZZARD
    ; 62,CLOYSTER
    db BLIZZARD,LOVELY_KISS,CRABHAMMER,TSUNAMI
    ; 61,SLOWBRO
    db TSUNAMI,BLIZZARD,AMNESIA,PSYCHIC_M
    ; 65,LAPRAS
    db HYPER_BEAM,SUBSTITUTE,CRABHAMMER,BLIZZARD
    ; 65,NINETALES
    db BLIZZARD,NIGHT_SHADE,LOVELY_KISS,SUPER_FANG
    db 0

; ────────────────────────────────────────────────

LanceMove1:
    ; 58,GYARADOS
    db HYPER_BEAM,HYDRO_PUMP,THUNDERBOLT,FLAMETHROWER
    ; 54,DRAGONAIR
    db LIGHT_SCREEN,TSUNAMI,HYPER_BEAM,FLAMETHROWER
    ; 54,DRAGONAIR
    db LIGHT_SCREEN,THUNDERBOLT,HYPER_BEAM,ICE_BEAM
    ; 55,CHARIZARD
    db SLASH,FLAMETHROWER,DRAGON_RAGE,HYPER_BEAM
    ; 60,AERODACTYL
    db FLAMETHROWER,EARTHQUAKE,HYPER_BEAM,ROCK_SLIDE
    ; 62,DRAGONITE
    db THUNDERPUNCH,ICE_PUNCH,FIRE_PUNCH,HYPER_BEAM
    db 0

LanceMove2:
    ; 68,GYARADOS
    db SUPER_FANG,HYDRO_PUMP,THUNDER_WAVE,EARTHQUAKE
    ; 62,DRAGONITE
    db REFLECT,WATERFALL,EARTHQUAKE,FIRE_PUNCH
    ; 62,DRAGONITE
    db LIGHT_SCREEN,THUNDERPUNCH,WING_ATTACK,ICE_PUNCH
    ; 65,CHARIZARD
    db SLASH,FIRE_BLAST,SUPER_FANG,EARTHQUAKE
    ; 70,DRAGONITE
    db THUNDERPUNCH,ICE_PUNCH,THUNDER_WAVE,HYPER_BEAM
    ; 70,AERODACTYL
    db SUPERSONIC,EARTHQUAKE,SKY_ATTACK,ROCK_SLIDE
    db 0

; ────────────────────────────────────────────────

Sony2Move7:
    ; 37,PIDGEOT
    db QUICK_ATTACK,WING_ATTACK,SWOOP,RAZOR_WIND
    ; 38,ARCANINE
    db HYPER_FANG,DOUBLE_KICK,AGILITY,FLAMETHROWER
    ; 35,EXEGGUTOR
    db LEECH_SEED,EGG_BOMB,SLEEP_POWDER,PSYBEAM
    ; 35,ALAKAZAM
    db FLARE,KINESIS,PSYBEAM,RECOVER
    ; 38,RHYHORN
    db BODY_SLAM,ROCK_SLIDE,TRAPHOLE,THRASH
    ; 40,BLASTOISE
    db WITHDRAW,SEISMIC_TOSS,BODY_SLAM,TSUNAMI
    db 0

Sony2Move8:
    ; 37,PIDGEOT
    db QUICK_ATTACK,WING_ATTACK,SWOOP,RAZOR_WIND
    ; 38,CLOYSTER
    db SUPERSONIC,CLAMP,AURORA_BEAM,MIST
    ; 35,ARCANINE
    db HYPER_FANG,DOUBLE_KICK,POISON_GAS,FLAMETHROWER
    ; 35,ALAKAZAM
    db FLARE,KINESIS,PSYBEAM,RECOVER
    ; 38,RHYHORN
    db BODY_SLAM,ROCK_SLIDE,TRAPHOLE,THRASH
    ; 40,VENUSAUR
    db RAZOR_LEAF,STUN_SPORE,LEECH_SEED,BODY_SLAM
    db 0

Sony2Move9:
    ; 37,PIDGEOT
    db QUICK_ATTACK,WING_ATTACK,SWOOP,RAZOR_WIND
    ; 38,EXEGGUTOR
    db EGG_BOMB,SLEEP_POWDER,PSYBEAM,MEGA_DRAIN
    ; 35,CLOYSTER
    db SUPERSONIC,CLAMP,AURORA_BEAM,MIST
    ; 35,ALAKAZAM
    db FLARE,KINESIS,PSYBEAM,RECOVER
    ; 38,RHYHORN
    db BODY_SLAM,ROCK_SLIDE,TRAPHOLE,THRASH
    ; 40,CHARIZARD
    db FIRE_PUNCH,SLASH,DRAGON_RAGE,SWOOP
    db 0

Sony2MoveA:
    ; 47,PIDGEOT
    db SWOOP,AGILITY,MIRROR_MOVE,DRILL_PECK
    ; 45,RHYDON
    db DOUBLE_KICK,EARTHQUAKE,SUBSTITUTE,BODY_SLAM
    ; 45,ARCANINE
    db SUPER_FANG,AGILITY,FIRE_SPIN,FIRE_PUNCH
    ; 47,EXEGGUTOR
    db SLEEP_POWDER,MEGA_DRAIN,PSYCHIC_M,EGG_BOMB
    ; 50,ALAKAZAM
    db RECOVER,PSYCHIC_M,REFLECT,FLARE
    ; 53,BLASTOISE
    db ICE_PUNCH,DIZZY_PUNCH,EARTHQUAKE,HYDRO_PUMP
    db 0

Sony2MoveB:
    ; 47,PIDGEOT
    db SWOOP,AGILITY,MIRROR_MOVE,DRILL_PECK
    ; 45,RHYDON
    db DOUBLE_KICK,EARTHQUAKE,SUBSTITUTE,BODY_SLAM
    ; 45,CLOYSTER
    db SPIKE_CANNON,MIST,SELFDESTRUCT,ICE_BEAM
    ; 47,ARCANINE
    db SUPER_FANG,AGILITY,FIRE_SPIN,FIRE_PUNCH
    ; 50,ALAKAZAM
    db RECOVER,PSYCHIC_M,REFLECT,FLARE
    ; 53,VENUSAUR
    db RAZOR_LEAF,SLUDGE,SLEEP_POWDER,BODY_SLAM
    db 0

Sony2MoveC:
    ; 47,PIDGEOT
    db SWOOP,AGILITY,MIRROR_MOVE,DRILL_PECK
    ; 45,RHYDON
    db DOUBLE_KICK,EARTHQUAKE,SUBSTITUTE,BODY_SLAM
    ; 45,EXEGGUTOR
    db SLEEP_POWDER,MEGA_DRAIN,PSYCHIC_M,EGG_BOMB
    ; 47,CLOYSTER
    db SPIKE_CANNON,MIST,SELFDESTRUCT,ICE_BEAM
    ; 50,ALAKAZAM
    db RECOVER,PSYCHIC_M,REFLECT,FLARE
    ; 53,CHARIZARD
    db SLASH,EARTHQUAKE,SWORDS_DANCE,FLAMETHROWER
    db 0

Sony3Move1:
    ; 61,PIDGEOT
    db DRILL_PECK,SWIFT,EGG_BOMB,SKY_ATTACK
    ; 59,ALAKAZAM
    db RECOVER,PSYCHIC_M,REFLECT,FLARE
    ; 61,RHYDON
    db ROCK_SLIDE,EARTHQUAKE,SUBSTITUTE,DIZZY_PUNCH
    ; 61,ARCANINE
    db BODY_SLAM,AGILITY,FIRE_SPIN,FIRE_BLAST
    ; 63,EXEGGUTOR
    db SLEEP_POWDER,RAZOR_LEAF,PSYCHIC_M,EXPLOSION
    ; 65,BLASTOISE
    db ICE_BEAM,CRABHAMMER,EARTHQUAKE,HYDRO_PUMP
    db 0

Sony3Move2:
    ; 61,PIDGEOT
    db DRILL_PECK,SWIFT,EGG_BOMB,SKY_ATTACK
    ; 59,ALAKAZAM
    db RECOVER,PSYCHIC_M,REFLECT,FLARE
    ; 61,RHYDON
    db ROCK_SLIDE,EARTHQUAKE,SUBSTITUTE,DIZZY_PUNCH
    ; 61,CLOYSTER
    db CRABHAMMER,REST,EXPLOSION,BLIZZARD
    ; 63,ARCANINE
    db EARTHQUAKE,AGILITY,FIRE_SPIN,FIRE_BLAST
    ; 65,VENUSAUR
    db RAZOR_LEAF,SLUDGE,SLEEP_POWDER,BODY_SLAM
    db 0

Sony3Move3:
    ; 61,PIDGEOT
    db DRILL_PECK,SWIFT,EGG_BOMB,SKY_ATTACK
    ; 59,ALAKAZAM
    db RECOVER,PSYCHIC_M,REFLECT,FLARE
    ; 61,RHYDON
    db ROCK_SLIDE,EARTHQUAKE,SUBSTITUTE,BODY_SLAM
    ; 61,EXEGGUTOR
    db SLEEP_POWDER,RAZOR_LEAF,PSYCHIC_M,EXPLOSION
    ; 63,CLOYSTER
    db CRABHAMMER,REST,EXPLOSION,BLIZZARD
    ; 65,CHARIZARD
    db SLASH,EARTHQUAKE,SWORDS_DANCE,FIRE_BLAST
    db 0

; ────────────────────────────────────────────────

CooltrainerFMove2:
    ; 44,VICTREEBEL
    db RAZOR_LEAF,SLUDGE,SPORE,STUN_SPORE
    ; 43,WIGGLYTUFF
    db BODY_SLAM,SOFTBOILED,SING,HYPER_BEAM
    ; 45,VENOMOTH
    db SLUDGE,PIN_MISSILE,SPORE,PSYCHIC_M
    ; 44,OMASTAR
    db AURORA_BEAM,REST,TSUNAMI,EARTHQUAKE
    ; 45,HITMONCHAN
    db FIRE_PUNCH,ICE_PUNCH,THUNDERPUNCH,JUMP_KICK
    ; 45,PINSIR
    db ICE_PUNCH,DIZZY_PUNCH,SWORDS_DANCE,TWINEEDLE
    db 0

CooltrainerFMove3:
    ; 44,VILEPLUME
    db RAZOR_LEAF,SLUDGE,SPORE,STUN_SPORE
    ; 43,DEWGONG
    db BODY_SLAM,REST,TSUNAMI,BLIZZARD
    ; 45,BEEDRILL
    db TWINEEDLE,SLUDGE,SWORDS_DANCE,AGILITY
    ; 41,SEAKING
    db AGILITY,WATERFALL,PSYCHIC_M,HYPER_BEAM
    ; 43,RAPIDASH
    db AGILITY,HORN_ATTACK,FIRE_PUNCH,HORN_DRILL
    ; 46,CHANSEY
    db REFLECT,SOFTBOILED,LOVELY_KISS,SEISMIC_TOSS
    db 0

CooltrainerFMove4:
    ; 41,PERSIAN
    db FLARE,SLASH,REST,THUNDERBOLT
    ; 43,NINETALES
    db TRAPHOLE,CONFUSE_RAY,FLAMETHROWER,FIRE_SPIN
    ; 43,SEADRA
    db DRAGON_RAGE,AGILITY,TSUNAMI,ICE_BEAM
    ; 44,BUTTERFREE
    db STUN_SPORE,PIN_MISSILE,PSYCHIC_M,SPORE
    ; 40,ELECTRODE
    db BODY_SLAM,THUNDER_WAVE,THUNDERBOLT,EXPLOSION
    ; 45,NIDOQUEEN
    db DIZZY_PUNCH,BLIZZARD,SLUDGE,EARTHQUAKE
    db 0

; ────────────────────────────────────────────────

CooltrainerMMove2:
    ; 44,EXEGGUTOR
    db STUN_SPORE,SLEEP_POWDER,PSYCHIC_M,EXPLOSION
    ; 44,CLOYSTER
    db SPIKE_CANNON,REST,BLIZZARD,EXPLOSION
    ; 44,ARCANINE
    db FIRE_SPIN,FIRE_BLAST,BODY_SLAM,REST
    ; 41,FEAROW
    db DRILL_PECK,AGILITY,MIRROR_MOVE,HYPER_BEAM
    ; 43,CLEFABLE
    db SOFTBOILED,MINIMIZE,BODY_SLAM,METRONOME
    ; 45,WEEZING
    db FLARE,SLUDGE,PSYCHIC_M,EXPLOSION
    db 0

CooltrainerMMove3:
    ; 44,KADABRA
    db RECOVER,PSYCHIC_M,HYPNOSIS,FLARE
    ; 43,TAUROS
    db BONE_CLUB,REST,BLIZZARD,EARTHQUAKE
    ; 45,KINGLER
    db CRABHAMMER,SWORDS_DANCE,HYPER_BEAM,WATERFALL
    ; 44,KABUTOPS
    db AURORA_BEAM,REST,TSUNAMI,TRAPHOLE
    ; 45,HITMONLEE
    db SEISMIC_TOSS,COUNTER,HI_JUMP_KICK,FIRE_PUNCH
    ; 45,GYARADOS
    db ICE_BEAM,BODY_SLAM,HYDRO_PUMP,HYPER_BEAM
    db 0

CooltrainerMMove4:
    ; 42,MAGNETON
    db TRI_ATTACK,CONVERSION,THUNDER_WAVE,THUNDER_M
    ; 41,DUGTRIO
    db SLASH,EARTHQUAKE,ROCK_THROW,TRI_ATTACK
    ; 43,GOLDUCK
    db SLASH,TSUNAMI,ICE_BEAM,AMNESIA
    ; 42,SCYTHER
    db SLASH,SWORDS_DANCE,SWOOP,TWINEEDLE
    ; 44,RATICATE
    db DOUBLE_TEAM,THUNDERBOLT,HYPER_FANG,SUPER_FANG
    ; 45,NIDOKING
    db DIZZY_PUNCH,SLUDGE,EARTHQUAKE,THUNDER_M
    db 0

; ────────────────────────────────────────────────

BlackBeltMove9:
    ; 43,MACHOKE
    db TRAPHOLE,JUMP_KICK,SEISMIC_TOSS,BODY_SLAM
    ; 45,GRAVELER
    db ROCK_SLIDE,THUNDERPUNCH,EARTHQUAKE,EXPLOSION
    ; 42,PARASECT
    db SLASH,TWINEEDLE,BARRAGE,SPORE
    ; 42,SNORLAX
    db HYPER_BEAM,AMNESIA,EARTHQUAKE,BODY_SLAM
    ; 44,GOLBAT
    db SWOOP,SLUDGE,MEGA_DRAIN,HYPER_FANG
    ; 43,POLIWRATH
    db TSUNAMI,ICE_PUNCH,HYPNOSIS,SUBMISSION
    db 0

; ────────────────────────────────────────────────

JugglerMove2:
    ; 43,HYPNO
    db FLARE,REFLECT,REST,PSYCHIC_M
    ; 43,TENTACRUEL
    db FLARE,ICE_BEAM,WATERFALL,SLUDGE
    ; 42,RAICHU
    db THUNDERBOLT,THUNDER_WAVE,THUNDERPUNCH,HYPER_FANG
    ; 44,DODRIO
    db DRILL_PECK,AGILITY,TRI_ATTACK,ROLLING_KICK
    ; 41,RHYHORN
    db THUNDERBOLT,SUBSTITUTE,BODY_SLAM,EARTHQUAKE
    ; 45,MUK
    db EXPLOSION,SLUDGE,THUNDERPUNCH,TOXIC
    db 0

JugglerMove5:
    ; 45,MR. MIME
    db FLARE,CONFUSE_RAY,MIRROR_MOVE,PSYCHIC_M
    ; 43,STARMIE
    db RECOVER,PSYBEAM,AURORA_BEAM,THUNDERBOLT
    ; 44,PIDGEOT
    db REFLECT,AGILITY,DRILL_PECK,HYPER_BEAM
    ; 41,MAROWAK
    db SWORDS_DANCE,ICE_PUNCH,EARTHQUAKE,BONEMERANG
    ; 42,PRIMEAPE
    db JUMP_KICK,TRAPHOLE,SEISMIC_TOSS,SUBMISSION
    ; 43,TANGELA
    db LEECH_SEED,SLEEP_POWDER,STUN_SPORE,SOLARBEAM
    db 0

; ────────────────────────────────────────────────

TamerMove5:
    ; 41,ELECTABUZZ
    db AGILITY,THUNDERBOLT,BODY_SLAM,THUNDER_WAVE
    ; 40,JYNX
    db LOVELY_KISS,PSYBEAM,BODY_SLAM,BLIZZARD
    ; 42,MAGMAR
    db FIRE_SPIN,FIRE_BLAST,BODY_SLAM,CONFUSE_RAY
    ; 44,KANGASKHAN
    db EARTHQUAKE,DIZZY_PUNCH,SUBSTITUTE,SLASH
    ; 45,ARBOK
    db EARTHQUAKE,FLARE,MEGA_DRAIN,SLUDGE
    ; 45,SANDSLASH
    db SLASH,SWORDS_DANCE,EARTHQUAKE,TWINEEDLE
    db 0

; ────────────────────────────────────────────────

PokemaniacMove6:
    ; 45,DRAGONAIR
    db LIGHT_SCREEN,THUNDER_WAVE,FLAMETHROWER,ICE_BEAM
    ; 43,LAPRAS
    db THUNDER_M,REST,THUNDER_WAVE,ICE_BEAM
    ; 45,SLOWBRO
    db WITHDRAW,TSUNAMI,AMNESIA,PSYBEAM
    ; 45,LICKITUNG
    db EARTHQUAKE,BODY_SLAM,SOFTBOILED,SWORDS_DANCE
    ; 42,HAUNTER
    db HYPNOSIS,NIGHT_SHADE,PSYCHIC_M,THUNDERBOLT
    ; 44,FARFETCH'D
    db BLADE,SWORDS_DANCE,SLASH,SWOOP
    db 0

PokemaniacMove8:
    ; 26,DITTO
    db TRANSFORM,0,0,0
    db 0

; ────────────────────────────────────────────────

ChannelerMove14:
    ; 35,GASTLY
    db ABSORB,LICK,POISON_GAS,NIGHT_SHADE
    ; 35,HAUNTER
    db MEGA_DRAIN,SMOG,CONFUSION,NIGHT_SHADE
    db 0

ChannelerMove15:
    ; 38,HAUNTER
    db HYPNOSIS,DREAM_EATER,THUNDERPUNCH,CONFUSION
    db 0

ChannelerMove16:
    ; 33,GASTLY
    db HYPNOSIS,DREAM_EATER,CONFUSE_RAY,SMOG
    ; 33,GASTLY
    db POISON_GAS,NIGHT_SHADE,LEECH_LIFE,LICK
    ; 33,HAUNTER
    db PSYWAVE,HYPNOSIS,NIGHT_SHADE,CONFUSION
    db 0

; ────────────────────────────────────────────────
