; pokemon's overworld sprites
SPRITE_MON       EQU $0
SPRITE_BALL_M    EQU $1
SPRITE_HELIX     EQU $2
SPRITE_FAIRY     EQU $3
SPRITE_BIRD_M    EQU $4
SPRITE_WATER     EQU $5
SPRITE_BUG       EQU $6
SPRITE_GRASS     EQU $7
SPRITE_SNAKE     EQU $8
SPRITE_QUADRUPED EQU $9

; overworld sprites
SPRITE_RED                       EQU $01
SPRITE_BLUE                      EQU $02
SPRITE_OAK                       EQU $03
SPRITE_BUG_CATCHER               EQU $04
SPRITE_SLOWBRO                   EQU $05
SPRITE_LASS                      EQU $06
SPRITE_BLACK_HAIR_BOY_1          EQU $07
SPRITE_LITTLE_GIRL               EQU $08
SPRITE_BIRD                      EQU $09
SPRITE_FAT_BALD_GUY              EQU $0a
SPRITE_GAMBLER                   EQU $0b
SPRITE_BLACK_HAIR_BOY_2          EQU $0c
SPRITE_GIRL                      EQU $0d
SPRITE_HIKER                     EQU $0e
SPRITE_FOULARD_WOMAN             EQU $0f
SPRITE_GENTLEMAN                 EQU $10
SPRITE_DAISY                     EQU $11
SPRITE_BIKER                     EQU $12
SPRITE_SAILOR                    EQU $13
SPRITE_COOK                      EQU $14
SPRITE_BIKE_SHOP_GUY             EQU $15
SPRITE_MR_FUJI                   EQU $16
SPRITE_GIOVANNI                  EQU $17
SPRITE_ROCKET                    EQU $18
SPRITE_MEDIUM                    EQU $19
SPRITE_WAITER                    EQU $1a
SPRITE_ERIKA                     EQU $1b
SPRITE_MOM_GEISHA                EQU $1c
SPRITE_BRUNETTE_GIRL             EQU $1d
SPRITE_LANCE                     EQU $1e
SPRITE_OAK_SCIENTIST_AIDE        EQU $1f
SPRITE_OAK_AIDE                  EQU $20
SPRITE_ROCKER                    EQU $21
SPRITE_SWIMMER                   EQU $22
SPRITE_WHITE_PLAYER              EQU $23
SPRITE_GYM_HELPER                EQU $24
SPRITE_OLD_PERSON                EQU $25
SPRITE_MART_GUY                  EQU $26
SPRITE_FISHER                    EQU $27
SPRITE_OLD_MEDIUM_WOMAN          EQU $28
SPRITE_NURSE                     EQU $29
SPRITE_CABLE_CLUB_WOMAN          EQU $2a
SPRITE_MR_MASTERBALL             EQU $2b
SPRITE_LAPRAS_GIVER              EQU $2c
SPRITE_WARDEN                    EQU $2d
SPRITE_SS_CAPTAIN                EQU $2e
SPRITE_FISHER2                   EQU $2f
SPRITE_BLACKBELT                 EQU $30
SPRITE_GUARD                     EQU $31
;SPRITE_NOT_DEFINED              EQU $32
SPRITE_MOM                       EQU $33
SPRITE_BALDING_GUY               EQU $34
SPRITE_YOUNG_BOY                 EQU $35
SPRITE_GAMEBOY_KID               EQU $36
SPRITE_GAMEBOY_KID_COPY          EQU $37
SPRITE_CLEFAIRY                  EQU $38
SPRITE_AGATHA                    EQU $39
SPRITE_BRUNO                     EQU $3a
SPRITE_LORELEI                   EQU $3b
SPRITE_SEEL                      EQU $3c

SPRITE_ALAKAZAM                  EQU $3d
SPRITE_MACHAMP                   EQU $3e
SPRITE_GOLEM                     EQU $3f
SPRITE_GENGAR                    EQU $40
SPRITE_LAPRAS                    EQU $41
SPRITE_AERODACTYL                EQU $42
SPRITE_ARTICUNO                  EQU $43
SPRITE_ZAPDOS                    EQU $44
SPRITE_MOLTRES                   EQU $45
SPRITE_DRATINI                   EQU $46
SPRITE_MEWTWO                    EQU $47

SPRITE_BALL                      EQU $48
SPRITE_OMANYTE                   EQU $49
SPRITE_BOULDER                   EQU $4a
SPRITE_PAPER_SHEET               EQU $4b
SPRITE_BOOK_MAP_DEX              EQU $4c
SPRITE_CLIPBOARD                 EQU $4d
SPRITE_SNORLAX                   EQU $4e
SPRITE_OLD_AMBER_COPY            EQU $4f
SPRITE_OLD_AMBER                 EQU $50
SPRITE_LYING_OLD_MAN_UNUSED_1    EQU $51
SPRITE_LYING_OLD_MAN_UNUSED_2    EQU $52
SPRITE_LYING_OLD_MAN             EQU $53
SPRITE_BASKET                    EQU $54

; different kinds of people events
ITEM    EQU $80
TRAINER EQU $40