    db NORMAL,ROCK,05
    db NORMAL,GHOST,00
    db NORMAL,METAL,02

    db FIGHTING,POISON,05
    db FIGHTING,WIND,05
    db FIGHTING,PSYCHIC,05
    db FIGHTING,BUG,05
    db FIGHTING,ROCK,20
    db FIGHTING,ICE,20
    db FIGHTING,GHOST,00
    db FIGHTING,RUBBER,20
    db FIGHTING,METAL,20
    db FIGHTING,IVORY,15

    db WIND,FIGHTING,20
    db WIND,GRASS,20
    db WIND,ROCK,05
    db WIND,GHOST,20
    db WIND,IVORY,08
    db WIND,METAL,05

    db POISON,GRASS,20
    db POISON,POISON,05
    db POISON,GROUND,05
    db POISON,BUG,20
    db POISON,ROCK,05
    db POISON,FIGHTING,20
    db POISON,METAL,00

    db GROUND,FIRE,20
    db GROUND,ELECTRIC,20
    db GROUND,GRASS,05
    db GROUND,BUG,05
    db GROUND,ROCK,20
    db GROUND,POISON,20
    db GROUND,WIND,00
    db GROUND,RUBBER,05
    db GROUND,DRAGON,02
    db GROUND,METAL,15

    db ROCK,ROCK,05
    db ROCK,FIRE,15
    db ROCK,FIGHTING,05
    db ROCK,GROUND,05
    db ROCK,WIND,20
    db ROCK,BUG,15
    db ROCK,ICE,20
    db ROCK,METAL,05
    db ROCK,DRAGON,15
    db ROCK,GRASS,05

    db BUG,FIRE,05
    db BUG,GRASS,20
    db BUG,WIND,05
    db BUG,PSYCHIC,20
    db BUG,POISON,05
    db BUG,METAL,02
    db BUG,GROUND,20
    db BUG,ICE,08

    db METAL,METAL,05
    db METAL,IVORY,12
    db METAL,FIRE,08
    db METAL,ELECTRIC,05
    db METAL,DRAGON,20
    db METAL,GHOST,00
    db METAL,GRASS,12

    db IVORY,ROCK,05
    db IVORY,GHOST,00
    db IVORY,METAL,05
    db IVORY,RUBBER,15
    db IVORY,FIRE,08
    db IVORY,BUG,15
    db IVORY,POISON,08

    db RUBBER,ROCK,05
    db RUBBER,GHOST,00
    db RUBBER,METAL,05
    db RUBBER,ELECTRIC,20
    db RUBBER,IVORY,06
    db RUBBER,WATER,15
    db RUBBER,POISON,08

    db FIRE,FIRE,05
    db FIRE,GRASS,20
    db FIRE,ICE,20
    db FIRE,WATER,05
    db FIRE,BUG,20
    db FIRE,ROCK,02
    db FIRE,DRAGON,05
    db FIRE,METAL,15
    db FIRE,GROUND,05

    db WATER,WATER,05
    db WATER,FIRE,25
    db WATER,ROCK,25
    db WATER,GRASS,05
    db WATER,GROUND,20
    db WATER,DRAGON,08
    db WATER,RUBBER,05
    db WATER,METAL,12

    db GRASS,GRASS,05
    db GRASS,WATER,20
    db GRASS,FIRE,02
    db GRASS,GROUND,20
    db GRASS,BUG,05
    db GRASS,POISON,05
    db GRASS,ROCK,20
    db GRASS,WIND,05
    db GRASS,DRAGON,08
    db GRASS,METAL,08

    db ELECTRIC,WATER,20
    db ELECTRIC,ELECTRIC,05
    db ELECTRIC,GRASS,05
    db ELECTRIC,GROUND,00
    db ELECTRIC,WIND,20
    db ELECTRIC,DRAGON,15
    db ELECTRIC,RUBBER,05
    db ELECTRIC,METAL,25
    db ELECTRIC,ROCK,02
    db ELECTRIC,IVORY,08

    db PSYCHIC,PSYCHIC,05
    db PSYCHIC,FIGHTING,20
    db PSYCHIC,POISON,20
    db PSYCHIC,GHOST,02
    db PSYCHIC,BUG,05
    db PSYCHIC,METAL,08
    db PSYCHIC,GRASS,07

    db ICE,ICE,05
    db ICE,WATER,05
    db ICE,GRASS,20
    db ICE,GROUND,15
    db ICE,WIND,20
    db ICE,DRAGON,25
    db ICE,FIRE,05
    db ICE,BUG,15
    db ICE,FIGHTING,05
    db ICE,METAL,08
    db ICE,ROCK,15