    db NORMAL,ROCK,05
    db NORMAL,GHOST,00
    db NORMAL,METAL,02

    db FIGHTING,POISON,05
    db FIGHTING,WIND,05
    db FIGHTING,PSYCHIC,05
    db FIGHTING,BUG,05
    db FIGHTING,ROCK,20
    db FIGHTING,ICE,20
    db FIGHTING,GHOST,00
    db FIGHTING,RUBBER,20
    db FIGHTING,METAL,20
    db FIGHTING,IVORY,14

    db WIND,FIGHTING,20
    db WIND,GRASS,15
    db WIND,ROCK,05
    db WIND,GHOST,20
    db WIND,IVORY,08
    db WIND,METAL,05
    db WIND,ELECTRIC,05
    db WIND,DRAGON,08

    db POISON,GRASS,20
    db POISON,POISON,04
    db POISON,GROUND,05
    db POISON,BUG,20
    db POISON,ROCK,04
    db POISON,FIGHTING,20
    db POISON,METAL,00

    db GROUND,FIRE,20
    db GROUND,ELECTRIC,20
    db GROUND,GRASS,05
    db GROUND,BUG,06
    db GROUND,ROCK,20
    db GROUND,POISON,20
    db GROUND,WIND,00
    db GROUND,RUBBER,05
    db GROUND,DRAGON,02
    db GROUND,METAL,15

    db ROCK,ROCK,05
    db ROCK,FIRE,15
    db ROCK,FIGHTING,02
    db ROCK,GROUND,05
    db ROCK,WIND,20
    db ROCK,BUG,13
    db ROCK,ICE,12
    db ROCK,METAL,05
    db ROCK,DRAGON,14
    db ROCK,GRASS,04
    db ROCK,RUBBER,08

    db BUG,FIRE,05
    db BUG,GRASS,20
    db BUG,WIND,05
    db BUG,PSYCHIC,20
    db BUG,POISON,05
    db BUG,METAL,02
    db BUG,GROUND,20
    db BUG,ICE,08

    db METAL,METAL,05
    db METAL,FIRE,09
    db METAL,ELECTRIC,05
    db METAL,DRAGON,20
    db METAL,GHOST,00
    db METAL,GRASS,12

    db IVORY,ROCK,05
    db IVORY,GHOST,00
    db IVORY,METAL,04
    db IVORY,RUBBER,14
    db IVORY,FIRE,09
    db IVORY,BUG,13
    db IVORY,POISON,09
    db IVORY,ELECTRIC,08
    db IVORY,GRASS,13

    db RUBBER,ROCK,04
    db RUBBER,GHOST,00
    db RUBBER,METAL,03
    db RUBBER,ELECTRIC,17
    db RUBBER,IVORY,09
    db RUBBER,WATER,11
    db RUBBER,ICE,08
    db RUBBER,FIRE,09

    db FIRE,FIRE,08
    db FIRE,GRASS,20
    db FIRE,ICE,25
    db FIRE,WATER,04
    db FIRE,BUG,20
    db FIRE,ROCK,04
    db FIRE,DRAGON,05
    db FIRE,METAL,18
    db FIRE,GROUND,05
    db FIRE,GHOST,18

    db WATER,WATER,04
    db WATER,FIRE,25
    db WATER,ROCK,25
    db WATER,GRASS,04
    db WATER,GROUND,20
    db WATER,DRAGON,08
    db WATER,RUBBER,09
    db WATER,METAL,13
    db WATER,ICE,07

    db GRASS,GRASS,08
    db GRASS,WATER,20
    db GRASS,FIRE,05
    db GRASS,GROUND,20
    db GRASS,BUG,05
    db GRASS,POISON,05
    db GRASS,ROCK,20
    db GRASS,WIND,05
    db GRASS,DRAGON,08
    db GRASS,METAL,08

    db ELECTRIC,WATER,20
    db ELECTRIC,ELECTRIC,05
    db ELECTRIC,GRASS,05
    db ELECTRIC,GROUND,00
    db ELECTRIC,WIND,20
    db ELECTRIC,DRAGON,15
    db ELECTRIC,RUBBER,07
    db ELECTRIC,METAL,25
    db ELECTRIC,ROCK,00
    db ELECTRIC,IVORY,08
    db ELECTRIC,ICE,05

    db PSYCHIC,PSYCHIC,04
    db PSYCHIC,FIGHTING,20
    db PSYCHIC,POISON,20
    db PSYCHIC,GHOST,02
    db PSYCHIC,BUG,05
    db PSYCHIC,METAL,07
    db PSYCHIC,GRASS,06

    db ICE,ICE,05
    db ICE,WATER,05
    db ICE,GRASS,18
    db ICE,GROUND,15
    db ICE,WIND,20
    db ICE,DRAGON,25
    db ICE,FIRE,05
    db ICE,BUG,15
    db ICE,FIGHTING,02
    db ICE,METAL,08
    db ICE,ROCK,15